ubxfwupdate: checksum.h File Reference
checksum.h File Reference
checksum routines for UBX protocol and firmware image
#include <stdio.h>
#include "types.h"
Functions
BOOL CheckUbxChecksumU4 (const U4 *pData, size_t numBytes)
Check UBX checksum on Words.
unsigned short GetUbxChecksumU1 (const U1 *pData, size_t length)
Calculate UBX checksum over pData.
void GetUbxChecksumU4 (U4 *pChk_a, U4 *pChk_b, const U4 *pData, size_t numBytes)
Calculate UBX checksum over pData.
Detailed Description
checksum routines for UBX protocol and firmware image
Definition in file checksum.h.
Function Documentation
BOOL CheckUbxChecksumU4 (const U4 * pData, size_t numBytes)
Check UBX checksum on Words.
Check if the data beginning at pData with size numBytes has appended the correct checksum, operating on 4-Byte words
Parameters
pData pointer to checksum calculation range begin
numBytes length of checksum calculation range in bytes
Returns
TRUE if the checksum is correct, FALSE else
Definition at line 50 of file checksum.c.
References GetUbxChecksumU4().
Referenced by ValidateImage().
 {
     U4 chk_a = 0;
     U4 chk_b = 0;
     GetUbxChecksumU4(&chk_a, &chk_b, pData, numBytes);
     pData += (numBytes/4);
     return (chk_a == *pData && chk_b == *(pData+1));
 }
unsigned short GetUbxChecksumU1 (const U1 * pData, size_t length)
Calculate UBX checksum over pData.
Calculates the checksum over pData and returns it.
Parameters
pData pointer to Data to calculate checksum on
length length of data to calculate checksum on
Returns
2 Bytes checksum, crc_a in low byte
Definition at line 61 of file checksum.c.
Referenced by UbxCheckCrc(), and UbxCreateMessage().
 {
     U1 chk_a = 0;
     U1 chk_b = 0;
     while (length--)
     {
         chk_a += *pData++;
         chk_b += chk_a;
     }
     return ((U2)(chk_b)<<8) | (U2)(chk_a);
 }
void GetUbxChecksumU4 (U4 * pChk_a, U4 * pChk_b, const U4 * pData, size_t numBytes)
Calculate UBX checksum over pData.
Calculates the checksum over pData and returns it.
Parameters
pChk_a pointer to U4 receiving first word of checksum
pChk_b pointer to U4 receiving second word of checksum
pData pointer to Data to calculate checksum on
numBytes length of data in bytes to calculate checksum on
Definition at line 33 of file checksum.c.
Referenced by CheckUbxChecksumU4(), and verifyImage().
 {
     U4 chk_a = 0;
     U4 chk_b = 0;
     numBytes /= 4;
     while (numBytes--)
     {
         chk_a += *pData++;
         chk_b += chk_a;
     }
     *pChk_a = chk_a;
     *pChk_b = chk_b;
 }