ubxfwupdate: flash.h File Reference
flash.h File Reference
Flash organization stuff.
#include "types.h"
Data Structures
struct BLOCK_DEF_s
Flash sector block organization description.
struct BLOCK_ARR_s
Array of block definitions.
Typedefs
typedef struct BLOCK_DEF_s BLOCK_DEF_t
Flash sector block organization description.
typedef BLOCK_DEF_t * BLOCK_DEF_pt
pointer to BLOCK_DEF_t type
typedef struct BLOCK_ARR_s BLOCK_ARR_t
Array of block definitions.
typedef BLOCK_ARR_t * BLOCK_ARR_pt
pointer to BLOCK_ARR_t type
Functions
I4 GetSectorNrForSize (const U4 Offset, const U4 FwSize, const BLOCK_ARR_pt pFlashdef)
Get the number of sectors the firmware fits in.
I4 GetSectorNrForAddress (const U4 Address, const U4 Base, const U4 Offset, const BLOCK_ARR_pt pFlashdef)
Get the sector number at address.
I4 GetPacketNrForSector (const U4 Sector, const BLOCK_ARR_pt pFlashdef, const U4 PacketSize)
Get the number of the packet for the given sector.
U4 GetPacketNrForAddress (const U4 Address, const U4 Base, const U4 PacketSize)
Get the number of the packet for the given address.
void DumpFlashInfo (BLOCK_ARR_t const *const pkFlashOrg, const U4 FlashSize)
Dump Flash organization info.
BOOL GetFlashOrganisation (U2 const ManId, U2 const DevId, BLOCK_ARR_pt pBlocks, U4 *const pSize, CH const *const Filename)
Parse a file for flash memory architecture descriptions.
void clearBlocks (BLOCK_ARR_pt pBlocks)
Clear the array of block contents.
BOOL addBlock (BLOCK_ARR_pt pBlocks, BLOCK_DEF_pt const pNewBlock)
Clear the array of block contents.
Detailed Description
Flash organization stuff.
Provides an interface to transform Addresses to sector numbers and Packet numbers and parsing flash definition text files
Definition in file flash.h.
Typedef Documentation
typedef BLOCK_ARR_t* BLOCK_ARR_pt
pointer to BLOCK_ARR_t type
Definition at line 54 of file flash.h.
typedef struct BLOCK_ARR_s BLOCK_ARR_t
Array of block definitions.
typedef BLOCK_DEF_t* BLOCK_DEF_pt
pointer to BLOCK_DEF_t type
Definition at line 46 of file flash.h.
typedef struct BLOCK_DEF_s BLOCK_DEF_t
Flash sector block organization description.
Function Documentation
BOOL addBlock (BLOCK_ARR_pt pBlocks, BLOCK_DEF_pt const pNewBlock)
Clear the array of block contents.
Parameters
pBlocks Block array to be cleared
pNewBlock Block to be added to pBlocks
Returns
TRUE on success, FALSE otherwise
Definition at line 470 of file flash.c.
References FALSE, and TRUE.
Referenced by GetFlashOrganisation(), and UpdateFirmware().
 {
     assert(pBlocks && pNewBlock);
     assert( ( pBlocks->pBlocks &&  pBlocks->NumBlocks)
          || (!pBlocks->pBlocks && !pBlocks->NumBlocks) );
     BOOL result=FALSE;
     BLOCK_DEF_pt pTmpBlocks = (BLOCK_DEF_pt) realloc(pBlocks->pBlocks, (size_t)((pBlocks->NumBlocks + 1)*sizeof(*pNewBlock)));
     if(pTmpBlocks)
     {
         memcpy(&pTmpBlocks[pBlocks->NumBlocks], pNewBlock, sizeof(*pNewBlock));
         pBlocks->pBlocks=pTmpBlocks;
         ++pBlocks->NumBlocks;
         result=TRUE;
     }
     return result;
 }
void clearBlocks (BLOCK_ARR_pt pBlocks)
Clear the array of block contents.
Parameters
pBlocks Block array to be cleared
Definition at line 460 of file flash.c.
References NULL.
Referenced by GetFlashOrganisation(), and UpdateFirmware().
 {
     assert(pBlocks);
     assert( ( pBlocks->pBlocks &&  pBlocks->NumBlocks)
          || (!pBlocks->pBlocks && !pBlocks->NumBlocks) );
     free(pBlocks->pBlocks);
     pBlocks->pBlocks=NULL;
     pBlocks->NumBlocks=0;
 }
void DumpFlashInfo (BLOCK_ARR_t const *const pkFlashOrg, const U4 FlashSize)
Dump Flash organization info.
Parameters
pkFlashOrg pointer to flash organization vector
FlashSize size of Flash
Definition at line 319 of file flash.c.
References MESSAGE(), and MSG_DBG.
Referenced by UpdateFirmware().
 {
     assert(pkFlashOrg);
     MESSAGE(MSG_DBG, "Flash size:   %d", FlashSize);
     size_t i;
     for(i = 0; i<pkFlashOrg->NumBlocks; i++)
     {
         MESSAGE(MSG_DBG, " Flash block:  %d x %d", pkFlashOrg->pBlocks[i].Count, pkFlashOrg->pBlocks[i].Size);
     }
 }
BOOL GetFlashOrganisation (U2 const ManId, U2 const DevId, BLOCK_ARR_pt pBlocks, U4 *const pSize, CH const *const Filename)
Parse a file for flash memory architecture descriptions.
Parameters
ManId the manufacturer id of the flash
DevId the device id of the flash
pBlocks pointer where to store the flash definition
pSize pointer to size of the flash
Filename name of the flash definition file
Returns
TRUE if successful, FALSE otherwise
Definition at line 331 of file flash.c.
References addBlock(), clearBlocks(), BLOCK_DEF_s::Count, FALSE, flashTxt, MESSAGE(), MSG_DBG, MSG_ERR, NULL, and BLOCK_DEF_s::Size.
Referenced by UpdateFirmware().
 {
     assert(pBlocks);
     CH* file = NULL;
     CH* fileTmp = NULL;
     if (strlen(Filename)>0) // is there a file at all?
     {
         FILE *stream=fopen(Filename, "r");
         if (!stream)
         {
             //MESSAGE(MSG_ERR, "Could not open file '%s'", Filename);
             return FALSE;
         }
         //clear flash definition description vector
         clearBlocks(pBlocks);
         //get file size and allocate memory
         int ret=fseek(stream, 0, SEEK_END);
         if(ret)
         {
             fclose(stream);
             return FALSE;
         }
         long filesize = ftell(stream);
         fileTmp = (CH*) malloc(filesize);
         if (fileTmp == NULL)
         {
             MESSAGE(MSG_ERR, "Allocation of file buffer memory failed.");
             fclose(stream);
             return FALSE;
         }
         //copy file content to ram buffer
         rewind(stream);
         size_t numRead=fread(fileTmp, 1, filesize, stream);
         fclose(stream);
         if(numRead!=(size_t)filesize)
         {
             free(fileTmp);
             return FALSE;
         }
         file = fileTmp;
     }
     else
     {
         // use compiled-in version
         MESSAGE(MSG_DBG,"Use compiled-in Flash Description");
         fileTmp = (CH*) malloc(sizeof(flashTxt));
         if (fileTmp == NULL)
         {
             MESSAGE(MSG_ERR, "Allocation of file buffer memory failed.");
             return FALSE;
         }
         memcpy(fileTmp, flashTxt, sizeof(flashTxt));
         file = fileTmp;
     }
     //file content now in 'file', process it
     CH* pEnd;
     CH key[32];
     //create search string
     sprintf(key, "0x%04X-0x%04X", ManId, DevId);
     //search for manid, devid
     CH* pPos = strstr(file, key);
     if (pPos == NULL)
     {
         free(file);
         return FALSE;
     }
     //description was found, extract organization
     pPos = strchr(pPos, '=');
     if (pPos == NULL)
     {
         free(file);
         return FALSE;
     }
     // remove equal sign and all leading spaces
     pPos += strspn(pPos, "\t =");
     // remove comments
     pEnd = strpbrk(pPos, ";\r\n\0");
     if(pEnd == NULL)
     {
         free(file);
         return FALSE;
     }
     *pEnd = '\0';
     // remove trailing spaces
     while ((pEnd >= pPos) && (isspace(*pEnd) || (*pEnd == 0) || (*pEnd == '\n') || (*pEnd == '\r')))
     {
         *pEnd = '\0';
         pEnd --;
     }
     // parse syntax
     *pSize = 0;
     while (*pPos != '\0')
     {
         CH* stopstring;
         U4 value = strtoul(pPos, &stopstring, 10);
         if ((stopstring > pPos) && (*stopstring == 'x') && (value > 0))
         {
             BLOCK_DEF_t block;
             block.Count = value;
             pPos = stopstring + 1;
             value = strtoul(pPos, &stopstring, 10);
             if ((stopstring > pPos) && (value > 0))
             {
                 block.Size = value * 1024;
                 pPos = stopstring;
                 *pSize += block.Count * block.Size;
                 addBlock(pBlocks, &block);
                 //skip spaces
                 while (isspace(*pPos) || *pPos == ',')
                 {
                     pPos ++;
                 }
             }
         }
     }
     if (fileTmp)
         free(fileTmp);
     return (pBlocks->NumBlocks != 0);
 }
U4 GetPacketNrForAddress (const U4 Address, const U4 Base, const U4 PacketSize)
Get the number of the packet for the given address.
Parameters
Address Address to get packet number for
Base Address of firmware base
PacketSize Size of one download packet
Returns
Packet number if success, -1 if packet cannot be determined
Definition at line 310 of file flash.c.
Referenced by updProcessMessages().
 {
     U4 RelAddr = Address - Base;
     U4 Packet = RelAddr / PacketSize;
     return Packet;
 }
I4 GetPacketNrForSector (const U4 Sector, const BLOCK_ARR_pt pFlashdef, const U4 PacketSize)
Get the number of the packet for the given sector.
Parameters
Sector number of the sector
pFlashdef pointer to flash organization structure array
PacketSize packet size
Returns
number of the according packet, -1 if packet cannot be determined
Definition at line 216 of file flash.c.
References MESSAGE(), and MSG_ERR.
Referenced by updDumpAck(), updEraseSector(), updInit(), and updProcessMessages().
 {
     assert(pFlashdef);
     if(pFlashdef->NumBlocks == 1)
     {
         // uniform flash
         return Sector * pFlashdef->pBlocks[0].Size / PacketSize;
     }
     else
     {
         I4 packet   = 0;
         U4 block    = 0;  //actual block
         U4 blocksec = 0;  //sector in the actual block
         U4 sec_cnt  = 0;
         // sum up the number of packets of the sectors
         while (sec_cnt < Sector)
         {
             sec_cnt++;
             if (block >= pFlashdef->NumBlocks)
             {
                 //somewhat went wrong
                 MESSAGE(MSG_ERR, "GetPacketNrForSector: Sec %u Packetsize %u", Sector, PacketSize);
                 return -1;
             }
             packet += pFlashdef->pBlocks[block].Size / PacketSize;
             blocksec++;
             if (blocksec >= pFlashdef->pBlocks[block].Count)
             {
                 block++;
                 blocksec = 0;
             }
         }
         return packet;
     }
 }
I4 GetSectorNrForAddress (const U4 Address, const U4 Base, const U4 Offset, const BLOCK_ARR_pt pFlashdef)
Get the sector number at address.
Parameters
Address Address to get sector number at
Base Base address of firmware
Offset Offset of firmware from flash base
pFlashdef Pointer to flash sector definition information
Returns
sector number if found, -1 if it cannot be determined
Definition at line 255 of file flash.c.
Referenced by updDumpAck(), and updProcessMessages().
 {
     assert(pFlashdef);
     U4 block    = 0;  //actual block
     U4 blocksec = 0;  //sector in the actual block
     // advance block and blocksec to offset address
     U4 addr = 0;
     while (addr < Offset)
     {
         addr += pFlashdef->pBlocks[block].Size;
         blocksec++;
         if (blocksec >= pFlashdef->pBlocks[block].Count)
         {
             //next block
             block++;
             blocksec = 0;
             if (block >= pFlashdef->NumBlocks)
             {
                 //cannot erase a section behind size of flash
                 return -1;
             }
         }
     }
     // sum up the number of sectors
     U4 sec_cnt = 0;
     while (addr < (Address-Base+Offset))
     {
         addr += pFlashdef->pBlocks[block].Size;
         // address within the limits of the actual sector?
         if (addr > (Address-Base+Offset))
         {
             break;
         }
         // perhaps address fits into next sector's ranges
         sec_cnt ++;
         blocksec++;
         if (blocksec >= pFlashdef->pBlocks[block].Count)
         {
             block++;
             blocksec = 0;
             if (block >= pFlashdef->NumBlocks)
             {
                 // there are no more sectors available on flash
                 return -1;
             }
         }
     }
     return sec_cnt;
 }
I4 GetSectorNrForSize (const U4 Offset, const U4 FwSize, const BLOCK_ARR_pt pFlashdef)
Get the number of sectors the firmware fits in.
Parameters
Offset the offset of the firmware from flash base
FwSize the size of the firmware
pFlashdef pointer to array containing flash organization
Returns
number of sectors required, -1 if it cannot be determined
Definition at line 169 of file flash.c.
References MESSAGE(), and MSG_ERR.
Referenced by UpdateFirmware().
 {
     assert(pFlashdef);
     U4 size        = 0;  //size
     U4 block       = 0;  //actual block
     U4 blocksec    = 0;  //sector in the actual block
     U4 sectorNr    = 0;  //count sector numbers
     U4 addr = 0;
     while (addr < Offset)
     {
         addr += pFlashdef->pBlocks[block].Size;
         blocksec++;
         if (blocksec >= pFlashdef->pBlocks[block].Count)
         {
             block++;
             blocksec = 0;
             if (block >= pFlashdef->NumBlocks)
             {
                 //there are no more sectors behind size of flash
                 return -1;
             }
         }
     }
     while (size < FwSize)
     {
         if ((block >= pFlashdef->NumBlocks) && (size < FwSize))
         {
             //somewhat went wrong
             MESSAGE(MSG_ERR, "Cannot determine packet nr for size!");
             return -1;
         }
         sectorNr ++;
         size += pFlashdef->pBlocks[block].Size;
         blocksec++;
         if (blocksec >= pFlashdef->pBlocks[block].Count)
         {
             block++;
             blocksec = 0;
         }
     }
     return sectorNr;
 }