ubxfwupdate: image.h File Reference
image.h File Reference
Definitions concerning the firmware image.
#include "types.h"
Data Structures
union FWHEADER_u
Header of firmware image.
struct FWFOOTERINFO_u
structure holding data extracted from image footer
Typedefs
typedef union FWHEADER_u FWHEADER_t
Header of firmware image.
typedef FWHEADER_t * FWHEADER_pt
pointer to FWHEADER_t
typedef struct FWFOOTERINFO_u FWFOOTERINFO_t
structure holding data extracted from image footer
Functions
U4 ValidateImage (FWHEADER_t const *pImage, const size_t ImageSize, FWFOOTERINFO_t *pFwFooter)
Validate firmware image.
BOOL OpenAndBufferFile (const CH *BinaryFileName, FWHEADER_t **ppFileContent, size_t *pFileSize)
Open file and buffer it in RAM.
Detailed Description
Definitions concerning the firmware image.
Definition in file image.h.
Typedef Documentation
typedef struct FWFOOTERINFO_u FWFOOTERINFO_t
structure holding data extracted from image footer
typedef FWHEADER_t* FWHEADER_pt
pointer to FWHEADER_t
Definition at line 53 of file image.h.
typedef union FWHEADER_u FWHEADER_t
Header of firmware image.
Function Documentation
BOOL OpenAndBufferFile (const CH * BinaryFileName, FWHEADER_t ** ppFileContent, size_t * pFileSize)
Open file and buffer it in RAM.
Opens a file with platform-independent method (file streams) and copies the content into a dynamically allocated buffer. The pointer to the beginning of the buffer is returned in pFileContent. The caller is responsible of freeing the memory at *ppFileContent if the return value is TRUE.
Parameters
BinaryFileName Filename of file to open
ppFileContent pointer to buffer to receive file content
pFileSize pointer to file size
Returns
TRUE if the file could be buffered, FALSE else
Definition at line 165 of file image.c.
References FALSE, MESSAGE(), MSG_ERR, NULL, and TRUE.
Referenced by UpdateFirmware().
 {
     if (!BinaryFileName || !strlen(BinaryFileName))
     {
         MESSAGE(MSG_ERR, "File '%s' is not valid", BinaryFileName);
         return FALSE;
     }
     FILE *stream=fopen(BinaryFileName, "rb");
     if (!stream)
     {
         MESSAGE(MSG_ERR, "Could not open file '%s'.", BinaryFileName);
         return FALSE;
     }
     //get filesize and allocate memory
     int ret=fseek(stream, 0, SEEK_END);
     if(ret)
     {
         MESSAGE(MSG_ERR, "Could not set pointer to start in file '%s'", BinaryFileName);
         fclose(stream);
         return FALSE;
     }
     long filesize = ftell(stream);
     long ffAppend = (4 - (filesize & 0x3)) & 0x3;
     CH* fileTmp = (CH*)malloc(filesize + ffAppend);
     if (fileTmp == NULL)
     {
         MESSAGE(MSG_ERR, "Allocation of file buffer memory failed.");
         fclose(stream);
         return FALSE;
     }
     //copy file content to ram buffer
     ret=fseek(stream, 0, SEEK_SET);
     if(ret)
     {
         MESSAGE(MSG_ERR, "Seeking in the file failed.");
         fclose(stream);
         free(fileTmp);
         return FALSE;
     }
     // Read data
     size_t numRead=fread(fileTmp, 1, (size_t)filesize, stream);
     fclose(stream);
     if(numRead!=(size_t)filesize)
     {
         MESSAGE(MSG_ERR, "Wrong number of bytes read. Read = %ld, Expected = %ld", numRead, filesize);
         free(fileTmp);
         return FALSE;
     }
     memset(fileTmp + filesize, 0xFF, ffAppend); // append FFs
     *pFileSize = filesize + ffAppend;
     *ppFileContent = (FWHEADER_t*)fileTmp;
     return TRUE;
 }
U4 ValidateImage (FWHEADER_t const * pImage, const size_t ImageSize, FWFOOTERINFO_t * pFwFooter)
Validate firmware image.
Performs several consistency checks on the firmware image to ensure data consistency and a correct image.
Parameters
pImage pointer to buffer containing firmware image file contents
ImageSize Size of Buffer containing Image
pFwFooter Pointer to data extracted from image footer
Returns
0 if the buffer doesn't contains a valid image, the generation otherwise
Definition at line 51 of file image.c.
References CheckUbxChecksumU4(), EXT2_BASE, FALSE, lib_crc_crc32(), magicG50, magicG70, MESSAGE(), MSG_DBG, MSG_ERR, MSG_LEV2, NUMOF, and TRUE.
Referenced by UpdateFirmware().
 {
     CH verString[100];
     //check file size, must be at least header size
     if (fileSize < sizeof(FWHEADER_t))
     {
         return 0;
     }
     //get the header
     U4 generation =
             (pImage->v1.magic == magicG50) ?          50 :  // u-blox5
             (pImage->v1.magic == magicG51) ?          60 :  // u-blox6
             (pImage->v1.magic == magicG70) ?          70 :  // u-blox7
             (pImage->v1.magic == magicG80) ?          80 :  // u-blox8
             0;
     /***************************************************
     * Check if valid image footer is present and parse *
     ***************************************************/
     {
         CH* pMagic;
         BOOL magicFound = FALSE;
         U i;
         for (i = 0; i < 4; i++) // image might be padded with up to 3 0xFF
         {
             pMagic = ((CH*)pImage) + fileSize - 4 - i;
             if (pMagic[0] == 'U' && pMagic[1] == 'B' && pMagic[2] == 'F' && pMagic[3] == 'L')
             {
                 magicFound = TRUE;
                 break;
             }
         }
         if (magicFound)
         {
             U4 version;
             U4 crc;
             U4 footerSize;
             memcpy(&version, pMagic - sizeof(U4), sizeof(version));
             memcpy(&pFwFooter->numberOfImages, pMagic - (3 * sizeof(U4)), sizeof(version));
             footerSize = 5 * sizeof(U4) + sizeof(U4) * pFwFooter->numberOfImages;
             if (version == 0 &&
                 pFwFooter->numberOfImages <= NUMOF(pFwFooter->imagesSize) &&
                 memcpy(&crc, pMagic - (footerSize - sizeof(U4)), sizeof(crc)) != 0 &&
                 lib_crc_crc32(0xF5D4C69, pMagic - (footerSize - 2 * sizeof(U4)), (footerSize - sizeof(U4))) == crc)
             {
                 for (i = 0; i < pFwFooter->numberOfImages; i++)
                 {
                     memcpy(&pFwFooter->imagesSize[i], pMagic - (footerSize - (sizeof(U4) * (i + 2))), sizeof(pFwFooter->imagesSize[i]));
                     MESSAGE(MSG_DBG, "image %u size %u", i, pFwFooter->imagesSize[i]);
                 }
                 memcpy(&pFwFooter->cfgSize, pMagic - 2 * sizeof(U4), sizeof(pFwFooter->cfgSize));
                 MESSAGE(MSG_DBG, "config size %u", pFwFooter->cfgSize);
                 if (generation == 0)
                 {
                     return 91; //Image magic is not present but valid version 0 image footer found so this is U-blox 9 image, cannot check anything more because it is scrumbled
                 }
             }
             else
             {
                 MESSAGE(MSG_ERR, "Invalid footer found");
                 return 0;
             }
         }
     }
     if (!generation)
     {
         // magic word not found
         MESSAGE(MSG_LEV2, "No magic word found");
         return 0;
     }
     if (pImage->v1.pEnd   < pImage->v1.pStart  ||
         pImage->v1.pStart < pImage->v1.pBase   ||
         ((U4)pImage->v1.pEnd   & 0xFF800000) != EXT2_BASE ||
         ((U4)pImage->v1.pBase  & 0xFF800000) != EXT2_BASE ||
         ((U4)pImage->v1.pStart & 0xFF800000) != EXT2_BASE   )
     {
         //pImage->pointer(s) seems to be corrupt
         MESSAGE(MSG_LEV2, "Image addresses invalid");
         return FALSE;
     }
     //magic word found and pointers seem to be OK, check CRC
     U4 crcpos = (pImage->v1.pEnd & ~0x1) - pImage->v1.pBase;
     U4 crcrange = crcpos - 4; // CRC starts behind magic word
     BOOL crcOk = CheckUbxChecksumU4((U4*)((U1*)pImage+4), crcrange);
     // one could return at this stage to detect validity of the image. we
     // additionally grab the version string out of the image
     // the ROM version the firmware was built for is contained in the lower
     // 7 bits of the highest byte of the hardware info word
     if (crcOk)
     {
         memset(verString, 0, sizeof(verString));
         if ((pImage->v1.pVersion & 0xFF800000) == EXT2_BASE)
         {
             CH* FwVerStr = (CH*)((U1*)pImage + (pImage->v1.pVersion - pImage->v1.pBase));
             if (FwVerStr < (CH*)((U1*)pImage + fileSize))
             {
                 strncpy(verString, FwVerStr, sizeof(verString));
             }
         }
         MESSAGE(MSG_LEV2, "Image (file size %u) for u-blox%d accepted", fileSize, generation / 10);
         MESSAGE(MSG_LEV2, "Image Ver '%s'", verString);
         MESSAGE(MSG_DBG, "CRC= 0x%08X 0x%08X",
             *((U4*)((U1*)pImage + crcpos)),
             *((U4*)((U1*)pImage + crcpos + 4)));
     }
     return crcOk ? generation : 0;
 }