ubxfwupdate: mergefis.c File Reference
mergefis.c File Reference
Loads and parses a FIS file and merges the file with the binary.
#include <fcntl.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <ctype.h>
#include <stdlib.h>
#include <assert.h>
#include <stdio.h>
#include <string.h>
#include "mergefis.h"
#include <unistd.h>
Data Structures
struct XML_RULE_t
Rule for an XML element or attribute.
struct XML_ATTR_t
An XML Attribute can be defined by this structure.
struct XML_ELEM_s
Defines an XML element in a XML tree.
Typedefs
typedef struct XML_ELEM_s XML_ELEM_t
Defines an XML element in a XML tree.
Functions
static void freeXmlTree (XML_ELEM_t *data)
Free all contents in all elements of the XML tree to which data belongs.
static XML_ATTR_t * findJedec (XML_ELEM_t *elem, unsigned int const jedec)
Find the JEDEC attribute and compare it to the integer argument.
static char const * getAttrValue (char const *attrName, XML_ELEM_t const *elem)
Find the attribute value with the specified name in the provided element.
static char const * getElemValue (char const *elemName, XML_ELEM_t const *elem)
Find the value of the child-element with the specified name.
static BOOL isElementOrAttr (XML_HNDL_t const *xmlData, char const *tag, char const *attr)
Does the current XML parsing state point to the element or attribute name?
static long long findNextInXml (XML_HNDL_t *xmlData, char const *tag, char const *attr, char **result)
Find the next value for the passed element or attribute name in an XML file.
static void hex_string_to_char_array (const char *hex_string, char *data)
static void GetUbxChecksumU4 (unsigned int *pCrc_a, unsigned int *pCrc_b, const unsigned int *pData, size_t length)
static BOOL CheckUbxChecksumU4 (const unsigned int *pData, size_t length)
unsigned int lib_crc_crc32 (unsigned int seed, const void *pkAdr, unsigned int size)
Calculate 4 byte CRC.
static BOOL UpdateImageCrc (char *pImage, const size_t ImageSize)
Update the CRC of the flash image.
BOOL buildXmlTree (XML_HNDL_t *xmlData, XML_RULE_t const *allowedEntries, unsigned int numAllowedEntries, XML_ELEM_t **root)
Parse the provided XML file and extract a tree according to the rules.
static XML_ELEM_t * findDevice (XML_HNDL_t *xmlData, XML_RULE_t const *allowedEntries, size_t numEntries, const unsigned int jedec)
Find the device with the JEDEC given.
static XML_ELEM_t * findCmdSet (XML_HNDL_t *xmlData, XML_RULE_t const *allowedEntries, size_t numEntries, char const *cmdsetName)
Find the device with the JEDEC given.
static BOOL stringToU4 (char *string, U4 *res)
static void edit_table2 (char *fis, XML_ELEM_t const *container)
Edit the leading table of the FIS version 2.
unsigned int mergefis_get_sector_count (char const *fis)
Return the sector count in the FIS.
unsigned int mergefis_get_sector_size (char const *fis)
Return the sector size in the FIS.
static MERGEFIS_RETVAL_t mergefis_load2 (char **fis, size_t *fisSize, XML_HNDL_t *xmlData, const unsigned int jedec, char const *revisionString)
MERGEFIS_RETVAL_t mergefis_load (char **fis, size_t *fisSize, const char *fisFile, const unsigned int jedec)
Get the image of the FIS.
MERGEFIS_RETVAL_t mergefis_merge (char *pData, unsigned int ImageSize, char const *fis)
Merge the flash image with the corresponding FIS data.
Variables
const unsigned int lib_crc_kCrc32table [256]
Detailed Description
Loads and parses a FIS file and merges the file with the binary.
Definition in file mergefis.c.
Typedef Documentation
typedef struct XML_ELEM_s XML_ELEM_t
Defines an XML element in a XML tree.
Function Documentation
BOOL buildXmlTree (XML_HNDL_t * xmlData, XML_RULE_t const * allowedEntries, unsigned int numAllowedEntries, XML_ELEM_t ** root)
Parse the provided XML file and extract a tree according to the rules.
The provided XML file will be parsed according to the rules of the array of allowed entries. On success the generated tree should contain all children, attributes and values in the specified section.
Parameters
xmlData : The current state of the XML parsing at which parsing continues within this file
allowedEntries : The structure that defines what elements and attributes are allowed where and which elements are potential root elements for the generated tree
numAllowedEntries : Number of entries in allowedEntries
root : The passed pointer will on success point to the highest element of the XML tree. This has to be freed by the calling function with freeXmlTree on success.
Returns
TRUE on success, FALSE otherwise
Definition at line 571 of file mergefis.c.
References XML_ELEM_s::attr, XML_ELEM_s::children, XML_RULE_t::contentType, FALSE, XML_HNDL_t::fd, freeXmlTree(), XML_ATTR_t::name, XML_ELEM_s::name, XML_ELEM_s::numAttr, XML_ELEM_s::numChildren, XML_ELEM_s::parent, XML_HNDL_t::state, TRUE, XML_ATTR_t::value, and XML_ELEM_s::value.
Referenced by findCmdSet(), and findDevice().
 {
     if(!xmlData || !allowedEntries || !numAllowedEntries || !root)
         return FALSE;
     // Make sure there is exactly one root element.
     unsigned int countRoot = 0;
     unsigned int i;
     for(i = 0; i < numAllowedEntries; ++i)
     {
         if( allowedEntries[i].belongsTo[0] == '\0'
          && allowedEntries[i].contentType == YXML_CONTENT )
             ++countRoot;
     }
     // At least one root element must exist
     if(countRoot == 0)
         return FALSE;
     XML_ELEM_t *curr=malloc(sizeof(*curr));
     if(!curr)
         return FALSE;
     XML_ELEM_t *dataRoot=curr;
     memset(curr, 0, sizeof(*curr));
     BOOL rootFound=FALSE;
     // Read and parse the remaining parts of the XML
     // to make sure it is not malformed
     yxml_ret_t prevState = YXML_OK;
     BOOL contentLeadingWs = FALSE;
     do
     {
         assert(curr && dataRoot);
         // Every read error is handled as unexpected EOF
         char byte;
         int rd=read(xmlData->fd, &byte, sizeof(byte));
         if( rd == sizeof(byte))
         {
             yxml_ret_t ret = yxml_parse(&xmlData->state, byte);
             // Has an error occurred?
             if(ret < YXML_OK)
             {
                 freeXmlTree(dataRoot);
                 return FALSE;
             }
             // Find root element if not done so yet
             if(!rootFound)
             {
                 // Is this a possible root beginning?
                 if(ret == YXML_ELEMSTART)
                 {
                     assert(dataRoot==curr);
                     // Check that this element is to be allowed a root element
                     for(i = 0; i < numAllowedEntries && !rootFound; ++i)
                     {
                         if( allowedEntries[i].belongsTo[0] == '\0'
                          && allowedEntries[i].contentType == YXML_CONTENT )
{
                             if(!strcmp(allowedEntries[i].name, xmlData->state.elem))
                                 rootFound=TRUE;
                         }
                     }
                     // Copy element name
                     if(rootFound)
                     {
                         dataRoot->name=strdup(xmlData->state.elem);
                         if(!dataRoot->name)
{
                             freeXmlTree(dataRoot);
                             return FALSE;
                         }
                     }
                 }
             }
             else // root already found, process children and siblings
             {
                 switch(ret)
                 {
                     case YXML_ELEMSTART:
                     {
                         // XML Tag: root, child or 'sibling'?
                         // Check if child is allowed to be child of this parent
                         BOOL valid=FALSE;
                         for(i = 0; i < numAllowedEntries; ++i)
{
                             // Is this new element found in the list?
                             if( !strcmp(allowedEntries[i].name, xmlData->state.elem)
                              && allowedEntries[i].contentType == YXML_CONTENT )
{
                                 // If yes, the parent also has to be an allowed one
                                 if(strstr(allowedEntries[i].belongsTo, curr->name))
{
                                     valid=TRUE;
                                 }
                             }
                         }
                         if(!valid)
{
                             freeXmlTree(dataRoot);
                             return FALSE;
                         }
                         // create child
                         XML_ELEM_t *tmpChildren = realloc(curr->children, (1+curr->numChildren)*sizeof(*tmpChildren));
                         if(tmpChildren)
{
                             curr->children = tmpChildren;
                             ++curr->numChildren;
                         }
                         else
{
                             freeXmlTree(dataRoot);
                             return FALSE;
                         }
                         // switch to child
                         XML_ELEM_t * parent = curr;
                         curr = &curr->children[curr->numChildren-1];
                         memset(curr, 0, sizeof(*curr));
                         // fill child data
                         curr->parent=parent;
                         // Copy element name
                         curr->name=strdup(xmlData->state.elem);
                         if(!curr->name)
{
                             freeXmlTree(dataRoot);
                             return FALSE;
                         }
                         break;
                     }
                     case YXML_ATTRSTART:
                     {
                         assert(!strcmp(xmlData->state.elem, curr->name));
                         // Is this attribute allowed here?
                         BOOL valid=FALSE;
                         for(i = 0; i < numAllowedEntries; ++i)
{
                             // Is this new element found in the list?
                             if( !strcmp(allowedEntries[i].name, xmlData->state.attr)
                              && allowedEntries[i].contentType == YXML_ATTRVAL )
{
                                 // If yes, the parent also has to be an allowed one
                                 if(strstr(allowedEntries[i].belongsTo, curr->name))
                                     valid=TRUE;
                             }
                         }
                         if(!valid)
{
                             freeXmlTree(dataRoot);
                             return FALSE;
                         }
                         // Create the attribute
                         XML_ATTR_t *tmpAttr = realloc(curr->attr, (1+curr->numAttr)*sizeof(*tmpAttr));
                         if(tmpAttr)
{
                             curr->attr = tmpAttr;
                             ++curr->numAttr;
                         }
                         else
{
                             freeXmlTree(dataRoot);
                             return FALSE;
                         }
                         memset(&curr->attr[curr->numAttr-1], 0, sizeof(*curr->attr));
                         // Copy element name
                         curr->attr[curr->numAttr-1].name=strdup(xmlData->state.attr);
                         if(!curr->attr[curr->numAttr-1].name)
{
                             freeXmlTree(dataRoot);
                             return FALSE;
                         }
                         break;
                     }
                     case YXML_ATTRVAL:
                     {
                         assert(curr->attr && curr->numAttr);
                         char * attrVal = curr->attr[curr->numAttr-1].value;
                         size_t attrValLen = 1 + (attrVal ? strlen(attrVal) : 0);
                         char * tmpAttrVal = realloc(attrVal, attrValLen+strlen(xmlData->state.data));
                         if(tmpAttrVal)
{
                             curr->attr[curr->numAttr-1].value = attrVal = tmpAttrVal;
                         }
                         else
{
                             freeXmlTree(dataRoot);
                             return FALSE;
                         }
                         memcpy( attrVal + attrValLen - 1          // Overwrite the previous '\0'
                               , xmlData->state.data
                               , strlen(xmlData->state.data) +1 ); // Copy the '\0' as well
                         break;
                     }
                     case YXML_CONTENT:
                     {
                         // Is this the first whitespace content byte after another state?
                         if(prevState != YXML_CONTENT && isspace(xmlData->state.data[0]))
                             contentLeadingWs = TRUE;
                         else if(!isspace(xmlData->state.data[0]))
                             contentLeadingWs = FALSE;
                         // Only process content after the first non-whitespace character is found
                         if(!contentLeadingWs)
{
                             // Is element allowed to have content?
                             BOOL valid = FALSE;
                             for(i = 0; i < numAllowedEntries; ++i)
{
                                 // Is this new element found in the list?
                                 if( allowedEntries[i].name[0] == '\0'
                                  && allowedEntries[i].contentType == YXML_CONTENT)
{
                                     // If yes, the parent also has to be an allowed one
                                     if(strstr(allowedEntries[i].belongsTo, curr->name))
{
                                         valid=TRUE;
                                     }
                                 }
                             }
                             if(!valid)
{
                                 freeXmlTree(dataRoot);
                                 return FALSE;
                             }
                             size_t valueLen = 1 + (curr->value ? strlen(curr->value) : 0);
                             char * tmpContentVal = realloc(curr->value, valueLen+strlen(xmlData->state.data));
                             if(tmpContentVal)
{
                                 curr->value = tmpContentVal;
                             }
                             else
{
                                 freeXmlTree(dataRoot);
                                 return FALSE;
                             }
                             memcpy(curr->value + valueLen - 1, xmlData->state.data, strlen(xmlData->state.data)+1); // Copy the '\0' as well
                         }
                         break;
                     }
                     case YXML_ELEMEND:
                     {
                         // Ends the loop if root is curr->parent
                         curr=curr->parent;
                         break;
                     }
                     case YXML_ATTREND:
                     case YXML_OK:
                     default:
                     {
                         // Do nothing
                         break;
                     }
                 }
                 // Preserve the previous return value. YXML_OK information
                 // is not very helpful, so ignore it
                 if(ret != YXML_OK)
                 {
                     prevState = ret;
                 }
             }
         }
         else if (rd == 0)
         {
             // File ended, but the caller has to find that out again
             freeXmlTree(dataRoot);
             return FALSE;
         }
     } while(curr);
     *root = dataRoot;
     return TRUE;
 }
static BOOL CheckUbxChecksumU4 (const unsigned int * pData, size_t length) static
Definition at line 507 of file mergefis.c.
References GetUbxChecksumU4().
Referenced by UpdateImageCrc().
 {
     unsigned int crc_a = 0;
     unsigned int crc_b = 0;
     GetUbxChecksumU4(&crc_a, &crc_b, pData, length);
     pData += (length/4);
     return (crc_a == *pData && crc_b == *(pData+1));
 }
static void edit_table2 (char * fis, XML_ELEM_t const * container) static
Edit the leading table of the FIS version 2.
Parameters
fis Pointer to the FIS image
container The device itself or the containing category
Definition at line 1005 of file mergefis.c.
References CAPABILITY_POSITION, CFG_POSITION, XML_ELEM_s::children, DEEP_SLEEP_OPCODE_POSITION, DEEP_SLEEP_WAKEUP_OPCODE_POSITION, DEEP_SLEEP_WAKEUP_TIMEOUT_POSITION, DRV_SQI_CAP_DEEP_SLEEP, DRV_SQI_CAP_FAST_PROGRAM, DRV_SQI_CAP_MAX_SPEED, DRV_SQI_CAP_WRITE_SUSPEND, getAttrValue(), getElemValue(), HSP_POSITION, MAX_SPEED_POSITION, MIN_ERASE_SUSPEND_POSITION, XML_ELEM_s::name, NULL, NUM_BYTES_WRITE_POSITION, XML_ELEM_s::numChildren, SECTOR_COUNT_POSITION, SECTOR_SIZE_POSITION, stringToU4(), and SUPPLY_TYPE_POSITION.
Referenced by mergefis_load2().
 {
     assert(fis && container);
     char const *supply = getAttrValue("supply", container);
     char *secSize = (char*)getElemValue("sectorSize", container);
     char *secCount = (char*)getElemValue("sectorCount", container);
     XML_ELEM_t *cap=NULL;
     unsigned int i;
     for(i = 0; i < container->numChildren; ++i)
     {
         if(!strcmp(container->children[i].name, "cap"))
         {
             cap = &container->children[i];
         }
     }
     char *hsp = (char*)getElemValue("hsp", container);
     char *cfg = (char*)getElemValue("cfg", container);
     char *minEraseSuspend = (char*)getElemValue("minEraseSuspend", container);
     char *numBytesWrite = (char*)getElemValue("numBytesWrite", container);
     char *deepSleepOpcode = (char*)getElemValue("deepSleepOpcode", container);
     char *deepSleepWakeupOpcode = (char*)getElemValue("deepSleepWakeupOpcode", container);
     char *deepSleepWakeupTimeout = (char*)getElemValue("deepSleepWakeupTimeout", container);
     char *maxSpeed= (char*)getElemValue("maxSpeed", container);
     if (supply != NULL)
     {
         char s = (strncmp(supply, "1.8V", 4) == 0) ? 1 : 0;
         fis[SUPPLY_TYPE_POSITION] = (fis[SUPPLY_TYPE_POSITION] & 0xFE) | (s & 0x1);
     }
     if (secSize != NULL)
     {
         U4 sSize = 0;
         stringToU4(secSize, &sSize);
         fis[SECTOR_SIZE_POSITION + 0] = (char) ((sSize >>  0) & 0xFF);
         fis[SECTOR_SIZE_POSITION + 1] = (char) ((sSize >>  8) & 0xFF);
         fis[SECTOR_SIZE_POSITION + 2] = (char) ((sSize >> 16) & 0xFF);
         fis[SECTOR_SIZE_POSITION + 3] = (char) ((sSize >> 24) & 0xFF);
     }
     if (secCount != NULL)
     {
         U4 sCount = 0;
         stringToU4(secCount, &sCount);
         fis[SECTOR_COUNT_POSITION + 0] = (char) ((sCount >>  0) & 0xFF);
         fis[SECTOR_COUNT_POSITION + 1] = (char) ((sCount >>  8) & 0xFF);
         fis[SECTOR_COUNT_POSITION + 2] = (char) ((sCount >> 16) & 0xFF);
         fis[SECTOR_COUNT_POSITION + 3] = (char) ((sCount >> 24) & 0xFF);
     }
     if (cap != NULL)
     {
         const char *writeSuspend = getAttrValue("writeSuspend", cap);
         const char *fastProgram = getAttrValue("fastProgram", cap);
         const char *deepSleep = getAttrValue("deepSleep", cap);
         const char *capMaxSpeed = getAttrValue("speed", cap);
         unsigned char fisValue = fis[CAPABILITY_POSITION];
         if (writeSuspend != NULL)
         {
             unsigned char wS = (atoi(writeSuspend) == 1) ? DRV_SQI_CAP_WRITE_SUSPEND : 0;
             fisValue = (fisValue & ~DRV_SQI_CAP_WRITE_SUSPEND) | wS;
         }
         if (fastProgram != NULL)
         {
             unsigned char fP = (atoi(fastProgram) == 1) ? DRV_SQI_CAP_FAST_PROGRAM : 0;
             fisValue = (fisValue & ~DRV_SQI_CAP_FAST_PROGRAM) | fP;
         }
         if (deepSleep != NULL)
         {
             unsigned char dS = (atoi(deepSleep) == 1) ? DRV_SQI_CAP_DEEP_SLEEP : 0;
             fisValue = (fisValue & ~DRV_SQI_CAP_DEEP_SLEEP) | dS;
         }
         if (capMaxSpeed != NULL)
         {
             unsigned char dS = (atoi(capMaxSpeed) == 1) ? DRV_SQI_CAP_MAX_SPEED : 0;
             fisValue = (fisValue & ~DRV_SQI_CAP_MAX_SPEED) | dS;
         }
         fis[CAPABILITY_POSITION] = fisValue;
     }
     if (hsp != NULL)
     {
         U4 HSP = 0;
         stringToU4(hsp, &HSP);
         fis[HSP_POSITION + 0] = (char) ((HSP >>  0) & 0xFF);
         fis[HSP_POSITION + 1] = (char) ((HSP >>  8) & 0xFF);
         fis[HSP_POSITION + 2] = (char) ((HSP >> 16) & 0xFF);
         fis[HSP_POSITION + 3] = (char) ((HSP >> 24) & 0xFF);
     }
     if (cfg != NULL)
     {
         U4 CFG = 0;
         stringToU4(cfg, &CFG);
         fis[CFG_POSITION + 0] = (char) ((CFG >>  0) & 0xFF);
         fis[CFG_POSITION + 1] = (char) ((CFG >>  8) & 0xFF);
         fis[CFG_POSITION + 2] = (char) ((CFG >> 16) & 0xFF);
         fis[CFG_POSITION + 3] = (char) ((CFG >> 24) & 0xFF);
     }
     if (minEraseSuspend != NULL)
     {
         U4 mES = 0;
         stringToU4(minEraseSuspend, &mES);
         fis[MIN_ERASE_SUSPEND_POSITION + 0] = (char) ((mES >>  0) & 0xFF);
         fis[MIN_ERASE_SUSPEND_POSITION + 1] = (char) ((mES >>  8) & 0xFF);
         fis[MIN_ERASE_SUSPEND_POSITION + 2] = (char) ((mES >> 16) & 0xFF);
         fis[MIN_ERASE_SUSPEND_POSITION + 3] = (char) ((mES >> 24) & 0xFF);
     }
     if (numBytesWrite != NULL)
     {
         U4 nBW = 0;
         stringToU4(numBytesWrite, &nBW);
         fis[NUM_BYTES_WRITE_POSITION + 0] = (char) ((nBW >>  0) & 0xFF);
         fis[NUM_BYTES_WRITE_POSITION + 1] = (char) ((nBW >>  8) & 0xFF);
         fis[NUM_BYTES_WRITE_POSITION + 2] = (char) ((nBW >> 16) & 0xFF);
         fis[NUM_BYTES_WRITE_POSITION + 3] = (char) ((nBW >> 24) & 0xFF);
     }
     if (deepSleepOpcode != NULL)
     {
         U4 deepSleepOp = 0;
         stringToU4(deepSleepOpcode, &deepSleepOp);
         fis[DEEP_SLEEP_OPCODE_POSITION] = (char) (deepSleepOp & 0xFF);
     }
     if (deepSleepWakeupOpcode != NULL)
     {
         U4 deepSleepWakeOp = 0;
         stringToU4(deepSleepWakeupOpcode, &deepSleepWakeOp);
         fis[DEEP_SLEEP_WAKEUP_OPCODE_POSITION] = (char) (deepSleepWakeOp & 0xFF);
     }
     if (deepSleepWakeupTimeout != NULL)
     {
         U4 deepSleepWakeTime = 0;
         stringToU4(deepSleepWakeupTimeout, &deepSleepWakeTime);
         fis[DEEP_SLEEP_WAKEUP_TIMEOUT_POSITION] = (char) (deepSleepWakeTime & 0xFF);
     }
     if (maxSpeed != NULL)
     {
         U4 maxSpeedInt = 0;
         stringToU4(maxSpeed, &maxSpeedInt);
         fis[MAX_SPEED_POSITION] = (char) (maxSpeedInt & 0xFF);
     }
 }
static XML_ELEM_t* findCmdSet (XML_HNDL_t * xmlData, XML_RULE_t const * allowedEntries, size_t numEntries, char const * cmdsetName) static
Find the device with the JEDEC given.
Parameters
xmlData XML data access descriptor
allowedEntries Allowed XML setup
numEntries Number of elements in allowedEntries
cmdsetName Find the command set with the right name attribute
Returns
The node of the device or NULL if not found
Definition at line 916 of file mergefis.c.
References XML_ELEM_s::attr, buildXmlTree(), freeXmlTree(), XML_ATTR_t::name, NULL, XML_ELEM_s::numAttr, and XML_ATTR_t::value.
Referenced by mergefis_load2().
 {
     if(!xmlData || !allowedEntries || !numEntries || !cmdsetName)
         return NULL;
     // Read categories until correct JEDEC attribute found or
     // no more categories available
     XML_ELEM_t *cmdsettree=NULL;
     XML_ELEM_t *result=NULL;
     do
     {
         if(!buildXmlTree(xmlData, allowedEntries, numEntries, &cmdsettree))
             break;
         assert(cmdsettree);
         // Iterate through all attributes and look for the name category
         unsigned int i;
         for(i = 0; i < cmdsettree->numAttr; ++i)
         {
             if( !strcmp(cmdsettree->attr[i].name, "name")
              && !strcmp(cmdsettree->attr[i].value, cmdsetName) )
                     result=cmdsettree;
         }
         if(!result)
             freeXmlTree(cmdsettree);
     } while(!result);
     return result;
 }
static XML_ELEM_t* findDevice (XML_HNDL_t * xmlData, XML_RULE_t const * allowedEntries, size_t numEntries, const unsigned int jedec) static
Find the device with the JEDEC given.
Parameters
xmlData XML data access descriptor
allowedEntries Allowed XML setup
numEntries Number of elements in allowedEntries
jedec JEDEC of the device
Returns
The node of the device or NULL if not found
Definition at line 863 of file mergefis.c.
References buildXmlTree(), XML_ELEM_s::children, findJedec(), freeXmlTree(), XML_ELEM_s::name, NULL, and XML_ELEM_s::numChildren.
Referenced by mergefis_load2().
 {
     if(!xmlData || !allowedEntries || !numEntries)
         return NULL;
     // Read categories until correct JEDEC attribute found or
     // no more categories available
     XML_ELEM_t *rootElem=NULL;
     XML_ELEM_t *dev=NULL;
     do
     {
         if(!buildXmlTree(xmlData, allowedEntries, numEntries, &rootElem))
             break;
         assert(rootElem);
         // Check if the root element is already the child
         if(!strcmp(rootElem->name, "device"))
         {
             if(findJedec(rootElem, jedec))
                 dev = rootElem;
         }
         else
         {
             // Iterate through all 'device'-children in rootElem
             unsigned int i;
             for(i = 0; i < rootElem->numChildren && !dev; ++i)
             {
                 if(!strcmp(rootElem->children[i].name, "device"))
                 {
                     if(findJedec(&rootElem->children[i], jedec))
                         dev = &rootElem->children[i];
                 }
             }
         }
         if(!dev)
             freeXmlTree(rootElem);
     } while(!dev);
     return dev;
 }
static XML_ATTR_t* findJedec (XML_ELEM_t * elem, unsigned int const jedec) static
Find the JEDEC attribute and compare it to the integer argument.
Find the JEDEC attribute in the passed element and compare it to the integer JEDEC passed as argument.
Parameters
elem : Element in which the JEDEC attribute is searched for.
jedec : The JEDEC value to which the attribute must be compared if found.
Returns
On success a pointer to the JEDEC attribute, otherwise NULL.
Definition at line 237 of file mergefis.c.
References XML_ELEM_s::attr, XML_ATTR_t::name, NULL, XML_ELEM_s::numAttr, and XML_ATTR_t::value.
Referenced by findDevice().
 {
     // Check if this device child has the right JEDEC attribute
     unsigned int j;
     XML_ATTR_t * result = NULL;
     for(j = 0; j < elem->numAttr; ++j)
     {
         if(!strcmp(elem->attr[j].name, "jedec"))
         {
             // Replace starting 'x' if existing
             if(elem->attr[j].value[0] == 'x')
             {
                 elem->attr[j].value[0] = ' ';
             }
             // Correct JEDEC?
             if((unsigned int) strtol(elem->attr[j].value, NULL, 16)==jedec)
                 result = &elem->attr[j];
         }
     }
     return result;
 }
static long long findNextInXml (XML_HNDL_t * xmlData, char const * tag, char const * attr, char ** result) static
Find the next value for the passed element or attribute name in an XML file.
If only a tag is passed to this function it will search for the content of the next tag element of this name. If additionally an attribute is specified, the value of the the next attribute of that name in the next tag of the specified name is returned.
Parameters
xmlData : Reference to the XML tree (Must not be NULL)
tag : The tag name (Must no be NULL)
attr : Attribute name (May be NULL)
result : Found string. (Must not be NULL)
Returns
-1 on failure. 0 if not found. Otherwise the length of the zero terminated string in result
Definition at line 366 of file mergefis.c.
References FALSE, XML_HNDL_t::fd, isElementOrAttr(), NULL, XML_HNDL_t::state, and TRUE.
Referenced by mergefis_load().
 {
     if(!xmlData || !tag || !result)
         return -1;
     const size_t blockSize=128;
     char *data=NULL;
     size_t allocMemory=0;
     BOOL endLoop=FALSE;
     // Read and parse the remaining parts of the XML
     // to make sure it is not malformed
     do
     {
         // Every read error is handled as unexpected EOF
         char byte;
         int rd=read(xmlData->fd, &byte, sizeof(byte));
         if( rd == sizeof(byte))
         {
             yxml_ret_t ret=yxml_parse(&xmlData->state, byte);
             // Has an error occurred?
             if(ret<YXML_OK)
             {
                 free(data);
                 return -1;
             }
             // Check if memory has been allocated. If yes
             // we are already in the right location to copy
             // the content data to this destination. Otherwise
             // check if the current byte has changed our location
             // to the intended value-field
             if(!data)
             {
                 // Is this the content of the element
                 // or attribute searched for?
                 if( ((!attr && ret==YXML_CONTENT) || ( attr && ret==YXML_ATTRVAL))
                  && isElementOrAttr(xmlData, tag, attr) )
                 {
                     // Element with right tag name has begun
                     data = malloc(blockSize);
                     if(!data)
                         return -1;
                     assert(blockSize >= sizeof(xmlData->state.data));
                     // Copy the initial content bytes to the destination buffer
                     // and take care of the terminating '\0' as well this time,
                     // so we can ignore it afterwards
                     allocMemory = blockSize;
                     memcpy(data, xmlData->state.data, strlen(xmlData->state.data) + 1);
                 }
             }
             else // Copy data
             {
                 if(ret!=YXML_CONTENT && ret!=YXML_ATTRVAL)
                 {
                     // The data copying must be stopped
                     endLoop=TRUE;
                 }
                 else
                 {
                     size_t numNewBytes = strlen(xmlData->state.data)+1;
                     size_t numBytesStored=strlen(data)+1;
                     // Is it required to enlarge the destination buffer?
                     // Don't count both '\0', one will be deleted (that's the -1)
                     if(numNewBytes + numBytesStored - 1 > allocMemory)
                     {
                         do
{
                             allocMemory += blockSize;
                         } while(numNewBytes + numBytesStored - 1 > allocMemory);
                         // Get the new memory size which is enough
                         // to store all the data
                         char * tmpData = realloc(data, allocMemory);
                         if(!tmpData)
{
                             free(data);
                             return -1;
                         }
                         data=tmpData;
                     }
                     // Copy the data by overwriting the previous \0
                     // termination (that's the -1) of the string and
                     // appending
                     // he remaining data
                     assert(numBytesStored);
                     memcpy(data + numBytesStored - 1, xmlData->state.data, numNewBytes);
                 }
             }
         }
         else if (rd == 0)
         {
             // File ended, but the caller has to find that out again
             endLoop=TRUE;
         }
     } while(!endLoop);
     // Return result if something found
     *result = data;
     size_t resultLen = data ? strlen(data) : 0;
     return resultLen;
 }
static void freeXmlTree (XML_ELEM_t * data) static
Free all contents in all elements of the XML tree to which data belongs.
All contents and elements contained in the tree to which data belongs will be freed.
Parameters
data : An element of the tree which has to be freed
Definition at line 178 of file mergefis.c.
References XML_ELEM_s::attr, XML_ELEM_s::children, XML_ATTR_t::name, XML_ELEM_s::name, XML_ELEM_s::numAttr, XML_ELEM_s::numChildren, XML_ELEM_s::parent, XML_ATTR_t::value, and XML_ELEM_s::value.
Referenced by buildXmlTree(), findCmdSet(), findDevice(), and mergefis_load2().
 {
     if(data)
     {
         const size_t MAX_DEPTH = 1024;
         // Two options
         // - If this is the first call to this function, find the root,
         //   initiate the freeing of all children by calling this function
         //   again after having set the children parent to their own pointer
         //   value and clean up the own stuff as well as the data pointer as
         //   well!
         // - If this is a consecutive call to this function,
         //   (data == data->parent), initiate the deletion of all children
         //   clean up the own stuff and return
         // Find the top element if parent is self,
         // a parent exists and has reset the parent to
         // that value
         size_t i;
         for(i=0; i < MAX_DEPTH && data->parent && data != data->parent; ++i)
         {
             data = data->parent;
         }
         // Only the tree is small enough to be cleaned up
         // by this function
         if(i < MAX_DEPTH)
         {
             for(i = 0; i < data->numChildren; ++i)
             {
                 data->children[i].parent = &data->children[i];
                 freeXmlTree(&data->children[i]);
             }
             for(i = 0; i < data->numAttr; ++i)
             {
                 free(data->attr[i].name);
                 free(data->attr[i].value);
             }
             free(data->attr);
             free(data->children);
             free(data->name);
             free(data->value);
             // This is the root element, clean up the own pointer
             if(!data->parent)
                 free(data);
         }
     }
 }
static char const* getAttrValue (char const * attrName, XML_ELEM_t const * elem) static
Find the attribute value with the specified name in the provided element.
Get the attribute value with the specified name in the provided element
Parameters
attrName : Name of the attribute of which the value should be returned
elem : Element in which the attribute should should be located
Returns
On success the pointer to the string value of the specified attribute. Otherwise NULL
Definition at line 269 of file mergefis.c.
References XML_ELEM_s::attr, XML_ATTR_t::name, NULL, XML_ELEM_s::numAttr, and XML_ATTR_t::value.
Referenced by edit_table2().
 {
     if(!attrName || !elem)
         return NULL;
     char * result=NULL;
     unsigned int i;
     for(i = 0; i < elem->numAttr; ++i)
     {
         if(!strcmp(elem->attr[i].name, attrName))
             result = elem->attr[i].value;
     }
     return result;
 }
static char const* getElemValue (char const * elemName, XML_ELEM_t const * elem) static
Find the value of the child-element with the specified name.
Get the value of the child-element with the specified name in the provided element
Parameters
elemName : Name of the element of which the value should be returned
elem : Element in which the element of the given name should exist as child
Returns
On success the pointer to the string value of the specified element. Otherwise NULL
Definition at line 296 of file mergefis.c.
References XML_ELEM_s::children, XML_ELEM_s::name, NULL, XML_ELEM_s::numChildren, and XML_ELEM_s::value.
Referenced by edit_table2().
 {
     if(!elemName || !elem)
         return NULL;
     char * result=NULL;
     unsigned int i;
     for(i = 0; i < elem->numChildren; ++i)
     {
         if(!strcmp(elem->children[i].name, elemName))
             result = elem->children[i].value;
     }
     return result;
 }
static void GetUbxChecksumU4 (unsigned int * pCrc_a, unsigned int * pCrc_b, const unsigned int * pData, size_t length) static
Definition at line 490 of file mergefis.c.
Referenced by CheckUbxChecksumU4(), and UpdateImageCrc().
 {
     unsigned int crc_a = 0;
     unsigned int crc_b = 0;
     length /= 4;
     while (length--)
     {
         crc_a += *pData++;
         crc_b += crc_a;
     }
     *pCrc_a = crc_a;
     *pCrc_b = crc_b;
 }
static void hex_string_to_char_array (const char * hex_string, char * data) static
Definition at line 473 of file mergefis.c.
Referenced by mergefis_load2(), and stringToU4().
 {
     assert(hex_string && data);
     unsigned int i;
     for(i = 0; i < strlen(hex_string); i+=2)
     {
         char buf[3];
         buf[0] = hex_string[i];
         buf[1] = hex_string[i+1];
         buf[2] = '\0';
         unsigned int c = 0;
         sscanf(buf, "%x", &c);
         data[i>>1] = (char)c;
     }
 }
static BOOL isElementOrAttr (XML_HNDL_t const * xmlData, char const * tag, char const * attr) static
Does the current XML parsing state point to the element or attribute name?
Check if the current state of parsing is occupied with the element and/or attribute provided. If only the element is specified it is enough if the parser is processing an element of the specified name at the moment to make the test succeed. If additionally an attribute is specified (non-NULL), the parser must currently also be processing an attribute of the specified name within the specified element.
Parameters
xmlData : Current XML parsing state
tag : Name of the tag for which it should be checked if the the parser is currently processing it.
attr : Name of the attribute for which it should be checked if the the parser is currently processing it. (May be NULL)
Returns
TRUE on success, FALSE otherwise
Definition at line 329 of file mergefis.c.
References FALSE, XML_HNDL_t::state, and TRUE.
Referenced by findNextInXml().
 {
     if(!tag || !xmlData)
         return FALSE;
     BOOL result=FALSE;
     if(xmlData->state.elem && !strcmp(tag, xmlData->state.elem))
     {
         if(attr)
         {
             if(xmlData->state.attr && !strcmp(attr, xmlData->state.attr))
                 result=TRUE;
         }
         else if(!xmlData->state.attr) // attr must not be set
         {
             // Only Element requested and
             result=TRUE;
         }
     }
     return result;
 }
unsigned int lib_crc_crc32 (unsigned int seed, const void * pkAdr, unsigned int size)
Calculate 4 byte CRC.
Returns 4 byte CRC of provided data
Parameters
seed Seed of CRC
pkAdr pointer to the data
size size of the data
Returns
The calculated 32bit CRC
Definition at line 517 of file mergefis.c.
References lib_crc_kCrc32table.
Referenced by mergefis_load2(), and ValidateImage().
 {
     const unsigned char* pk = (const unsigned char*)pkAdr;
     unsigned int crc = seed;
     while (size --)
     {
         crc = (((crc >> 8) & 0x00FFFFFF) ^ lib_crc_kCrc32table[(crc ^ *pk++) & 0x000000FF]);
     }
     return crc;
 }
unsigned int mergefis_get_sector_count (char const * fis)
Return the sector count in the FIS.
Return the sector count in the FIS
Parameters
fis The FIS definition from which to extract the sector count
Returns
The calculated sector count
Definition at line 1160 of file mergefis.c.
References MAJOR_REV_POSITION, MINOR_REV_POSITION, SECTOR_COUNT_POSITION, and SECTOR_COUNT_POSITION_VER3.
Referenced by UpdateFirmware().
 {
     if(fis[MAJOR_REV_POSITION] == 0x3 && fis[MINOR_REV_POSITION] == 0x0)
     {
         return (((unsigned int)((unsigned char)fis[SECTOR_COUNT_POSITION_VER3 + 0]) & 0xFF) <<   0) |
                (((unsigned int)((unsigned char)fis[SECTOR_COUNT_POSITION_VER3 + 1]) & 0xFF) <<   8);
     }
     else
     {
         return (((unsigned int)((unsigned char)fis[SECTOR_COUNT_POSITION + 0]) & 0xFF) <<   0) |
                (((unsigned int)((unsigned char)fis[SECTOR_COUNT_POSITION + 1]) & 0xFF) <<   8) |
                (((unsigned int)((unsigned char)fis[SECTOR_COUNT_POSITION + 2]) & 0xFF) <<  16) |
                (((unsigned int)((unsigned char)fis[SECTOR_COUNT_POSITION + 3]) & 0xFF) <<  24);
     }
 }
unsigned int mergefis_get_sector_size (char const * fis)
Return the sector size in the FIS.
Return the sector size in the FIS
Parameters
fis The FIS definition from which to extract the sector size
Returns
The calculated sector size
Definition at line 1176 of file mergefis.c.
References MAJOR_REV_POSITION, MINOR_REV_POSITION, SECTOR_SIZE_POSITION, and SECTOR_SIZE_VER3.
Referenced by UpdateFirmware().
 {
     if(fis[MAJOR_REV_POSITION] == 0x3 && fis[MINOR_REV_POSITION] == 0x0)
     {
         return SECTOR_SIZE_VER3;
     }
     else
     {
         return (((unsigned int)(unsigned char)(fis[SECTOR_SIZE_POSITION + 0]) & 0xFF) <<   0) |
                (((unsigned int)(unsigned char)(fis[SECTOR_SIZE_POSITION + 1]) & 0xFF) <<   8) |
                (((unsigned int)(unsigned char)(fis[SECTOR_SIZE_POSITION + 2]) & 0xFF) <<  16) |
                (((unsigned int)(unsigned char)(fis[SECTOR_SIZE_POSITION + 3]) & 0xFF) <<  24);
     }
 }
MERGEFIS_RETVAL_t mergefis_load (char ** fis, size_t * fisSize, const char * fisFile, const unsigned int jedec)
Get the image of the FIS.
Parameters
fis Pointer to pointer of the FIS image
fisSize Size of the allocated structure
fisFile Path to the FIS file
jedec JEDEC of the device the FIS image should be retrieved for
Returns
success / error code
Definition at line 1407 of file mergefis.c.
References XML_HNDL_t::buf, FALSE, XML_HNDL_t::fd, findNextInXml(), MERGEFIS_FILE_NOT_FOUND, MERGEFIS_INCORRECT_XML, mergefis_load2(), MERGEFIS_OK, MERGEFIS_UNKNOWN, MERGEFIS_VERSION_ERROR, NULL, XML_HNDL_t::state, and TRUE.
Referenced by UpdateFirmware().
 {
     if(!fis || !fisSize || !fisFile)
         return MERGEFIS_UNKNOWN;
     //open the FIS XML file
     XML_HNDL_t xmlData;
     xmlData.fd = open(fisFile, O_RDONLY);
     if ( xmlData.fd < 0 )
         return MERGEFIS_FILE_NOT_FOUND;
     MERGEFIS_RETVAL_t result=MERGEFIS_UNKNOWN;
     // Find optional revision information
     yxml_init(&xmlData.state, xmlData.buf, sizeof(xmlData.buf));
     char *revision=NULL;
     findNextInXml(&xmlData, "flash", "revision", &revision); // optional
     // reinitialize yxml, to make sure we start from the beginning again
     if(lseek(xmlData.fd, 0, SEEK_SET)==1)
         return MERGEFIS_UNKNOWN;
     yxml_init(&xmlData.state, xmlData.buf, sizeof(xmlData.buf));
     char *version=NULL;
     long long versionStrLen=findNextInXml(&xmlData, "flash", "fisVersion", &version);
     // At least one character must have been found (excluding terminating character)
     if(versionStrLen < 1)
     {
         result=MERGEFIS_INCORRECT_XML;
     }
     else
     {
         if ( strncmp(version, "2", 1) == 0 )
             result=mergefis_load2(fis, fisSize, &xmlData , jedec, revision);
         else
             result=MERGEFIS_VERSION_ERROR;
         // Only if the previous operations were all successful
         // it is required to parse until the end of the file
         // to make sure the XML is not malformed
         if(result==MERGEFIS_OK)
         {
             // Read and parse the remaining parts of the XML
             // to make sure it is not malformed
             yxml_ret_t ret=YXML_EEOF;
             BOOL exitLoop = FALSE;
             do
             {
                 // Every read error is handled as unexpected EOF
                 ret=YXML_EEOF;
                 char byte;
                 int rd = read(xmlData.fd, &byte, sizeof(byte));
                 if( rd == sizeof(byte))
                 {
                     ret=yxml_parse(&xmlData.state, byte);
                     // Error case?
                     if(ret < YXML_OK)
                         exitLoop = TRUE;
                 }
                 else if (rd == 0)
                 {
                     ret=yxml_eof(&xmlData.state);
                     exitLoop = TRUE;
                 }
             } while(!exitLoop);
             // yxml_eof must now have ended with YXML_OK,
             // otherwise the file is malformed
             if(ret != YXML_OK)
                 result = MERGEFIS_INCORRECT_XML;
         }
     }
     free(revision);
     free(version);
     close(xmlData.fd);
     return result;
 }
static MERGEFIS_RETVAL_t mergefis_load2 (char ** fis, size_t * fisSize, XML_HNDL_t * xmlData, const unsigned int jedec, char const * revisionString) static
Definition at line 1192 of file mergefis.c.
References XML_ELEM_s::attr, XML_ELEM_s::children, DRV_SQI_FIS_CHECKSUM_SEED, edit_table2(), findCmdSet(), findDevice(), freeXmlTree(), hex_string_to_char_array(), lib_crc_crc32(), MERGEFIS_CODE_CORRUPTED, MERGEFIS_INCORRECT_XML, MERGEFIS_JEDEC_NOT_SUPPORTED, MERGEFIS_OK, MERGEFIS_UNKNOWN, XML_ATTR_t::name, XML_ELEM_s::name, NULL, XML_ELEM_s::numAttr, XML_ELEM_s::numChildren, XML_ELEM_s::parent, REVISION_POSITION, stringToU4(), XML_ATTR_t::value, and XML_ELEM_s::value.
Referenced by mergefis_load().
 {
     if(!fis || !fisSize || !xmlData)
         return MERGEFIS_UNKNOWN;
     //search for our device in the flash section of the XML file
     const XML_RULE_t devEntries[] = {
         // Attributes start
         { "jedec",                  YXML_ATTRVAL, "device"                   },
         { "cmd",                    YXML_ATTRVAL, "category|device"          },
         { "supply",                 YXML_ATTRVAL, "category|device"          },
         { "writeSuspend",           YXML_ATTRVAL, "cap"                      },
         { "fastProgram",            YXML_ATTRVAL, "cap"                      },
         { "deepSleep",              YXML_ATTRVAL, "cap"                      },
         { "speed",                  YXML_ATTRVAL, "cap"                      },
         // Element start
         { "category",               YXML_CONTENT, ""                         },
         { "device",                 YXML_CONTENT, ""                         },
         { "device",                 YXML_CONTENT, "category"                 },
         { "numBytesWrite",          YXML_CONTENT, "category|device"          },
         { "minEraseSuspend",        YXML_CONTENT, "category|device"          },
         { "hsp",                    YXML_CONTENT, "category|device"          },
         { "cfg",                    YXML_CONTENT, "category|device"          },
         { "cap",                    YXML_CONTENT, "category|device"          },
         { "sectorSize",             YXML_CONTENT, "category|device"          },
         { "sectorCount",            YXML_CONTENT, "category|device"          },
         { "deepSleepOpcode",        YXML_CONTENT, "category|device"          },
         { "deepSleepWakeupOpcode",  YXML_CONTENT, "category|device"          },
         { "deepSleepWakeupTimeout", YXML_CONTENT, "category|device"          },
         { "maxSpeed",               YXML_CONTENT, "category|device"          },
         { "",                       YXML_CONTENT, "sectorSize"
                                                   "|sectorCount"
                                                   "|hsp"
                                                   "|cfg"
                                                   "|minEraseSuspend"
                                                   "|numBytesWrite"
                                                   "|deepSleepOpcode"
                                                   "|deepSleepWakeupTimeout"
                                                   "|maxSpeed"                }
     };
     XML_ELEM_t *device = findDevice( xmlData
                                    , devEntries
                                    , sizeof(devEntries)/sizeof(devEntries[0])
                                    , jedec );
     //still not found
     if (device == NULL)
         return MERGEFIS_JEDEC_NOT_SUPPORTED;
     char *deviceCmd = NULL;
     // Search for command attribute
     unsigned int i;
     for(i = 0;  i < device->numAttr && !deviceCmd; ++i)
     {
         if(!strcmp(device->attr[i].name, "cmd"))
             deviceCmd = strdup(device->attr[i].value);
     }
     // If no device cmd has been found and a parent exists
     // search in the corresponding parent
     if(device->parent && !deviceCmd)
     {
         for(i = 0;  i < device->parent->numAttr; ++i)
         {
             if(!strcmp(device->parent->attr[i].name, "cmd"))
                 deviceCmd = strdup(device->parent->attr[i].value);
         }
     }
     // If no cmd value has been found, this is a problem.
     if (deviceCmd == NULL)
     {
         freeXmlTree(device);
         return MERGEFIS_INCORRECT_XML;
     }
     const XML_RULE_t cmdsetEntries[]= {
         // Attributes start
         { "name",                            YXML_ATTRVAL, "cmdset"                },
         // Element start
         { "cmdset",                          YXML_CONTENT, ""                      },
         { "length",                          YXML_CONTENT, "cmdset"                },
         { "checksum",                        YXML_CONTENT, "cmdset"                },
         { "code",                            YXML_CONTENT, "cmdset"                },
         { "",                                YXML_CONTENT, "length|code|checksum"  }
     };
     // Find the corresponding command set
     XML_ELEM_t *cmdset = findCmdSet( xmlData
                                    , cmdsetEntries
                                    , sizeof(cmdsetEntries)/sizeof(cmdsetEntries[0])
                                    , deviceCmd );
     if(cmdset == NULL)
     {
         freeXmlTree(device);
         free(deviceCmd);
         return MERGEFIS_INCORRECT_XML;
     }
     // Get the required code, lenStr and checksum
     char * lenStr=NULL;
     char * checksum=NULL;
     char * code=NULL;
     for(i = 0; i < cmdset->numChildren; ++i)
     {
         if(!strcmp(cmdset->children[i].name, "length"))
         {
             lenStr = cmdset->children[i].value;
         }
         else if(!strcmp(cmdset->children[i].name, "checksum"))
         {
             checksum = cmdset->children[i].value;
         }
         else if(!strcmp(cmdset->children[i].name, "code"))
         {
             code = cmdset->children[i].value;
         }
     }
     if(!lenStr || !code)
     {
         freeXmlTree(device);
         freeXmlTree(cmdset);
         free(deviceCmd);
         return MERGEFIS_INCORRECT_XML;
     }
     U4 len = 0;
     stringToU4(lenStr, &len);
     //create buffer to convert the code into
     char *data = malloc(len);
     size_t dataSize = len;
     if(!data)
     {
         freeXmlTree(device);
         freeXmlTree(cmdset);
         free(deviceCmd);
         return MERGEFIS_UNKNOWN;
     }
     //fill it with 0xFF
     memset(data, 0xff, dataSize);
     //copy the code into the buffer
     hex_string_to_char_array(code, data);
     //copy the CRC into the buffer
     hex_string_to_char_array(checksum, &data[dataSize-4]);
     //check CRC
     unsigned int crc = lib_crc_crc32(DRV_SQI_FIS_CHECKSUM_SEED, (const void *)data, dataSize-4);
     unsigned int crcWritten = (((unsigned int)((unsigned char)data[dataSize-4]) & 0xFF) <<  0) |
                               (((unsigned int)((unsigned char)data[dataSize-3]) & 0xFF) <<  8) |
                               (((unsigned int)((unsigned char)data[dataSize-2]) & 0xFF) << 16) |
                               (((unsigned int)((unsigned char)data[dataSize-1]) & 0xFF) << 24);
     if( crc != crcWritten )
     {
         free(data);
         freeXmlTree(device->parent);
         freeXmlTree(cmdset);
         free(deviceCmd);
         return MERGEFIS_CODE_CORRUPTED;
     }
     //apply first the settings of the category, if existing
     if(device->parent)
     {
         edit_table2(data, device->parent);
     }
     //and now the settings of the device
     edit_table2(data, device);
     // Update JEDEC
     data[4] = (char) ((jedec >> 16) & 0xFF);
     data[5] = (char) ((jedec >>  8) & 0xFF);
     data[6] = (char) ((jedec >>  0) & 0xFF);
     // Update revision string
     if(revisionString != NULL)
     {
         unsigned int revision = 0xFFFFFFFF;
         sscanf(revisionString, "$Rev: %u $", &revision);
         data[REVISION_POSITION + 0] = (char) ((revision >>  0) & 0xFF);
         data[REVISION_POSITION + 1] = (char) ((revision >>  8) & 0xFF);
         data[REVISION_POSITION + 2] = (char) ((revision >> 16) & 0xFF);
         data[REVISION_POSITION + 3] = (char) ((revision >> 24) & 0xFF);
     }
     //update the CRC of the FIS
     crc = lib_crc_crc32(DRV_SQI_FIS_CHECKSUM_SEED, (const void *)data, dataSize-4);
     data[dataSize - 4] = (char) ((crc >>  0) & 0xFF);
     data[dataSize - 3] = (char) ((crc >>  8) & 0xFF);
     data[dataSize - 2] = (char) ((crc >> 16) & 0xFF);
     data[dataSize - 1] = (char) ((crc >> 24) & 0xFF);
     *fis = data;
     *fisSize = dataSize;
     // Clean up
     freeXmlTree(device);
     freeXmlTree(cmdset);
     free(deviceCmd);
     return MERGEFIS_OK;
 }
MERGEFIS_RETVAL_t mergefis_merge (char * pData, unsigned int ImageSize, char const * fis)
Merge the flash image with the corresponding FIS data.
Parameters
pData Pointer to the flash image
ImageSize Size of the flash image
fis Pointer to the FIS image
Returns
success / error code
Definition at line 1486 of file mergefis.c.
References MERGEFIS_CRC_FAILURE, MERGEFIS_OK, and UpdateImageCrc().
Referenced by UpdateFirmware().
 {
     //merge the images
     memcpy(&pData[0x40], fis, 0x1000 - 0x40);
     //Update CRC of the whole image
     return (UpdateImageCrc(pData, ImageSize))?MERGEFIS_OK:MERGEFIS_CRC_FAILURE;
 }
static BOOL stringToU4 (char * string, U4 * res) static
Definition at line 949 of file mergefis.c.
References FALSE, hex_string_to_char_array(), TRUE, and XML_ELEM_s::value.
Referenced by edit_table2(), and mergefis_load2().
 {
     if(!string || !res)
         return FALSE;
     U4 tmp = 0;
     if ( (string[0] == '0' && string[1] == 'x') || string[0] == 'x' )
     {
         int offset = 2;
         //we have a hex string that is in MSB order!
         //0x1000 -> 4096
         if(string[0] == 'x')
         {
             offset = 1;
         }
         size_t len = strlen(&string[offset]);
         if (len%2 != 0)
         {
             string[--offset] = '0';
             len++;
         }
         len /= 2;
         if (len > 4)
         {
             len = 4;
         }
         char *value = malloc(sizeof(*value)*len);
         if(!value)
             return FALSE;
         memset(value, 0x0, len);
         hex_string_to_char_array(&string[offset], value);
         size_t  i;
         for(i = 0; i < len; i++)
         {
             tmp = tmp << 8;
             tmp |= 0xFF & value[i];
         }
         free(value);
     }
     else
     {
         //this is a normal decimal string
         int atoiRes = atoi(string);
         if(atoiRes < 0)
             return FALSE;
         tmp = (U4) atoiRes;
     }
     *res=tmp;
     return TRUE;
 }
static BOOL UpdateImageCrc (char * pImage, const size_t ImageSize) static
Update the CRC of the flash image.
Parameters
pImage Pointer to the image
ImageSize Size of the image
Returns
TRUE Updating of the CRC succeeded
Definition at line 536 of file mergefis.c.
References CheckUbxChecksumU4(), and GetUbxChecksumU4().
Referenced by mergefis_merge().
 {
     unsigned int crc_a;
     unsigned int crc_b;
     unsigned int* pCrcrangestart = (unsigned int*)((char*)pImage+4);
     unsigned int crcpos = ImageSize - 8; // CRC is two words long
     unsigned int crcrangesize = crcpos - 4; // CRC starts behind magic word
     GetUbxChecksumU4(&crc_a, &crc_b, pCrcrangestart, crcrangesize);
     //MESSAGE(MSG_LEV2, "Updating CRC of buffered image to 0x%08X 0x%08X", crc_a, crc_b);
     unsigned int* pCrc = (unsigned int*)((char*)(pImage) + crcpos);
     *pCrc = crc_a;
     *(pCrc+1) = crc_b;
     return CheckUbxChecksumU4(pCrcrangestart, crcrangesize);
 }
Variable Documentation
const unsigned int lib_crc_kCrc32table[256]
This table provides a lookup table for the 32 Bit CRC algorithm
See also
lib_crc_crc32
Definition at line 104 of file mergefis.c.
Referenced by lib_crc_crc32().