ubxfwupdate: platform.h File Reference
platform.h File Reference
Defines and Prototypes for platform specifics.
#include "types.h"
Data Structures
struct SER_HANDLE_s
serial port information handling type
Macros
#define ENABLE_AARDVARK_SUPPORT
AARDVARK USB->I2C/SPI converter.
#define ENABLE_NET_SUPPORT
Network sockets.
#define BaudrateDefaultI2C 100000
The default I2C Baudrate.
Typedefs
typedef enum SER_TYPE_e SER_TYPE_t
communication interface type
typedef struct SER_HANDLE_s SER_HANDLE_t
serial port information handling type
typedef SER_HANDLE_t * SER_HANDLE_pt
pointer to SER_HANDLE_t type
Enumerations
enum SER_TYPE_e {
COM, STDINOUT, U2C, I2C,
SPI, SPU, NET
}
communication interface type
enum MSG_LEVEL {
MSG_ERR, MSG_WARN, MSG_LEV0, MSG_LEV1,
MSG_LEV2, MSG_DBG, MSG_DBGV
}
Message Level.
Functions
void TIME_SLEEP (U4 time)
Sleep.
U4 TIME_GET (void)
Get Timer.
SER_HANDLE_pt SER_OPEN (const CH *name)
Open Serial Port.
U4 SER_WRITE_SPI (SER_HANDLE_pt h, const void *p, U4 size)
Write to SPI Port.
U4 SER_WRITE (SER_HANDLE_pt h, const void *p, U4 size)
Write to Serial Port.
U4 SER_READ (SER_HANDLE_pt h, void *p, U4 size)
Read from Serial Port.
void SER_CLEAR (SER_HANDLE_pt h)
Flush Serial Port.
void SER_CLOSE (SER_HANDLE_pt h)
Close Serial Port.
BOOL SER_BAUDRATE (SER_HANDLE_pt h, U4 br)
changes the baudrate of the communication device
U4 SER_PENDING (SER_HANDLE_pt h)
get number of pending bytes at I2C interface
void SER_FLUSH (SER_HANDLE_pt h)
Flush Serial Port.
BOOL SER_REENUM (SER_HANDLE_pt h, BOOL IsUsb)
Re-Enumerate Port.
void MESSAGE (MSG_LEVEL level, const CH *format,...)
Print status message.
void MESSAGE_PLAIN (const CH *format,...)
void CONSOLE_INIT (void)
initialize console
void CONSOLE_DONE (void)
cleanup console
void CONSOLE_SAVE_POS (U4 offs)
save current cursor position
void CONSOLE_RESTORE_POS (void)
restore previously saved cursor position
Variables
int verbose
verbosity
Detailed Description
Defines and Prototypes for platform specifics.
Definition in file platform.h.
Macro Definition Documentation
#define BaudrateDefaultI2C 100000
The default I2C Baudrate.
Definition at line 84 of file platform.h.
Referenced by SetArgument().
#define ENABLE_AARDVARK_SUPPORT
AARDVARK USB->I2C/SPI converter.
Definition at line 36 of file platform.h.
#define ENABLE_NET_SUPPORT
Network sockets.
Definition at line 48 of file platform.h.
Typedef Documentation
typedef SER_HANDLE_t* SER_HANDLE_pt
pointer to SER_HANDLE_t type
Definition at line 78 of file platform.h.
typedef struct SER_HANDLE_s SER_HANDLE_t
serial port information handling type
typedef enum SER_TYPE_e SER_TYPE_t
communication interface type
Enumeration Type Documentation
enum MSG_LEVEL
Message Level.
Enumerator
MSG_ERR
Error message.
MSG_WARN
Warning message.
MSG_LEV0
Verbosity Level 0 message.
MSG_LEV1
Verbosity Level 1 message.
MSG_LEV2
Verbosity Level 2 message.
MSG_DBG
Debug message.
MSG_DBGV
Very verbose debug message.
Definition at line 216 of file platform.h.
 {
     MSG_ERR,   //!< Error message
     MSG_WARN,  //!< Warning message
 #ifdef _TEST
     MSG_TEST,  //!< Test message
 #endif // _TEST
     MSG_LEV0,  //!< Verbosity Level 0 message
     MSG_LEV1,  //!< Verbosity Level 1 message
     MSG_LEV2,  //!< Verbosity Level 2 message
     MSG_DBG,   //!< Debug message
     MSG_DBGV   //!< Very verbose debug message
 } MSG_LEVEL;
enum SER_TYPE_e
communication interface type
Enumerator
COM
Serial COM-Port.
STDINOUT
stdin/stdout port
U2C
I2C Port over Diolan.
I2C
I2C Port over Aardvark.
SPI
SPI Port over Aardvark.
SPU
SPI Port over Diolan.
NET
Serial port over Ethernet.
Definition at line 57 of file platform.h.
 {
     COM,                          //!< Serial COM-Port
     STDINOUT,                     //!< stdin/stdout port
     U2C,                          //!< I2C Port over Diolan
     I2C,                          //!< I2C Port over Aardvark
     SPI,                          //!< SPI Port over Aardvark
     SPU,                          //!< SPI Port over Diolan
     NET                           //!< Serial port over Ethernet
 } SER_TYPE_t;
Function Documentation
void CONSOLE_DONE (void)
cleanup console
Definition at line 2103 of file platform.c.
References sCONSOLE_tioSave.
Referenced by main().
 {
 #ifndef WIN32
     if (isatty(fileno(stderr)))
     {
         fflush(stdin);
         tcsetattr(fileno(stdin), TCSANOW, &sCONSOLE_tioSave);
     }
 #endif // WIN32
 }
void CONSOLE_INIT (void)
initialize console
Definition at line 2081 of file platform.c.
References sCONSOLE_tioSave, and TRUE.
Referenced by main().
 {
 #ifdef WIN32
     SetConsoleCtrlHandler(CONSOLE_CTRLHANDLER, TRUE);
 #else
     // make stdin unbuffered, disable echo, etc.
     struct termios tio;
     if (isatty(fileno(stderr)))
     {
         tcgetattr(fileno(stderr), &tio);
         memcpy(&sCONSOLE_tioSave, &tio, sizeof(struct termios));
         tio.c_lflag     &= (~ICANON);
         tio.c_lflag     &= (~ECHO);
         tio.c_cc[VTIME]  = 1;
         tio.c_cc[VMIN]   = 0;
         tcsetattr(fileno(stderr), TCSANOW, &tio);
     }
 #endif // WIN32
     sCONSOLE_SAVEPOS_y = 1;
     sCONSOLE_SAVEPOS_x = 1;
 }
void CONSOLE_RESTORE_POS (void)
restore previously saved cursor position
Definition at line 2162 of file platform.c.
Referenced by updDumpAck().
 {
 #ifdef WIN32
     COORD coord;
     coord.X = (SHORT)sCONSOLE_SAVEPOS_x;
     coord.Y = (SHORT)sCONSOLE_SAVEPOS_y;
     SetConsoleCursorPosition(GetStdHandle(STD_ERROR_HANDLE),coord);
 #else
     if (isatty(fileno(stderr)))
     {
         fprintf(stderr, "\e[%u;%uH", sCONSOLE_SAVEPOS_y, sCONSOLE_SAVEPOS_x);
         fflush(stderr);
     }
 #endif // WIN32
 }
void CONSOLE_SAVE_POS (U4 offs)
save current cursor position
Definition at line 2115 of file platform.c.
References MESSAGE_PLAIN().
Referenced by updInit().
 {
     // scroll terminal
     U4 i;
     for(i =  0;  i < offs; i++)
     {
         MESSAGE_PLAIN("\n");
     }
     fflush(stderr);
 #ifdef WIN32
     CONSOLE_SCREEN_BUFFER_INFO info;
     GetConsoleScreenBufferInfo(GetStdHandle(STD_ERROR_HANDLE),&info);
     sCONSOLE_SAVEPOS_x = info.dwCursorPosition.X;
     sCONSOLE_SAVEPOS_y = info.dwCursorPosition.Y;
 #else // WIN32
     if (isatty(fileno(stderr)))
     {
         char buf[16];
         char *pBuf = buf;
         // request cursor position
         fprintf(stderr, "\e[6n");
         fflush(stderr);
         // read cursor position (expecting: "^[[xxx;yyyR")
         int timeout = 10;
         while ( (pBuf - buf < 12) && (*pBuf != 'R') && timeout--)
         {
             if (read(0, pBuf, 1))
             {
                 pBuf++;
             }
         }
         int x = 0, y = 0;
         if (sscanf(buf+2, "%i;%iR", &y, &x) == 2)
         {
             sCONSOLE_SAVEPOS_y = y;
             sCONSOLE_SAVEPOS_x = x;
         }
     }
 #endif // WIN32
     sCONSOLE_SAVEPOS_y -= offs;
     if (sCONSOLE_SAVEPOS_y < 1)
     {
         sCONSOLE_SAVEPOS_y = 1;
     }
 }
void MESSAGE (MSG_LEVEL level, const CH * format, ...)
Print status message.
Print status message to standard output. The message is printed if level is lower or equal to MSG_LEV2 or verbose is TRUE and level is lower or equal to MSG_DBG; it is discarded otherwise.
Messages assigned a message level MSG_ERR or MSG_WARN are prefixed with "ERROR:" or "WARNING:", respectively. Messages of type MSG_DBG are prefixed with a hyphen. See details for MSG_LEVEL for a definition of valid message levels.
Parameters
level IN: message level
format IN: format string
... IN: optional arguments
Definition at line 1992 of file platform.c.
References MSG_DBG, MSG_ERR, MSG_LEV0, MSG_LEV1, MSG_LEV2, MSG_WARN, NULL, TIME_GET(), and verbose.
Referenced by COM_BAUDRATE(), COM_CLEAR(), COM_FLUSH(), COM_OPEN(), COM_READ(), COM_WRITE(), doReset(), DumpFlashInfo(), extractHwGeneration(), GetFlashOrganisation(), getNoFisMergingData(), GetPacketNrForSector(), GetSectorNrForSize(), I2C_BAUDRATE(), I2C_OPEN(), I2C_PENDING(), I2C_READ(), I2C_WRITE(), main(), NET_BAUDRATE(), NET_OPEN(), NET_READ(), NET_WRITE(), OpenAndBufferFile(), rcvConnect(), rcvDoAutobaud(), rcvPollMessage(), rcvReenumerate(), rcvSendTrainingSequence(), rcvSetBaud(), SER_REENUM(), SPI_BAUDRATE(), SPI_OPEN(), SPI_READ(), SPI_WRITE(), UbxSearchMsg(), UpdateFirmware(), updateImageToRam(), updDumpAck(), updEraseSector(), updInit(), updProcessMessages(), updSendWrite(), updUpdate(), updWritePacket(), ValidateImage(), and verifyImage().
 {
     static U4 tick = 0;
     // Must be done like this because the result of TIME_GET()
     // can not be the initializer of a compile-time constant
     if(tick==0)
         tick=TIME_GET();
 #ifdef WIN32
     HANDLE hErrOut = GetStdHandle(STD_ERROR_HANDLE);
     U4 dw;
 #endif // WIN32
     // maximum line length
     CH mem[1024];
     U4 cnt;
     if (level > ((verbose) ? MSG_DBG : MSG_LEV2))
     {
         return;
     }
     cnt = 0;
     cnt += sprintf(&mem[cnt], "%5.1f ", 0.001 * (double) (TIME_GET() - tick));
     switch (level)
     {
 #ifdef _TEST
         case MSG_TEST:  break;
 #endif // _TEST
         case MSG_ERR:    cnt+=sprintf(&mem[cnt], "ERROR: ");
 #ifdef WIN32
             SetConsoleTextAttribute(hErrOut,FOREGROUND_RED|FOREGROUND_INTENSITY);
 #endif // WIN32
             break;
         case MSG_WARN:    cnt+=sprintf(&mem[cnt], "WARNING: ");
 #ifdef WIN32
             SetConsoleTextAttribute(hErrOut,FOREGROUND_RED|FOREGROUND_GREEN|FOREGROUND_INTENSITY);
 #endif // WIN32
             break;
         case MSG_LEV0:    break;
         case MSG_LEV1:    cnt+=sprintf(&mem[cnt], " ");        break;
         case MSG_LEV2:
 #ifdef WIN32
             SetConsoleTextAttribute(hErrOut,FOREGROUND_BLUE|FOREGROUND_INTENSITY);
 #endif // WIN32
             break;
         default:
         case MSG_DBG:    cnt+=sprintf(&mem[cnt], "  - ");    break;
     }
     va_list args;
     va_start(args, format);
     cnt += vsprintf(&mem[cnt], format, args);
     va_end(args);
     cnt += sprintf(&mem[cnt], "\r\n");
 #ifdef WIN32
     WriteFile(hErrOut, mem, cnt, (LPDWORD)&dw, NULL);
     SetConsoleTextAttribute(hErrOut,FOREGROUND_RED|FOREGROUND_GREEN|FOREGROUND_BLUE);
 #else
     fprintf(stderr, "%s", mem);
 #endif // WIN32
 }
void MESSAGE_PLAIN (const CH * format, ...)
Definition at line 1971 of file platform.c.
References NULL.
Referenced by CONSOLE_SAVE_POS(), main(), ParseArguments(), SER_REENUM(), updDumpAck(), updEraseSector(), updProcessMessages(), updWritePacket(), and Usage().
 {
     CH mem[1024];
     U4 cnt = 0;
     va_list args;
     va_start(args, format);
     cnt += vsprintf(&mem[cnt], format, args);
     va_end(args);
 #ifdef WIN32
     HANDLE hErrOut = GetStdHandle(STD_ERROR_HANDLE);
     U4 dw;
     WriteFile(hErrOut, mem, cnt, (LPDWORD)&dw, NULL);
 #else
     fprintf(stderr, "%s", mem);
     fflush(stderr);
 #endif // WIN32
 }
BOOL SER_BAUDRATE (SER_HANDLE_pt h, U4 br)
changes the baudrate of the communication device
Parameters
h Handle to the device
br baudrate to set for the device
Returns
TRUE if the setting succeeded, FALSE else
Definition at line 1835 of file platform.c.
References SER_HANDLE_s::baudrate, COM, COM_BAUDRATE(), FALSE, SER_HANDLE_s::handle, I2C, I2C_BAUDRATE(), NET, NET_BAUDRATE(), SPI, SPI_BAUDRATE(), SPU, STDINOUT, TRUE, SER_HANDLE_s::type, and U2C.
Referenced by rcvSetBaud().
 {
     BOOL brSet = FALSE;
     //MESSAGE(MSG_DBG, "platform: switching baudrate to %d baud", br);
     switch(h->type)
     {
     case COM:
         brSet = COM_BAUDRATE(h->handle,br);
         break;
 #ifdef WIN32
     case STDINOUT:
         STDIN_SETBAUD(br);
         brSet = TRUE; // There is no baudrate here
         break;
 #endif //ifdef WIN32
 #ifdef ENABLE_AARDVARK_SUPPORT
     case I2C:
         brSet = I2C_BAUDRATE(h->handle,br);
         break;
     case SPI:
         brSet = SPI_BAUDRATE(h->handle,br);
         break;
 #endif // ENABLE_AARDVARK_SUPPORT
 #ifdef ENABLE_DIOLAN_SUPPORT
     case SPU:
         brSet = SPU_BAUDRATE(h->handle,br);
         break;
     case U2C:
         brSet = U2C_BAUDRATE(h->handle,br);
         break;
 #endif // ENABLE_DIOLAN_SUPPORT
 #ifdef ENABLE_NET_SUPPORT
     case NET:
         brSet = NET_BAUDRATE(h,br);
         break;
 #endif // ENABLE_NET_SUPPORT
     default:
         break;
     }
     if (brSet)
     {
         h->baudrate = br;
     }
     return brSet;
 }
void SER_CLEAR (SER_HANDLE_pt h)
Flush Serial Port.
Flush pending bytes from serial buffer
Parameters
h IN: handle to open serial port
Definition at line 1823 of file platform.c.
References COM, COM_CLEAR(), SER_HANDLE_s::handle, and SER_HANDLE_s::type.
Referenced by rcvConnect(), rcvDisconnect(), and rcvFlushBuffer().
 {
     switch(h->type)
     {
     case COM:
         COM_CLEAR(h->handle);
         break;
     default:
         break;
     }
 }
void SER_CLOSE (SER_HANDLE_pt h)
Close Serial Port.
Close serial port
Parameters
h IN: handle to open serial port
Definition at line 1899 of file platform.c.
References COM, COM_CLOSE(), SER_HANDLE_s::handle, I2C, I2C_CLOSE(), NET, NET_CLOSE(), SER_HANDLE_s::pData, SPI, SPI_CLOSE(), SPU, STDINOUT, SER_HANDLE_s::type, and U2C.
Referenced by rcvDisconnect().
 {
     if (!h)
         return;
     switch(h->type)
     {
     case COM:
         COM_CLOSE(h->handle);
         break;
 #ifdef WIN32
     case STDINOUT:
         break;
 #endif //ifdef WIN32
 #ifdef ENABLE_AARDVARK_SUPPORT
     case I2C:
         I2C_CLOSE(h->handle);
         break;
     case SPI:
         SPI_CLOSE(h->handle);
         break;
 #endif // ENABLE_AARDVARK_SUPPORT
 #ifdef ENABLE_DIOLAN_SUPPORT
     case U2C:
         U2C_CLOSE(h->handle);
         break;
     case SPU:
         SPU_CLOSE(h->handle);
         break;
 #endif // ENABLE_DIOLAN_SUPPORT
 #ifdef ENABLE_NET_SUPPORT
     case NET:
         NET_CLOSE(h->handle);
         break;
 #endif // ENABLE_NET_SUPPORT
     default:
         break;
     }
     // free custom data
     if (h->pData)
         free(h->pData);
     // free handle
     free(h);
 }
void SER_FLUSH (SER_HANDLE_pt h)
Flush Serial Port.
Write the buffered data to the port
Parameters
h IN: handle to open serial port
Definition at line 1884 of file platform.c.
References COM, COM_FLUSH(), SER_HANDLE_s::handle, and SER_HANDLE_s::type.
 {
     if (!h)
         return;
     switch (h->type)
     {
     case COM:
         COM_FLUSH(h->handle);
         break;
     default:
         break;
     }
 }
SER_HANDLE_pt SER_OPEN (const CH * name)
Open Serial Port.
Open serial port indicated by name.
Parameters
name IN: name of serial port to open
Returns
handle to opened port on success, NULL on failure
Definition at line 1407 of file platform.c.
References SER_HANDLE_s::baudrate, COM, COM_OPEN(), SER_HANDLE_s::devAddr, SER_HANDLE_s::handle, I2C, I2C_OPEN(), NET, NET_OPEN(), NULL, SER_HANDLE_s::pData, SER_HANDLE_s::pName, SPI, SPI_OPEN(), SPU, STDINOUT, SER_HANDLE_s::type, and U2C.
Referenced by rcvConnect().
 {
     SER_TYPE_t serType = COM;
     HANDLE     handle = (HANDLE)0;
     SER_HANDLE_pt pSerHandle;
     void *pData = NULL;
     int        addr = 0;
 #ifdef ENABLE_DIOLAN_SUPPORT
     if (!handle && (strncmp(name, "U2C",3) == 0 || strncmp(name, "u2c",3) == 0))
     {
         serType = U2C;
         handle  = U2C_OPEN(name,&addr);
     }
     if (!handle && (strncmp(name, "SPU",3) == 0 || strncmp(name, "spu",3) == 0))
     {
         serType = SPU;
         handle  = SPU_OPEN(name,&pData);
     }
 #endif // ENABLE_DIOLAN_SUPPORT
 #ifdef ENABLE_AARDVARK_SUPPORT
     if (!handle && strncmp(name, "I2C", 3) == 0)
     {
         serType = I2C;
         handle = I2C_OPEN(name, &addr);
     }
     if (!handle && (strncmp(name, "SPI", 3) == 0 ||
                     strncmp(name, "spi", 3) == 0))
     {
         serType = SPI;
         handle = SPI_OPEN(name, &pData);
     }
 #endif // ENABLE_AARDVARK_SUPPORT
 #ifdef ENABLE_NET_SUPPORT
     if (!handle && strchr(name, ':'))
     {
         serType = NET;
         handle  = NET_OPEN(name);
     }
     else
 #endif // ENABLE_NET_SUPPORT
     if (!handle)
     {
         serType = COM;
         handle  = COM_OPEN(name);
     }
 #ifdef WIN32
     if (!handle && (strncmp(name, "STDIO", 5) == 0 || strncmp(name, "stdio", 5) == 0))
     {
         serType = STDINOUT;
         handle  = (HANDLE) -1; // Indicates stdin/stdout. Never used -> unique identifier
         // Make sure windows does not replace "\n" to "\r\n"
         if(_setmode(fileno(stdout), O_BINARY) == -1)
         {
             // In case of error abort here
             handle = (HANDLE)0;
         }
     }
 #endif //ifdef WIN32
     if (handle)
     {
         pSerHandle = (SER_HANDLE_pt)malloc(sizeof(SER_HANDLE_t));
         if (pSerHandle)
         {
             pSerHandle->handle   = handle;  // device handle
             pSerHandle->type     = serType; // device type
             pSerHandle->devAddr  = addr;    // device address
             pSerHandle->pData    = pData;   // custom data pointer
             pSerHandle->pName    = name;    // backup name
             pSerHandle->baudrate = 0;       // baudrate not set yet
             return pSerHandle;
         }
     }
     return NULL;
 }
U4 SER_PENDING (SER_HANDLE_pt h)
get number of pending bytes at I2C interface
Parameters
h IN: handle to open port
Returns
number of pending bytes
Definition at line 1944 of file platform.c.
References COM, SER_HANDLE_s::devAddr, SER_HANDLE_s::handle, I2C, I2C_PENDING(), SER_HANDLE_s::type, and U2C.
 {
     if (!h)
         return 0;
     switch (h->type)
     {
 #ifdef ENABLE_AARDVARK_SUPPORT
     case I2C:
         return I2C_PENDING(h->handle, h->devAddr);
 #endif // ENABLE_AARDVARK_SUPPORT
 #ifdef ENABLE_DIOLAN_SUPPORT
     case U2C:
         return U2C_PENDING(h->handle, h->devAddr);
 #endif // ENABLE_DIOLAN_SUPPORT
     case COM:
     default:
         break;
     }
     return 0;
 }
U4 SER_READ (SER_HANDLE_pt h, void * p, U4 size)
Read from Serial Port.
Read data from serial port
Parameters
h IN: handle to open serial port
p OUT: buffer to write data to
size IN: number of bytes to be read
Returns
number of bytes read
Definition at line 1789 of file platform.c.
References COM, COM_READ(), SER_HANDLE_s::devAddr, SER_HANDLE_s::handle, I2C, I2C_READ(), NET, NET_READ(), SER_HANDLE_s::pData, SPI, SPI_READ(), SPU, STDINOUT, SER_HANDLE_s::type, and U2C.
Referenced by rcvReceiveMessage().
 {
     switch(h->type)
     {
     case COM:
         return COM_READ(h->handle,p,size);
 #ifdef WIN32
     case STDINOUT:
         return STDIN_READ(p,size);
 #endif //ifdef WIN32
 #ifdef ENABLE_AARDVARK_SUPPORT
     case I2C:
         return I2C_READ(h->handle,h->devAddr,p,size);
     case SPI:
         return SPI_READ(h->handle,(SPI_READBUFFER_pt)h->pData,p,size);
 #endif // ENABLE_AARDVARK_SUPPORT
 #ifdef ENABLE_DIOLAN_SUPPORT
     case U2C:
         return U2C_READ(h->handle,h->devAddr,p,size);
     case SPU:
         return SPU_READ(h->handle,(SPI_READBUFFER_pt)h->pData,p,size);
 #endif // ENABLE_DIOLAN_SUPPORT
 #ifdef ENABLE_NET_SUPPORT
     case NET:
         return NET_READ(h->handle,p,size);
 #endif // ENABLE_NET_SUPPORT
     default:
         break;
     }
     return 0;
 }
BOOL SER_REENUM (SER_HANDLE_pt h, BOOL IsUsb)
Re-Enumerate Port.
Re-Enumerates Port, if applicable
Parameters
h IN: handle to open serial port
IsUsb IN: set to TRUE if serial port is really a USB connection
Returns
success state
Definition at line 1486 of file platform.c.
References SER_HANDLE_s::baudrate, COM, COM_BAUDRATE(), COM_CLOSE(), COM_OPEN(), FALSE, SER_HANDLE_s::handle, I2C, I2C_BAUDRATE(), MESSAGE(), MESSAGE_PLAIN(), MSG_DBG, NET, NET_BAUDRATE(), SER_HANDLE_s::pName, SPI, SPI_BAUDRATE(), SPU, STDINOUT, TIME_SLEEP(), TRUE, SER_HANDLE_s::type, and U2C.
Referenced by rcvReenumerate().
 {
     MESSAGE(MSG_DBG, "Re-enumerating...");
     switch(h->type)
     {
     case COM:
         {
             U4 retries = 10;
             COM_CLOSE(h->handle);
             do
             {
                 TIME_SLEEP(1000);
                 h->handle = COM_OPEN(h->pName);
                 if (h->handle)
                 {
                     return COM_BAUDRATE(h->handle, h->baudrate);
                 }
             }
             while ((h->handle == (HANDLE)0) && retries--);
         }
         break;
 #ifdef WIN32
     case STDINOUT:
         MESSAGE_PLAIN("<AC>Reenum %i<\\AC>", IsUsb);
         TIME_SLEEP(1000);   // Pause to allow host to perform operation
         return TRUE;
 #endif //ifdef WIN32
 #ifdef ENABLE_AARDVARK_SUPPORT
     case I2C:
         TIME_SLEEP(500);
         return I2C_BAUDRATE(h->handle,h->baudrate);
     case SPI:
         TIME_SLEEP(500);
         return SPI_BAUDRATE(h->handle,h->baudrate);
 #endif // ENABLE_AARDVARK_SUPPORT
 #ifdef ENABLE_DIOLAN_SUPPORT
     case U2C:
         TIME_SLEEP(500);
         return U2C_BAUDRATE(h->handle,h->baudrate);
     case SPU:
         TIME_SLEEP(500);
         return SPU_BAUDRATE(h->handle,h->baudrate);
 #endif // ENABLE_DIOLAN_SUPPORT
 #ifdef ENABLE_NET_SUPPORT
     case NET:
         TIME_SLEEP(500);
         return NET_BAUDRATE(h,h->baudrate);
 #endif // ENABLE_NET_SUPPORT
     default:
         break;
     }
     return FALSE;
 }
U4 SER_WRITE (SER_HANDLE_pt h, const void * p, U4 size)
Write to Serial Port.
Write data to serial port
Parameters
h IN: handle to open serial port
p IN: buffer to data to be written
size IN: number of bytes to be written
Returns
number of bytes written
Definition at line 1754 of file platform.c.
References COM, COM_WRITE(), SER_HANDLE_s::devAddr, SER_HANDLE_s::handle, I2C, I2C_WRITE(), NET, NET_WRITE(), SER_WRITE_SPI(), SPI, SPU, STDINOUT, SER_HANDLE_s::type, and U2C.
Referenced by rcvFlushBuffer(), and rcvRawSend().
 {
     switch(h->type)
     {
     case COM:
         return COM_WRITE(h->handle,p,size);
 #ifdef WIN32
     case STDINOUT:
         return STDOUT_WRITE(p,size);
 #endif //ifdef WIN32
 #ifdef ENABLE_AARDVARK_SUPPORT
     case I2C:
         return I2C_WRITE(h->handle,h->devAddr,p,size);
     case SPI:
         return SER_WRITE_SPI(h, p, size);
 #endif // ENABLE_AARDVARK_SUPPORT
 #ifdef ENABLE_DIOLAN_SUPPORT
     case U2C:
         return U2C_WRITE(h->handle,h->devAddr,p,size);
     case SPU:
         return SER_WRITE_SPI(h, p, size);
 #endif //ENABLE_DIOLAN_SUPPORT
 #ifdef ENABLE_NET_SUPPORT
     case NET:
         return NET_WRITE(h->handle,p,size);
 #endif // ENABLE_NET_SUPPORT
     default:
         break;
     }
     return 0;
 }
U4 SER_WRITE_SPI (SER_HANDLE_pt h, const void * p, U4 size)
Write to SPI Port.
Write data to SPI port. Successive 0xFF will be filtered out.
Parameters
h IN: handle to open serial port
p IN: buffer to data to be written
size IN: number of bytes to be written
Returns
number of bytes written
Definition at line 1542 of file platform.c.
References UBX_HEAD_s::classId, SER_HANDLE_s::handle, UBX_HEAD_s::msgId, NULL, SER_HANDLE_s::pData, SPI, SPI_WRITE(), SPU, SER_HANDLE_s::type, UBX_CLASS_UPD, UBX_UPD_FLWRI, and UbxCreateMessage().
Referenced by SER_WRITE().
 {
     // get the header of the UBX message
     UBX_HEAD_pt pUbxHdr = (UBX_HEAD_pt)p;
     // check for UPD-FLWRI message
     if(pUbxHdr->classId == UBX_CLASS_UPD && pUbxHdr->msgId == UBX_UPD_FLWRI)
     {
         // content of UPD-FLWRI message
         U4 targetAddress = 0;    // address where to write the data to
         U4 writeSize = 0;        // length of the payload to be written
         U4 startOfData = 0;      // where the data section starts
         U4 pos = 0;              // current position inside the complete packet
         U1 *pData = NULL;        // pointer to data section of packet
         U1 totalFF = 8;          // how many 0xFF in success are allowed
         U curSearch = 0;         // how man 0xFF have been already found
         // get the content of the UPD-FLWRI message
         memcpy(&targetAddress, (U4 *)((U1 *)p+sizeof(UBX_HEAD_t)), sizeof(targetAddress));
         memcpy(&writeSize,     (U4 *)((U1 *)p+sizeof(UBX_HEAD_t)+sizeof(targetAddress)), sizeof(writeSize));
         // set the pointer to the data
         pData = (U1 *)p + sizeof(UBX_HEAD_t) + sizeof(targetAddress) + sizeof(writeSize);
         while(pos < writeSize)
         {
             // get the current character
             U1 current = pData[pos];
             // compare to 0xFF
             if(current == 0xFF)
             {
                 // increment the 0xFF counter
                 curSearch++;
             }
             // something else found
             else
             {
                 // check if already more 0xFF have passed than allowed
                 if(curSearch > totalFF)
                 {
                     // check if anything has to be written
                     if(pos-startOfData-curSearch)
                     {
                         // calculate the new write address and the new size of the payload
                         U4 writeAddress = targetAddress+startOfData;
                         U4 newWriteSize    = pos-startOfData-curSearch;
                         CH *pMessage=NULL;
                         CH *pSendData = (CH*)malloc(newWriteSize+8);
                         if(!pSendData)
                             return 0;
                         size_t Size;
                         // get the data
                         memcpy(pSendData+0, &writeAddress, 4);
                         memcpy(pSendData+4, &newWriteSize, 4);
                         memcpy(pSendData+8, pData+startOfData, newWriteSize);
                         // create UBX message
                         UbxCreateMessage(UBX_CLASS_UPD, UBX_UPD_FLWRI, pSendData, newWriteSize+8, &pMessage, &Size);
                         // send the data to the receiver
                         switch(h->type)
{
 #ifdef ENABLE_AARDVARK_SUPPORT
                         case SPI:
                             SPI_WRITE(h->handle,(SPI_READBUFFER_pt)h->pData,pMessage,Size);
                             break;
 #endif // ENABLE_AARDVARK_SUPPORT
 #ifdef ENABLE_DIOLAN_SUPPORT
                         case SPU:
                             SPU_WRITE(h->handle,(SPI_READBUFFER_pt)h->pData,pMessage,Size);
                             break;
 #endif // ENABLE_DIOLAN_SUPPORT
                         default:
                             break;
                         }
                         // cleanup
                         free(pMessage);
                         free(pSendData);
                     }
                     // set the start of the new data to the current position (where data was found)
                     startOfData = pos;
                 }
                 // reset the 0xFF counter
                 curSearch = 0;
             }
             // increment the position pointer
             pos++;
         }
         // check if anything has to be written
         if(pos-startOfData-curSearch)
         {
             // calculate the new write address and the new size of the payload
             U4 writeAddress = targetAddress+startOfData;
             U4 newWriteSize2    = pos-startOfData-curSearch;
             CH *pMessage=NULL;
             CH *pSendData = (CH*) malloc(newWriteSize2+8);
             if(!pSendData)
                 return 0;
             size_t Size;
             // get the data
             memcpy(pSendData+0, &writeAddress, 4);
             memcpy(pSendData+4, &newWriteSize2, 4);
             memcpy(pSendData+8, pData+startOfData, newWriteSize2);
             // create UBX message
             UbxCreateMessage(UBX_CLASS_UPD, UBX_UPD_FLWRI, pSendData, newWriteSize2+8, &pMessage, &Size);
             // send the data to the receiver
             switch(h->type)
             {
 #ifdef ENABLE_AARDVARK_SUPPORT
             case SPI:
                 SPI_WRITE(h->handle,(SPI_READBUFFER_pt)h->pData,pMessage,Size);
                 break;
 #endif // ENABLE_AARDVARK_SUPPORT
 #ifdef ENABLE_DIOLAN_SUPPORT
             case SPU:
                 SPU_WRITE(h->handle,(SPI_READBUFFER_pt)h->pData,pMessage,Size);
                 break;
 #endif // ENABLE_DIOLAN_SUPPORT
             default:
                 break;
             }
             // cleanup
             free(pMessage);
             free(pSendData);
         }
         // no data could be found to be written -> send one single byte
         else
         {
             U4 newSize = 1;       // size is one single byte
             CH *pMessage=NULL;
             CH *pSendData = (CH*) malloc(newSize+8);
             if(!pSendData)
                 return 0;
             U1 newData = 0xFF;    // data is 0xFF
             size_t Size;
             // get the data
             memcpy(pSendData+0, &targetAddress, 4);
             memcpy(pSendData+4, &newSize, 4);
             memcpy(pSendData+8, &newData, newSize);
             // create the message
             UbxCreateMessage(UBX_CLASS_UPD, UBX_UPD_FLWRI, pSendData, newSize+8, &pMessage, &Size);
             // send the data to the receiver
             switch(h->type)
             {
 #ifdef ENABLE_AARDVARK_SUPPORT
             case SPI:
                 SPI_WRITE(h->handle,(SPI_READBUFFER_pt)h->pData,pMessage,Size);
                 break;
 #endif // ENABLE_AARDVARK_SUPPORT
 #ifdef ENABLE_DIOLAN_SUPPORT
             case SPU:
                 SPU_WRITE(h->handle,(SPI_READBUFFER_pt)h->pData,pMessage,Size);
                 break;
 #endif // ENABLE_DIOLAN_SUPPORT
             default:
                 break;
             }
             // cleanup
             free(pMessage);
             free(pSendData);
         }
         // fake the number of written bytes
         // such that the higher levels wont freak out
         return size;
     }
     // no UPD-FLWRI message
     else
     {
         // write data using standard write
         switch(h->type)
         {
 #ifdef ENABLE_AARDVARK_SUPPORT
         case SPI:
             return SPI_WRITE(h->handle,(SPI_READBUFFER_pt)h->pData,p,size);
 #endif // ENABLE_AARDVARK_SUPPORT
 #ifdef ENABLE_DIOLAN_SUPPORT
         case SPU:
             return SPU_WRITE(h->handle,(SPI_READBUFFER_pt)h->pData,p,size);
 #endif // ENABLE_DIOLAN_SUPPORT
         default:
             return 0;
         }
     }
 }
U4 TIME_GET (void)
Get Timer.
Number of milliseconds that have elapsed since a OS/platform specific event. Don't use absolute values, but differences between subsequent calls to TIME_GET() to get a predictable behavior.
Returns
number of milliseconds
Definition at line 129 of file platform.c.
References NULL.
Referenced by MESSAGE(), rcvAckMessage(), rcvReceiveMessage(), UpdateFirmware(), updateImageToRam(), updDumpAck(), updEraseSector(), and updWritePacket().
 {
 #ifdef WIN32
     return GetTickCount();
 #else
     struct timeval tv;
     return (gettimeofday(&tv,NULL)==0) ?
         (U4)(tv.tv_sec*1000 + tv.tv_usec/1000) : 0;
 #endif
 }
void TIME_SLEEP (U4 time)
Sleep.
Sleep for time milliseconds
Parameters
time IN: number of milliseconds to sleep
Definition at line 120 of file platform.c.
Referenced by I2C_PENDING(), I2C_READ(), rcvReceiveMessage(), rcvSendTrainingSequence(), rcvSetBaud(), SER_REENUM(), UpdateFirmware(), and updProcessMessages().
 {
 #ifdef WIN32
     Sleep(ms);
 #else
     usleep(1000*ms);
 #endif
 }
Variable Documentation
int verbose
verbosity
Definition at line 111 of file platform.c.
Referenced by CanSendParentCommands(), MESSAGE(), UpdateFirmware(), updDumpAck(), and updInit().