ubxfwupdate: platform.c File Reference
platform.c File Reference
Platform abstraction layer.
#include <stdio.h>
#include <string.h>
#include "platform.h"
#include "spi_read_buffer.h"
#include "ubxmsg.h"
#include "aardvark.h"
#include <unistd.h>
#include <fcntl.h>
#include <stdlib.h>
#include <stdarg.h>
#include <termio.h>
#include <sys/time.h>
#include <sys/fcntl.h>
#include <sys/file.h>
#include <sys/stat.h>
#include <sys/socket.h>
#include <sys/select.h>
#include <sys/types.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
#include <arpa/inet.h>
#include <netdb.h>
#include <signal.h>
#include <errno.h>
Macros
#define SOCKADDR struct sockaddr
cross-platform compatibility
#define SOCKADDR_IN struct sockaddr_in
cross-platform compatibility
#define HOSTENT struct hostent
cross-platform compatibility
#define FDSET fd_set
cross-platform compatibility
#define TIMEVAL struct timeval
cross-platform compatibility
#define closesocket(s) close(s)
cross-platform compatibility
#define LAST_ERR() errno
cross-platform compatibility
#define LAST_NET_ERR() errno
cross-platform compatibility
#define DEFAULT_I2C_ADDR 0x42
default slave address
#define I2C_SLEEPTIME 50
time to sleep on full rx buffer to give msgpp time to consume payload
#define COMPSZ 50
Functions
void TIME_SLEEP (U4 ms)
Sleep.
U4 TIME_GET (void)
Get Timer.
HANDLE COM_OPEN (const CH *name)
Open a serial port.
BOOL COM_BAUDRATE (HANDLE h, U4 br)
set baudrate of serial COM port
void COM_CLOSE (HANDLE h)
close serial COM port
U4 COM_WRITE (HANDLE h, const void *p, U4 size)
write data to device
U4 COM_READ (HANDLE h, void *p, U4 size)
Read data from device.
void COM_CLEAR (HANDLE h)
discard all characters from the output or input buffer
void COM_FLUSH (HANDLE h)
clears the buffers for the specified file and causes all buffered data to be written to the file
HANDLE I2C_OPEN (const CH *name, int *pAddr)
open I2C port
void I2C_CLOSE (HANDLE h)
close I2C port
BOOL I2C_BAUDRATE (HANDLE h, U4 br)
set baudrate of I2C device
U4 I2C_WRITE (HANDLE h, int deviceAddress, const void *p, U4 size)
write data to I2C port
const CH * I2C_STATUS_STR (int status)
get status string from aardvark i2c status
U4 I2C_PENDING (HANDLE h, int deviceAddress)
read number of pending bytes from I2C port
U4 I2C_READ (HANDLE h, int deviceAddress, void *p, U4 size)
read data from I2C port
HANDLE SPI_OPEN (const CH *name, void **pData)
open SPI port
void SPI_CLOSE (HANDLE h)
close SPI port
BOOL SPI_BAUDRATE (HANDLE h, U4 br)
set baudrate of SPI device
U4 SPI_WRITE (HANDLE h, SPI_READBUFFER_pt pReadBuf, const void *p, U4 size)
write data to SPI port
U4 SPI_READ (HANDLE h, SPI_READBUFFER_pt pReadBuf, void *p, U4 size)
read data from SPI port
HANDLE NET_OPEN (const CH *name)
Open a network port.
U4 NET_WRITE (HANDLE h, const void *p, U4 size)
Write data to net.
U4 NET_READ (HANDLE h, void *p, U4 size)
Read data from net.
void NET_CLOSE (HANDLE h)
close net socket
BOOL NET_BAUDRATE (SER_HANDLE_pt h, U4 br)
Set baudrate of Ethernet device.
SER_HANDLE_pt SER_OPEN (const CH *name)
Open Serial Port.
BOOL SER_REENUM (SER_HANDLE_pt h, BOOL IsUsb)
Re-Enumerate Port.
U4 SER_WRITE_SPI (SER_HANDLE_pt h, const void *p, U4 size)
Write to SPI Port.
U4 SER_WRITE (SER_HANDLE_pt h, const void *p, U4 size)
Write to Serial Port.
U4 SER_READ (SER_HANDLE_pt h, void *p, U4 size)
Read from Serial Port.
void SER_CLEAR (SER_HANDLE_pt h)
Flush Serial Port.
BOOL SER_BAUDRATE (SER_HANDLE_pt h, U4 br)
changes the baudrate of the communication device
void SER_FLUSH (SER_HANDLE_pt h)
Flush Serial Port.
void SER_CLOSE (SER_HANDLE_pt h)
Close Serial Port.
U4 SER_PENDING (SER_HANDLE_pt h)
get number of pending bytes at I2C interface
void MESSAGE_PLAIN (const CH *format,...)
void MESSAGE (MSG_LEVEL level, const CH *format,...)
Print status message.
void CONSOLE_INIT (void)
initialize console
void CONSOLE_DONE (void)
cleanup console
void CONSOLE_SAVE_POS (U4 offs)
save current cursor position
void CONSOLE_RESTORE_POS (void)
restore previously saved cursor position
Variables
int verbose = 0
verbosity
static int sCONSOLE_SAVEPOS_y
static int sCONSOLE_SAVEPOS_x
static struct termios sCONSOLE_tioSave
Detailed Description
Platform abstraction layer.
Definition in file platform.c.
Macro Definition Documentation
#define closesocket (s) close(s)
cross-platform compatibility
Definition at line 93 of file platform.c.
Referenced by NET_BAUDRATE(), and NET_CLOSE().
#define COMPSZ 50
number of subsequent bytes at start of reception buffer compared for equality with 0xFF
Definition at line 1101 of file platform.c.
Referenced by SPI_READ().
#define DEFAULT_I2C_ADDR 0x42
default slave address
Definition at line 104 of file platform.c.
Referenced by I2C_OPEN().
#define FDSET fd_set
cross-platform compatibility
Definition at line 91 of file platform.c.
Referenced by NET_READ().
#define HOSTENT struct hostent
cross-platform compatibility
Definition at line 90 of file platform.c.
Referenced by NET_BAUDRATE(), and NET_OPEN().
#define I2C_SLEEPTIME 50
time to sleep on full rx buffer to give msgpp time to consume payload
Definition at line 105 of file platform.c.
Referenced by I2C_WRITE().
#define LAST_ERR () errno
cross-platform compatibility
Definition at line 94 of file platform.c.
#define LAST_NET_ERR () errno
cross-platform compatibility
Definition at line 95 of file platform.c.
Referenced by NET_READ(), and NET_WRITE().
#define SOCKADDR struct sockaddr
cross-platform compatibility
Definition at line 88 of file platform.c.
Referenced by NET_BAUDRATE(), and NET_OPEN().
#define SOCKADDR_IN struct sockaddr_in
cross-platform compatibility
Definition at line 89 of file platform.c.
Referenced by NET_BAUDRATE(), and NET_OPEN().
#define TIMEVAL struct timeval
cross-platform compatibility
Definition at line 92 of file platform.c.
Referenced by NET_READ().
Function Documentation
BOOL COM_BAUDRATE (HANDLE h, U4 br)
set baudrate of serial COM port
Parameters
h Handle to device
br Baudrate
Returns
TRUE if success, FALSE else
Definition at line 198 of file platform.c.
References FALSE, MESSAGE(), MSG_DBG, and TRUE.
Referenced by SER_BAUDRATE(), and SER_REENUM().
 {
 #ifdef WIN32
     DCB dcb;
     dcb.DCBlength = sizeof(dcb);
     if (!GetCommState(h, &dcb))
     {
         MESSAGE(MSG_DBG, "GetCommState err=%d", GetLastError());
         return FALSE;
     }
     dcb.BaudRate = br;
     dcb.ByteSize = 8;
     dcb.fBinary  = TRUE;
     dcb.DCBlength = sizeof(dcb);
     if (!SetCommState(h, &dcb))
     {
         MESSAGE(MSG_DBG, "SetCommState err=%d", GetLastError());
         return FALSE;
     }
     return TRUE;
 #else
     struct termios tp;
     int baudrate;
     switch(br)
     {
 #if !defined(__APPLE__)
         case 921600:baudrate=B921600;break;
         case 460800:baudrate=B460800;break;
 #endif
         case 230400:baudrate=B230400;break;
         case 115200:baudrate=B115200;break;
         case 57600: baudrate=B57600;break;
         case 38400: baudrate=B38400;break;
         case 19200: baudrate=B19200;break;
         case 9600:  baudrate=B9600;break;
         default:    baudrate=B9600;
     }
     tcgetattr((int)h, &tp);
     //cfmakeraw(&tp);
     tp.c_lflag = 0;
     tp.c_iflag = 0;
     tp.c_oflag = 0;
     tp.c_cflag &= ~(CSIZE|PARENB);
     tp.c_cflag |= CLOCAL | CS8;
     tp.c_cflag |= baudrate;
 #ifdef UART_TWO_STOP_BITS
     tp.c_cflag |= CSTOPB;
 #else
     tp.c_cflag &= ~CSTOPB;
 #endif
     tp.c_cc[VMIN] = 0;
     tp.c_cc[VTIME] = 0;
     cfsetospeed(&tp, baudrate);
     cfsetispeed(&tp, baudrate);
     if (tcsetattr((int)h, TCSANOW, &tp) < 0)
     { // Apply change immediately
         return FALSE;
     }
     return TRUE;
 #endif
 }
void COM_CLEAR (HANDLE h)
discard all characters from the output or input buffer
Parameters
h Handle to the serial COM port device
Definition at line 375 of file platform.c.
References MESSAGE(), MSG_DBG, and NULL.
Referenced by SER_CLEAR().
 {
 #ifdef WIN32
     U4 dw;
     U1 buf[256];
     if (!PurgeComm(h, PURGE_RXCLEAR))
         MESSAGE(MSG_DBG, "PurgeComm err=%d", GetLastError());
     while (ReadFile(h, buf, sizeof(buf), (LPDWORD)&dw, NULL) && (dw == sizeof(buf)))
         /*nop*/;
 #else
     tcflush((int)h,TCIFLUSH);
 #endif
 }
void COM_CLOSE (HANDLE h)
close serial COM port
Parameters
h Handle to device
Definition at line 269 of file platform.c.
Referenced by SER_CLOSE(), and SER_REENUM().
 {
 #ifdef WIN32
     CloseHandle(h);
 #else
     close((int)h);
 #endif
 }
void COM_FLUSH (HANDLE h)
clears the buffers for the specified file and causes all buffered data to be written to the file
Parameters
h Handle to the serial COM port device
Definition at line 393 of file platform.c.
References MESSAGE(), MSG_DBG, and MSG_WARN.
Referenced by SER_FLUSH().
 {
 #ifdef WIN32
     if (!FlushFileBuffers(h))
         MESSAGE(MSG_DBG, "FlushFileBuffers err=%d", GetLastError());
 #else
     ((void)h);
     MESSAGE(MSG_WARN, "COM_FLUSH not implemented.");
 #endif
 }
HANDLE COM_OPEN (const CH * name)
Open a serial port.
Parameters
name Symbolic link name for port
Returns
handle to port
Definition at line 149 of file platform.c.
References MESSAGE(), MSG_DBG, and NULL.
Referenced by SER_OPEN(), and SER_REENUM().
 {
 #ifdef WIN32
     HANDLE h;
     DCB dcb;
     COMMTIMEOUTS cto;
     h = CreateFile(name, GENERIC_READ | GENERIC_WRITE, 0, NULL, OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, NULL);
     if (h != INVALID_HANDLE_VALUE)
     {
         memset(&cto, 0, sizeof(cto));
         cto.ReadIntervalTimeout = MAXDWORD;
         memset(&dcb, 0, sizeof(dcb));
         dcb.DCBlength = sizeof(dcb);
         dcb.fDtrControl = 1;
         dcb.fRtsControl = 1;
         if (!SetupComm(h, 4096, 32768))
             MESSAGE(MSG_DBG, "SetupComm err=%d", GetLastError());
         if (!SetCommTimeouts(h, &cto))
             MESSAGE(MSG_DBG, "SetCommTimeouts err=%d", GetLastError());
         if (!BuildCommDCB("baud=9600 parity=N data=8 stop=1", &dcb))
             MESSAGE(MSG_DBG, "BuildCommDCB err=%d", GetLastError());
         if (!SetCommState(h, &dcb))
             MESSAGE(MSG_DBG, "SetCommState err=%d", GetLastError());
         return h;
     }
     return NULL;
 #else
     // open the serial port with the NDELAY option
     // otherwise this may block forever because u-blox chips
     // don't support the DCD line
     int fd = open(name, O_RDWR | O_NOCTTY | O_NDELAY);
     if (fd < 0)
     {
         return (HANDLE)0;
     }
     // remove the NDELAY option again, it will be
     // handled on the lower layer when setting the baudrate
     fcntl(fd, F_SETFL, 0);
     return (HANDLE)fd;
 #endif
 }
U4 COM_READ (HANDLE h, void * p, U4 size)
Read data from device.
Parameters
h Handle to serial COM device
p Pointer to user-allocated buffer of at least size size
size Number of bytes to read from device
Returns
number of bytes which were read from device
Definition at line 329 of file platform.c.
References MESSAGE(), MSG_DBG, and NULL.
Referenced by SER_READ().
 {
 #ifdef WIN32
     U4 dwRead = 0;
     if (!ReadFile(h, p, size, (LPDWORD)&dwRead, NULL))
     {
         MESSAGE(MSG_DBG, "ReadFile err=%d", GetLastError());
         return 0;
     }
     return dwRead;
 #else
     I4 dw = read((int)h,p,size);
     //if (dw>0) dump_data("COM_READ ",(U1 *)p, dw);
     return dw>0 ? (U4)dw : 0;
 #endif
 }
U4 COM_WRITE (HANDLE h, const void * p, U4 size)
write data to device
Parameters
h Handle to serial COM device
p Pointer to data to write
size Size of data to write
Returns
number of bytes written
Definition at line 285 of file platform.c.
References MESSAGE(), MSG_DBG, MSG_ERR, and NULL.
Referenced by SER_WRITE().
 {
 #ifdef WIN32
     U4 dw;
     if (!WriteFile(h, p, size, (LPDWORD)&dw, NULL))
     {
         MESSAGE(MSG_DBG, "WriteFile err=%d", GetLastError());
         return 0;
     }
     return dw;
 #else
     I4 dw = write((int)h,p,size);
     //if (dw>0) dump_data("COM_WRITE ",(U1 *)p, dw);
     if ((U4)dw != size)
         MESSAGE(MSG_ERR, "can not write all data (req: %li, actual: %li)", size, dw);
     return dw>0?(U4)dw:0;
 #endif
 }
void CONSOLE_DONE (void)
cleanup console
Definition at line 2103 of file platform.c.
References sCONSOLE_tioSave.
Referenced by main().
 {
 #ifndef WIN32
     if (isatty(fileno(stderr)))
     {
         fflush(stdin);
         tcsetattr(fileno(stdin), TCSANOW, &sCONSOLE_tioSave);
     }
 #endif // WIN32
 }
void CONSOLE_INIT (void)
initialize console
Definition at line 2081 of file platform.c.
References sCONSOLE_tioSave, and TRUE.
Referenced by main().
 {
 #ifdef WIN32
     SetConsoleCtrlHandler(CONSOLE_CTRLHANDLER, TRUE);
 #else
     // make stdin unbuffered, disable echo, etc.
     struct termios tio;
     if (isatty(fileno(stderr)))
     {
         tcgetattr(fileno(stderr), &tio);
         memcpy(&sCONSOLE_tioSave, &tio, sizeof(struct termios));
         tio.c_lflag     &= (~ICANON);
         tio.c_lflag     &= (~ECHO);
         tio.c_cc[VTIME]  = 1;
         tio.c_cc[VMIN]   = 0;
         tcsetattr(fileno(stderr), TCSANOW, &tio);
     }
 #endif // WIN32
     sCONSOLE_SAVEPOS_y = 1;
     sCONSOLE_SAVEPOS_x = 1;
 }
void CONSOLE_RESTORE_POS (void)
restore previously saved cursor position
Definition at line 2162 of file platform.c.
Referenced by updDumpAck().
 {
 #ifdef WIN32
     COORD coord;
     coord.X = (SHORT)sCONSOLE_SAVEPOS_x;
     coord.Y = (SHORT)sCONSOLE_SAVEPOS_y;
     SetConsoleCursorPosition(GetStdHandle(STD_ERROR_HANDLE),coord);
 #else
     if (isatty(fileno(stderr)))
     {
         fprintf(stderr, "\e[%u;%uH", sCONSOLE_SAVEPOS_y, sCONSOLE_SAVEPOS_x);
         fflush(stderr);
     }
 #endif // WIN32
 }
void CONSOLE_SAVE_POS (U4 offs)
save current cursor position
Definition at line 2115 of file platform.c.
References MESSAGE_PLAIN().
Referenced by updInit().
 {
     // scroll terminal
     U4 i;
     for(i =  0;  i < offs; i++)
     {
         MESSAGE_PLAIN("\n");
     }
     fflush(stderr);
 #ifdef WIN32
     CONSOLE_SCREEN_BUFFER_INFO info;
     GetConsoleScreenBufferInfo(GetStdHandle(STD_ERROR_HANDLE),&info);
     sCONSOLE_SAVEPOS_x = info.dwCursorPosition.X;
     sCONSOLE_SAVEPOS_y = info.dwCursorPosition.Y;
 #else // WIN32
     if (isatty(fileno(stderr)))
     {
         char buf[16];
         char *pBuf = buf;
         // request cursor position
         fprintf(stderr, "\e[6n");
         fflush(stderr);
         // read cursor position (expecting: "^[[xxx;yyyR")
         int timeout = 10;
         while ( (pBuf - buf < 12) && (*pBuf != 'R') && timeout--)
         {
             if (read(0, pBuf, 1))
             {
                 pBuf++;
             }
         }
         int x = 0, y = 0;
         if (sscanf(buf+2, "%i;%iR", &y, &x) == 2)
         {
             sCONSOLE_SAVEPOS_y = y;
             sCONSOLE_SAVEPOS_x = x;
         }
     }
 #endif // WIN32
     sCONSOLE_SAVEPOS_y -= offs;
     if (sCONSOLE_SAVEPOS_y < 1)
     {
         sCONSOLE_SAVEPOS_y = 1;
     }
 }
BOOL I2C_BAUDRATE (HANDLE h, U4 br)
set baudrate of I2C device
Parameters
h handle to device
br baudrate to set
Returns
TRUE
Definition at line 839 of file platform.c.
References MESSAGE(), MSG_DBG, and TRUE.
Referenced by SER_BAUDRATE(), and SER_REENUM().
 {
     br = aa_i2c_bitrate((Aardvark)h,br/1000);
     MESSAGE(MSG_DBG, "Baudrate %dkHz",br);
     return TRUE;
 }
void I2C_CLOSE (HANDLE h)
close I2C port
Parameters
h handle to device
Definition at line 828 of file platform.c.
Referenced by SER_CLOSE().
 {
     aa_close((Aardvark)h);
 }
HANDLE I2C_OPEN (const CH * name, int * pAddr)
open I2C port
Parameters
name name of the I2C port ("I2C0:0x42", "I2C1:0x42", ...)
pAddr pointer to receive i2c address
Returns
handle to the device
Definition at line 788 of file platform.c.
References DEFAULT_I2C_ADDR, MESSAGE(), MSG_DBG, and MSG_ERR.
Referenced by SER_OPEN().
 {
     int devIndex = atoi(name+3);
     int i2cAddr;
     // find device index and i2c slave address
     int parsedFields = sscanf(name+3,"%d:0x%x",&devIndex,&i2cAddr);
     // assign defaults
     if (parsedFields < 2)
     {
         i2cAddr = DEFAULT_I2C_ADDR;
     }
     if (parsedFields < 1)
     {
         devIndex = 0;
     }
     // get access to aardvark
     Aardvark dev = aa_open(devIndex);
     MESSAGE(MSG_DBG,"aardvark port %d I2C address 0x%x",devIndex,i2cAddr);
     // bail on invalid dev handle
     if ((int)dev <= 0)
     {
         MESSAGE(MSG_ERR, "%s", aa_status_string((int)dev));
         *pAddr = 0;
         return (HANDLE)0;
     }
     *pAddr = i2cAddr;
     // enable I2C mode
     aa_configure(dev,  AA_CONFIG_GPIO_I2C);
     // enable pullups
     aa_i2c_pullup(dev, AA_I2C_PULLUP_BOTH);
     return (HANDLE)dev;
 }
U4 I2C_PENDING (HANDLE h, int deviceAddress)
read number of pending bytes from I2C port
Parameters
h handle to device
deviceAddress address of the I2C device
Returns
number of bytes pending
Definition at line 907 of file platform.c.
References I2C_STATUS_STR(), MESSAGE(), MSG_ERR, and TIME_SLEEP().
Referenced by I2C_READ(), and SER_PENDING().
 {
     // set address
     const u08 sizeAddr = 0xFD;
     u16 writtenBytes = 0;
     int status = aa_i2c_write_ext((Aardvark)h,(u16)deviceAddress,AA_I2C_NO_STOP,1,&sizeAddr,&writtenBytes);
     if (status != 0)
     {
 #ifdef AARDVARK_DEBUG_PIN
         aa_gpio_set((Aardvark)h, AA_GPIO_MISO);
         aa_gpio_direction((Aardvark)h, AA_GPIO_MISO);
         TIME_SLEEP(5);
         aa_gpio_set((Aardvark)h, 0);
 #endif //AARDVARK_DEBUG_PIN
         const char * status_string = aa_status_string((int)status);
         if (!status_string) status_string = I2C_STATUS_STR(status);
         MESSAGE(MSG_ERR, "I2C_PENDING write ext addr: %s (%d)", status_string, status);
         status = aa_i2c_free_bus((Aardvark)h);
         if (status != 0)
         {
             status_string = aa_status_string((int)status);
             if (!status_string) status_string = I2C_STATUS_STR(status);
             MESSAGE(MSG_ERR, "I2C_PENDING free bus: %s (%d)", status_string, status);
         }
         return 0;
     }
     // read length
     u16 readBytes  = 0;
     u08 bytesAvail[2] = {0};
     status = aa_i2c_read_ext((Aardvark)h,(u16)deviceAddress,AA_I2C_NO_FLAGS,(u16)2,bytesAvail,&readBytes);
     if (status != 0)
     {
 #ifdef AARDVARK_DEBUG_PIN
         aa_gpio_set((Aardvark)h, AA_GPIO_MISO);
         aa_gpio_direction((Aardvark)h, AA_GPIO_MISO);
         TIME_SLEEP(10);
         aa_gpio_set((Aardvark)h, 0);
 #endif //AARDVARK_DEBUG_PIN
         const char * status_string = aa_status_string((int)status);
         if (!status_string) status_string = I2C_STATUS_STR(status);
         MESSAGE(MSG_ERR, "I2C_PENDING read data: %s (%d)", status_string, status);
         return 0;
     }
     // minimum of both lengths
     u16 length = (bytesAvail[0]<<8) + bytesAvail[1];
     return length;
 }
U4 I2C_READ (HANDLE h, int deviceAddress, void * p, U4 size)
read data from I2C port
Parameters
h handle to device
deviceAddress address of the I2C device
p pointer to user-allocated buffer of at least size size to receive data
size number of bytes to read
Returns
number of bytes read
Definition at line 963 of file platform.c.
References I2C_PENDING(), I2C_STATUS_STR(), MESSAGE(), MSG_ERR, and TIME_SLEEP().
Referenced by SER_READ().
 {
     u16 length = (u16)I2C_PENDING(h, deviceAddress);
     u16 readBytes = 0;
     length = length > size ? (u16)size : length;
     // read data
     if (length)
     {
         int status = aa_i2c_read_ext((Aardvark)h,(u16)deviceAddress,AA_I2C_NO_FLAGS,length,(u08*)p,&readBytes);
         if (status != 0)
         {
 #ifdef AARDVARK_DEBUG_PIN
             aa_gpio_set((Aardvark)h, AA_GPIO_MISO);
             aa_gpio_direction((Aardvark)h, AA_GPIO_MISO);
             TIME_SLEEP(20);
             aa_gpio_set((Aardvark)h, 0);
 #endif //AARDVARK_DEBUG_PIN
             const char * status_string = aa_status_string((int)status);
             if (!status_string)    status_string = I2C_STATUS_STR(status);
             MESSAGE(MSG_ERR, "I2C_READ read data: %s (%d)", status_string, status);
             return 0;
         }
     }
     else
     {
         aa_i2c_free_bus((Aardvark)h);
         readBytes = 0;
     }
     return (U4)readBytes;
 }
const CH* I2C_STATUS_STR (int status)
get status string from aardvark i2c status
Parameters
status status identifier
Returns
string containing status text
Definition at line 878 of file platform.c.
Referenced by I2C_PENDING(), and I2C_READ().
 {
     switch (status)
     {
     case AA_I2C_STATUS_BUS_ERROR:
         return "bus error";
     case AA_I2C_STATUS_SLA_ACK:
         return "arbitration lost";
     case AA_I2C_STATUS_SLA_NACK:
         return "slave addr NACK";
     case AA_I2C_STATUS_DATA_NACK:
         return "data NACK";
     case AA_I2C_STATUS_ARB_LOST:
         return "ARB lost";
     case AA_I2C_STATUS_BUS_LOCKED:
         return "BUS locked";
     case AA_I2C_STATUS_LAST_DATA_ACK:
         return "last data ACK";
     default:
         return "unknown";
     }
 }
U4 I2C_WRITE (HANDLE h, int deviceAddress, const void * p, U4 size)
write data to I2C port
Parameters
h handle to device
deviceAddress address of the I2C device
p pointer to data to write
size size of data to write
Returns
number of bytes written
Definition at line 855 of file platform.c.
References I2C_SLEEPTIME, MESSAGE(), and MSG_ERR.
Referenced by SER_WRITE().
 {
     u16 writtenBytes;
     int status = aa_i2c_write_ext((Aardvark)h,(u16)deviceAddress,AA_I2C_NO_FLAGS,(u16)size,(u08*)p,&writtenBytes);
     if (status < 0)
     {
         MESSAGE(MSG_ERR, "I2C_WRITE write data:%s (%d)", aa_status_string((int)status),status);
         return 0;
     }
     if (writtenBytes < size)
     {
         // rxbuffer seems to be full
         //MESSAGE(MSG_DBG,"wait",size);
         aa_sleep_ms(I2C_SLEEPTIME);
     }
     return (U4)writtenBytes;
 }
void MESSAGE (MSG_LEVEL level, const CH * format, ...)
Print status message.
Print status message to standard output. The message is printed if level is lower or equal to MSG_LEV2 or verbose is TRUE and level is lower or equal to MSG_DBG; it is discarded otherwise.
Messages assigned a message level MSG_ERR or MSG_WARN are prefixed with "ERROR:" or "WARNING:", respectively. Messages of type MSG_DBG are prefixed with a hyphen. See details for MSG_LEVEL for a definition of valid message levels.
Parameters
level IN: message level
format IN: format string
... IN: optional arguments
Definition at line 1992 of file platform.c.
References MSG_DBG, MSG_ERR, MSG_LEV0, MSG_LEV1, MSG_LEV2, MSG_WARN, NULL, TIME_GET(), and verbose.
Referenced by COM_BAUDRATE(), COM_CLEAR(), COM_FLUSH(), COM_OPEN(), COM_READ(), COM_WRITE(), doReset(), DumpFlashInfo(), extractHwGeneration(), GetFlashOrganisation(), getNoFisMergingData(), GetPacketNrForSector(), GetSectorNrForSize(), I2C_BAUDRATE(), I2C_OPEN(), I2C_PENDING(), I2C_READ(), I2C_WRITE(), main(), NET_BAUDRATE(), NET_OPEN(), NET_READ(), NET_WRITE(), OpenAndBufferFile(), rcvConnect(), rcvDoAutobaud(), rcvPollMessage(), rcvReenumerate(), rcvSendTrainingSequence(), rcvSetBaud(), SER_REENUM(), SPI_BAUDRATE(), SPI_OPEN(), SPI_READ(), SPI_WRITE(), UbxSearchMsg(), UpdateFirmware(), updateImageToRam(), updDumpAck(), updEraseSector(), updInit(), updProcessMessages(), updSendWrite(), updUpdate(), updWritePacket(), ValidateImage(), and verifyImage().
 {
     static U4 tick = 0;
     // Must be done like this because the result of TIME_GET()
     // can not be the initializer of a compile-time constant
     if(tick==0)
         tick=TIME_GET();
 #ifdef WIN32
     HANDLE hErrOut = GetStdHandle(STD_ERROR_HANDLE);
     U4 dw;
 #endif // WIN32
     // maximum line length
     CH mem[1024];
     U4 cnt;
     if (level > ((verbose) ? MSG_DBG : MSG_LEV2))
     {
         return;
     }
     cnt = 0;
     cnt += sprintf(&mem[cnt], "%5.1f ", 0.001 * (double) (TIME_GET() - tick));
     switch (level)
     {
 #ifdef _TEST
         case MSG_TEST:  break;
 #endif // _TEST
         case MSG_ERR:    cnt+=sprintf(&mem[cnt], "ERROR: ");
 #ifdef WIN32
             SetConsoleTextAttribute(hErrOut,FOREGROUND_RED|FOREGROUND_INTENSITY);
 #endif // WIN32
             break;
         case MSG_WARN:    cnt+=sprintf(&mem[cnt], "WARNING: ");
 #ifdef WIN32
             SetConsoleTextAttribute(hErrOut,FOREGROUND_RED|FOREGROUND_GREEN|FOREGROUND_INTENSITY);
 #endif // WIN32
             break;
         case MSG_LEV0:    break;
         case MSG_LEV1:    cnt+=sprintf(&mem[cnt], " ");        break;
         case MSG_LEV2:
 #ifdef WIN32
             SetConsoleTextAttribute(hErrOut,FOREGROUND_BLUE|FOREGROUND_INTENSITY);
 #endif // WIN32
             break;
         default:
         case MSG_DBG:    cnt+=sprintf(&mem[cnt], "  - ");    break;
     }
     va_list args;
     va_start(args, format);
     cnt += vsprintf(&mem[cnt], format, args);
     va_end(args);
     cnt += sprintf(&mem[cnt], "\r\n");
 #ifdef WIN32
     WriteFile(hErrOut, mem, cnt, (LPDWORD)&dw, NULL);
     SetConsoleTextAttribute(hErrOut,FOREGROUND_RED|FOREGROUND_GREEN|FOREGROUND_BLUE);
 #else
     fprintf(stderr, "%s", mem);
 #endif // WIN32
 }
void MESSAGE_PLAIN (const CH * format, ...)
Definition at line 1971 of file platform.c.
References NULL.
Referenced by CONSOLE_SAVE_POS(), main(), ParseArguments(), SER_REENUM(), updDumpAck(), updEraseSector(), updProcessMessages(), updWritePacket(), and Usage().
 {
     CH mem[1024];
     U4 cnt = 0;
     va_list args;
     va_start(args, format);
     cnt += vsprintf(&mem[cnt], format, args);
     va_end(args);
 #ifdef WIN32
     HANDLE hErrOut = GetStdHandle(STD_ERROR_HANDLE);
     U4 dw;
     WriteFile(hErrOut, mem, cnt, (LPDWORD)&dw, NULL);
 #else
     fprintf(stderr, "%s", mem);
     fflush(stderr);
 #endif // WIN32
 }
BOOL NET_BAUDRATE (SER_HANDLE_pt h, U4 br)
Set baudrate of Ethernet device.
Parameters
h handle to device
br baudrate to set
Returns
TRUE
Definition at line 1310 of file platform.c.
References closesocket, FALSE, HOSTENT, MESSAGE(), MSG_DBG, MSG_ERR, SER_HANDLE_s::pName, SOCKADDR, SOCKADDR_IN, and TRUE.
Referenced by SER_BAUDRATE(), and SER_REENUM().
 {
     char serverName[64];
     strncpy(serverName,h->pName,sizeof(serverName)-1);
     char *pEnd = strchr(serverName,':');
     if (!pEnd)
     {
         MESSAGE(MSG_ERR,"failed extracting host name: %s",h->pName);
         return FALSE;
     }
     *pEnd = 0; // terminate
     int portNum = (atoi(++pEnd) % 100)-1; // only use the two least significant digits
     MESSAGE(MSG_DBG,"setting port %d on %s to %d baud",portNum,serverName,br);
     char requestStr[128];
     // prepare request URL to be sent to ttycat
     sprintf(requestStr,"/goform/setPortConfig?portNum=%d&baudRate=%u&portEnable=1&listenEnable=1",portNum,br);
     MESSAGE(MSG_DBG,"req: %s",requestStr);
     // prepare and connect socket to HTTP port of ttycat
     SOCKET sock = socket( AF_INET, SOCK_STREAM, 0 );
     if (sock == INVALID_SOCKET)
     {
         MESSAGE(MSG_ERR,"unable to create socket");
         return FALSE;
     }
     SOCKADDR_IN sa;
     sa.sin_family = AF_INET;
     sa.sin_port   = htons(80);
     HOSTENT *pHost = gethostbyname(serverName);
     struct in_addr* pHexAddress = (struct in_addr*)pHost->h_addr_list[ 0 ];
     char* dottedAddress = inet_ntoa( *pHexAddress );
     sa.sin_addr.s_addr = inet_addr( dottedAddress );
     if (connect(sock,(const SOCKADDR*) &sa,
         sizeof(SOCKADDR_IN)) == SOCKET_ERROR)
     {
         MESSAGE(MSG_ERR,"connection to socket failed");
         closesocket(sock);
         return FALSE;
     }
     // no construct HTTP request header
     char httpRequest[512];
     sprintf(httpRequest,
              "GET %s HTTP/1.1\r\n"
              "User-Agent: FWUpdateG5/linux\r\n"
              "Host: %s\r\n"
              "Connection: Keep-Alive\r\n"
              "Cache-Control: no-cache\r\n"
              "\r\n",requestStr,serverName);
     //MESSAGE(MSG_DBG,"request: %s",httpRequest);
     // send request
     int ret = send(sock,(const char*)httpRequest,strlen(httpRequest),0);
     if (ret == SOCKET_ERROR)
     {
         MESSAGE(MSG_ERR,"sending request failed");
         closesocket(sock);
         return FALSE;
     }
     // get response
     char httpResponse[512];
     ret = recv(sock,httpResponse,sizeof(httpResponse),0);
     if (ret == SOCKET_ERROR)
     {
         MESSAGE(MSG_ERR,"receiving response failed");
         closesocket(sock);
         return FALSE;
     }
     int status;
     if (sscanf(httpResponse,"HTTP/1.1 %d ",&status))
     {
         MESSAGE(MSG_DBG,"status: %d",status);
         if (status != 200 && status != 302) // comtrol devicemaster sends redirection
         {
             MESSAGE(MSG_ERR,"response returned failing status");
             closesocket(sock);
             return FALSE;
         }
     }
     //MESSAGE(MSG_DBG,"response: %s",httpResponse);
     closesocket(sock);
     return TRUE;
 }
void NET_CLOSE (HANDLE h)
close net socket
Parameters
h Handle to device
Definition at line 1295 of file platform.c.
References closesocket.
Referenced by SER_CLOSE().
 {
     SOCKET sock = (SOCKET)h;
     closesocket(sock);
 #ifdef WIN32
     WSACleanup();
 #endif
 }
HANDLE NET_OPEN (const CH * name)
Open a network port.
Parameters
name name for port, format hostname:port
Returns
handle to port
Definition at line 1176 of file platform.c.
References HOSTENT, MESSAGE(), MSG_DBG, MSG_ERR, NULL, SOCKADDR, and SOCKADDR_IN.
Referenced by SER_OPEN().
 {
     CH nameCopy[64];
     strncpy(nameCopy,name,sizeof(nameCopy)-1);
 #ifdef WIN32
     WSADATA wsaData;
     if (WSAStartup(MAKEWORD(1,1),&wsaData))
     {
         MESSAGE(MSG_ERR,"WinSock not available");
         return 0;
     }
     else
     {
         if (LOBYTE(wsaData.wVersion) != 1 ||
             HIBYTE(wsaData.wVersion) != 1 )
         {
             MESSAGE(MSG_ERR,"no WinSock 1.1");
             WSACleanup();
             return 0;
         }
     }
 #endif
     SOCKET sock = socket( AF_INET, SOCK_STREAM, 0 );
     if (sock == INVALID_SOCKET)
     {
         MESSAGE(MSG_ERR,"unable to create socket");
 #ifdef WIN32
         WSACleanup();
 #endif
         return (HANDLE)0;
     }
     CH* host    = nameCopy;
     CH* portStr = strchr(nameCopy,':');
     if(!portStr)
         return 0;
     *portStr = 0;
     portStr++;
     U portNum = atoi(portStr);
     SOCKADDR_IN sa;
     sa.sin_family = AF_INET;
     sa.sin_port   = htons(portNum);
     HOSTENT *pHost = gethostbyname(host);
     if (pHost == NULL)
     {
         MESSAGE(MSG_ERR, "Cannot resolve hostname %s!", host);
         return (HANDLE)0;
     }
     struct in_addr* pHexAddress = (struct in_addr*)pHost->h_addr_list[ 0 ];
     char* dottedAddress = inet_ntoa( *pHexAddress );
     sa.sin_addr.s_addr = inet_addr( dottedAddress );
     MESSAGE(MSG_DBG,"opening port %d on host %s (%s)",portNum,host,dottedAddress);
     if (connect(sock,(const SOCKADDR*) &sa,
         sizeof( SOCKADDR_IN )) == SOCKET_ERROR)
     {
         MESSAGE(MSG_ERR,"connection to socket failed");
 #ifdef WIN32
         WSACleanup();
 #endif
         return (HANDLE)0;
     }
     return (HANDLE)sock;
 }
U4 NET_READ (HANDLE h, void * p, U4 size)
Read data from net.
Parameters
h Handle to net socket
p Pointer to user-allocated buffer of at least size size
size Number of bytes to read from device
Returns
number of bytes which were read from device
Definition at line 1270 of file platform.c.
References FDSET, LAST_NET_ERR, MESSAGE(), MSG_ERR, NULL, and TIMEVAL.
Referenced by SER_READ().
 {
     SOCKET sock = (SOCKET)h;
     FDSET fds;
     FD_ZERO(&fds);
     FD_SET(sock,&fds);
     TIMEVAL tv = {0,0};
     int nReady = select(sock+1,&fds,NULL,NULL,&tv);
     if (nReady)
     {
         int ret = recv(sock,(char *)p,size,0);
         if (ret == SOCKET_ERROR)
         {
             MESSAGE(MSG_ERR,"read from socket failed: %d",LAST_NET_ERR());
             return 0;
         }
         return (U4)ret;
     }
     return 0;
 }
U4 NET_WRITE (HANDLE h, const void * p, U4 size)
Write data to net.
Parameters
h Handle to net socket
p Pointer to user-allocated buffer of at least size size
size Number of bytes to write to device
Returns
number of bytes which were written to device
Definition at line 1251 of file platform.c.
References LAST_NET_ERR, MESSAGE(), and MSG_ERR.
Referenced by SER_WRITE().
 {
     SOCKET sock = (SOCKET)h;
     int ret = send(sock,(const char*)p,size,0);
     if (ret == SOCKET_ERROR)
     {
         MESSAGE(MSG_ERR,"write to socket failed: %d",LAST_NET_ERR());
         return 0;
     }
     return (U4)ret;
 }
BOOL SER_BAUDRATE (SER_HANDLE_pt h, U4 br)
changes the baudrate of the communication device
Parameters
h Handle to the device
br baudrate to set for the device
Returns
TRUE if the setting succeeded, FALSE else
Definition at line 1835 of file platform.c.
References SER_HANDLE_s::baudrate, COM, COM_BAUDRATE(), FALSE, SER_HANDLE_s::handle, I2C, I2C_BAUDRATE(), NET, NET_BAUDRATE(), SPI, SPI_BAUDRATE(), SPU, STDINOUT, TRUE, SER_HANDLE_s::type, and U2C.
Referenced by rcvSetBaud().
 {
     BOOL brSet = FALSE;
     //MESSAGE(MSG_DBG, "platform: switching baudrate to %d baud", br);
     switch(h->type)
     {
     case COM:
         brSet = COM_BAUDRATE(h->handle,br);
         break;
 #ifdef WIN32
     case STDINOUT:
         STDIN_SETBAUD(br);
         brSet = TRUE; // There is no baudrate here
         break;
 #endif //ifdef WIN32
 #ifdef ENABLE_AARDVARK_SUPPORT
     case I2C:
         brSet = I2C_BAUDRATE(h->handle,br);
         break;
     case SPI:
         brSet = SPI_BAUDRATE(h->handle,br);
         break;
 #endif // ENABLE_AARDVARK_SUPPORT
 #ifdef ENABLE_DIOLAN_SUPPORT
     case SPU:
         brSet = SPU_BAUDRATE(h->handle,br);
         break;
     case U2C:
         brSet = U2C_BAUDRATE(h->handle,br);
         break;
 #endif // ENABLE_DIOLAN_SUPPORT
 #ifdef ENABLE_NET_SUPPORT
     case NET:
         brSet = NET_BAUDRATE(h,br);
         break;
 #endif // ENABLE_NET_SUPPORT
     default:
         break;
     }
     if (brSet)
     {
         h->baudrate = br;
     }
     return brSet;
 }
void SER_CLEAR (SER_HANDLE_pt h)
Flush Serial Port.
Flush pending bytes from serial buffer
Parameters
h IN: handle to open serial port
Definition at line 1823 of file platform.c.
References COM, COM_CLEAR(), SER_HANDLE_s::handle, and SER_HANDLE_s::type.
Referenced by rcvConnect(), rcvDisconnect(), and rcvFlushBuffer().
 {
     switch(h->type)
     {
     case COM:
         COM_CLEAR(h->handle);
         break;
     default:
         break;
     }
 }
void SER_CLOSE (SER_HANDLE_pt h)
Close Serial Port.
Close serial port
Parameters
h IN: handle to open serial port
Definition at line 1899 of file platform.c.
References COM, COM_CLOSE(), SER_HANDLE_s::handle, I2C, I2C_CLOSE(), NET, NET_CLOSE(), SER_HANDLE_s::pData, SPI, SPI_CLOSE(), SPU, STDINOUT, SER_HANDLE_s::type, and U2C.
Referenced by rcvDisconnect().
 {
     if (!h)
         return;
     switch(h->type)
     {
     case COM:
         COM_CLOSE(h->handle);
         break;
 #ifdef WIN32
     case STDINOUT:
         break;
 #endif //ifdef WIN32
 #ifdef ENABLE_AARDVARK_SUPPORT
     case I2C:
         I2C_CLOSE(h->handle);
         break;
     case SPI:
         SPI_CLOSE(h->handle);
         break;
 #endif // ENABLE_AARDVARK_SUPPORT
 #ifdef ENABLE_DIOLAN_SUPPORT
     case U2C:
         U2C_CLOSE(h->handle);
         break;
     case SPU:
         SPU_CLOSE(h->handle);
         break;
 #endif // ENABLE_DIOLAN_SUPPORT
 #ifdef ENABLE_NET_SUPPORT
     case NET:
         NET_CLOSE(h->handle);
         break;
 #endif // ENABLE_NET_SUPPORT
     default:
         break;
     }
     // free custom data
     if (h->pData)
         free(h->pData);
     // free handle
     free(h);
 }
void SER_FLUSH (SER_HANDLE_pt h)
Flush Serial Port.
Write the buffered data to the port
Parameters
h IN: handle to open serial port
Definition at line 1884 of file platform.c.
References COM, COM_FLUSH(), SER_HANDLE_s::handle, and SER_HANDLE_s::type.
 {
     if (!h)
         return;
     switch (h->type)
     {
     case COM:
         COM_FLUSH(h->handle);
         break;
     default:
         break;
     }
 }
SER_HANDLE_pt SER_OPEN (const CH * name)
Open Serial Port.
Open serial port indicated by name.
Parameters
name IN: name of serial port to open
Returns
handle to opened port on success, NULL on failure
Definition at line 1407 of file platform.c.
References SER_HANDLE_s::baudrate, COM, COM_OPEN(), SER_HANDLE_s::devAddr, SER_HANDLE_s::handle, I2C, I2C_OPEN(), NET, NET_OPEN(), NULL, SER_HANDLE_s::pData, SER_HANDLE_s::pName, SPI, SPI_OPEN(), SPU, STDINOUT, SER_HANDLE_s::type, and U2C.
Referenced by rcvConnect().
 {
     SER_TYPE_t serType = COM;
     HANDLE     handle = (HANDLE)0;
     SER_HANDLE_pt pSerHandle;
     void *pData = NULL;
     int        addr = 0;
 #ifdef ENABLE_DIOLAN_SUPPORT
     if (!handle && (strncmp(name, "U2C",3) == 0 || strncmp(name, "u2c",3) == 0))
     {
         serType = U2C;
         handle  = U2C_OPEN(name,&addr);
     }
     if (!handle && (strncmp(name, "SPU",3) == 0 || strncmp(name, "spu",3) == 0))
     {
         serType = SPU;
         handle  = SPU_OPEN(name,&pData);
     }
 #endif // ENABLE_DIOLAN_SUPPORT
 #ifdef ENABLE_AARDVARK_SUPPORT
     if (!handle && strncmp(name, "I2C", 3) == 0)
     {
         serType = I2C;
         handle = I2C_OPEN(name, &addr);
     }
     if (!handle && (strncmp(name, "SPI", 3) == 0 ||
                     strncmp(name, "spi", 3) == 0))
     {
         serType = SPI;
         handle = SPI_OPEN(name, &pData);
     }
 #endif // ENABLE_AARDVARK_SUPPORT
 #ifdef ENABLE_NET_SUPPORT
     if (!handle && strchr(name, ':'))
     {
         serType = NET;
         handle  = NET_OPEN(name);
     }
     else
 #endif // ENABLE_NET_SUPPORT
     if (!handle)
     {
         serType = COM;
         handle  = COM_OPEN(name);
     }
 #ifdef WIN32
     if (!handle && (strncmp(name, "STDIO", 5) == 0 || strncmp(name, "stdio", 5) == 0))
     {
         serType = STDINOUT;
         handle  = (HANDLE) -1; // Indicates stdin/stdout. Never used -> unique identifier
         // Make sure windows does not replace "\n" to "\r\n"
         if(_setmode(fileno(stdout), O_BINARY) == -1)
         {
             // In case of error abort here
             handle = (HANDLE)0;
         }
     }
 #endif //ifdef WIN32
     if (handle)
     {
         pSerHandle = (SER_HANDLE_pt)malloc(sizeof(SER_HANDLE_t));
         if (pSerHandle)
         {
             pSerHandle->handle   = handle;  // device handle
             pSerHandle->type     = serType; // device type
             pSerHandle->devAddr  = addr;    // device address
             pSerHandle->pData    = pData;   // custom data pointer
             pSerHandle->pName    = name;    // backup name
             pSerHandle->baudrate = 0;       // baudrate not set yet
             return pSerHandle;
         }
     }
     return NULL;
 }
U4 SER_PENDING (SER_HANDLE_pt h)
get number of pending bytes at I2C interface
Parameters
h IN: handle to open port
Returns
number of pending bytes
Definition at line 1944 of file platform.c.
References COM, SER_HANDLE_s::devAddr, SER_HANDLE_s::handle, I2C, I2C_PENDING(), SER_HANDLE_s::type, and U2C.
 {
     if (!h)
         return 0;
     switch (h->type)
     {
 #ifdef ENABLE_AARDVARK_SUPPORT
     case I2C:
         return I2C_PENDING(h->handle, h->devAddr);
 #endif // ENABLE_AARDVARK_SUPPORT
 #ifdef ENABLE_DIOLAN_SUPPORT
     case U2C:
         return U2C_PENDING(h->handle, h->devAddr);
 #endif // ENABLE_DIOLAN_SUPPORT
     case COM:
     default:
         break;
     }
     return 0;
 }
U4 SER_READ (SER_HANDLE_pt h, void * p, U4 size)
Read from Serial Port.
Read data from serial port
Parameters
h IN: handle to open serial port
p OUT: buffer to write data to
size IN: number of bytes to be read
Returns
number of bytes read
Definition at line 1789 of file platform.c.
References COM, COM_READ(), SER_HANDLE_s::devAddr, SER_HANDLE_s::handle, I2C, I2C_READ(), NET, NET_READ(), SER_HANDLE_s::pData, SPI, SPI_READ(), SPU, STDINOUT, SER_HANDLE_s::type, and U2C.
Referenced by rcvReceiveMessage().
 {
     switch(h->type)
     {
     case COM:
         return COM_READ(h->handle,p,size);
 #ifdef WIN32
     case STDINOUT:
         return STDIN_READ(p,size);
 #endif //ifdef WIN32
 #ifdef ENABLE_AARDVARK_SUPPORT
     case I2C:
         return I2C_READ(h->handle,h->devAddr,p,size);
     case SPI:
         return SPI_READ(h->handle,(SPI_READBUFFER_pt)h->pData,p,size);
 #endif // ENABLE_AARDVARK_SUPPORT
 #ifdef ENABLE_DIOLAN_SUPPORT
     case U2C:
         return U2C_READ(h->handle,h->devAddr,p,size);
     case SPU:
         return SPU_READ(h->handle,(SPI_READBUFFER_pt)h->pData,p,size);
 #endif // ENABLE_DIOLAN_SUPPORT
 #ifdef ENABLE_NET_SUPPORT
     case NET:
         return NET_READ(h->handle,p,size);
 #endif // ENABLE_NET_SUPPORT
     default:
         break;
     }
     return 0;
 }
BOOL SER_REENUM (SER_HANDLE_pt h, BOOL IsUsb)
Re-Enumerate Port.
Re-Enumerates Port, if applicable
Parameters
h IN: handle to open serial port
IsUsb IN: set to TRUE if serial port is really a USB connection
Returns
success state
Definition at line 1486 of file platform.c.
References SER_HANDLE_s::baudrate, COM, COM_BAUDRATE(), COM_CLOSE(), COM_OPEN(), FALSE, SER_HANDLE_s::handle, I2C, I2C_BAUDRATE(), MESSAGE(), MESSAGE_PLAIN(), MSG_DBG, NET, NET_BAUDRATE(), SER_HANDLE_s::pName, SPI, SPI_BAUDRATE(), SPU, STDINOUT, TIME_SLEEP(), TRUE, SER_HANDLE_s::type, and U2C.
Referenced by rcvReenumerate().
 {
     MESSAGE(MSG_DBG, "Re-enumerating...");
     switch(h->type)
     {
     case COM:
         {
             U4 retries = 10;
             COM_CLOSE(h->handle);
             do
             {
                 TIME_SLEEP(1000);
                 h->handle = COM_OPEN(h->pName);
                 if (h->handle)
                 {
                     return COM_BAUDRATE(h->handle, h->baudrate);
                 }
             }
             while ((h->handle == (HANDLE)0) && retries--);
         }
         break;
 #ifdef WIN32
     case STDINOUT:
         MESSAGE_PLAIN("<AC>Reenum %i<\\AC>", IsUsb);
         TIME_SLEEP(1000);   // Pause to allow host to perform operation
         return TRUE;
 #endif //ifdef WIN32
 #ifdef ENABLE_AARDVARK_SUPPORT
     case I2C:
         TIME_SLEEP(500);
         return I2C_BAUDRATE(h->handle,h->baudrate);
     case SPI:
         TIME_SLEEP(500);
         return SPI_BAUDRATE(h->handle,h->baudrate);
 #endif // ENABLE_AARDVARK_SUPPORT
 #ifdef ENABLE_DIOLAN_SUPPORT
     case U2C:
         TIME_SLEEP(500);
         return U2C_BAUDRATE(h->handle,h->baudrate);
     case SPU:
         TIME_SLEEP(500);
         return SPU_BAUDRATE(h->handle,h->baudrate);
 #endif // ENABLE_DIOLAN_SUPPORT
 #ifdef ENABLE_NET_SUPPORT
     case NET:
         TIME_SLEEP(500);
         return NET_BAUDRATE(h,h->baudrate);
 #endif // ENABLE_NET_SUPPORT
     default:
         break;
     }
     return FALSE;
 }
U4 SER_WRITE (SER_HANDLE_pt h, const void * p, U4 size)
Write to Serial Port.
Write data to serial port
Parameters
h IN: handle to open serial port
p IN: buffer to data to be written
size IN: number of bytes to be written
Returns
number of bytes written
Definition at line 1754 of file platform.c.
References COM, COM_WRITE(), SER_HANDLE_s::devAddr, SER_HANDLE_s::handle, I2C, I2C_WRITE(), NET, NET_WRITE(), SER_WRITE_SPI(), SPI, SPU, STDINOUT, SER_HANDLE_s::type, and U2C.
Referenced by rcvFlushBuffer(), and rcvRawSend().
 {
     switch(h->type)
     {
     case COM:
         return COM_WRITE(h->handle,p,size);
 #ifdef WIN32
     case STDINOUT:
         return STDOUT_WRITE(p,size);
 #endif //ifdef WIN32
 #ifdef ENABLE_AARDVARK_SUPPORT
     case I2C:
         return I2C_WRITE(h->handle,h->devAddr,p,size);
     case SPI:
         return SER_WRITE_SPI(h, p, size);
 #endif // ENABLE_AARDVARK_SUPPORT
 #ifdef ENABLE_DIOLAN_SUPPORT
     case U2C:
         return U2C_WRITE(h->handle,h->devAddr,p,size);
     case SPU:
         return SER_WRITE_SPI(h, p, size);
 #endif //ENABLE_DIOLAN_SUPPORT
 #ifdef ENABLE_NET_SUPPORT
     case NET:
         return NET_WRITE(h->handle,p,size);
 #endif // ENABLE_NET_SUPPORT
     default:
         break;
     }
     return 0;
 }
U4 SER_WRITE_SPI (SER_HANDLE_pt h, const void * p, U4 size)
Write to SPI Port.
Write data to SPI port. Successive 0xFF will be filtered out.
Parameters
h IN: handle to open serial port
p IN: buffer to data to be written
size IN: number of bytes to be written
Returns
number of bytes written
Definition at line 1542 of file platform.c.
References UBX_HEAD_s::classId, SER_HANDLE_s::handle, UBX_HEAD_s::msgId, NULL, SER_HANDLE_s::pData, SPI, SPI_WRITE(), SPU, SER_HANDLE_s::type, UBX_CLASS_UPD, UBX_UPD_FLWRI, and UbxCreateMessage().
Referenced by SER_WRITE().
 {
     // get the header of the UBX message
     UBX_HEAD_pt pUbxHdr = (UBX_HEAD_pt)p;
     // check for UPD-FLWRI message
     if(pUbxHdr->classId == UBX_CLASS_UPD && pUbxHdr->msgId == UBX_UPD_FLWRI)
     {
         // content of UPD-FLWRI message
         U4 targetAddress = 0;    // address where to write the data to
         U4 writeSize = 0;        // length of the payload to be written
         U4 startOfData = 0;      // where the data section starts
         U4 pos = 0;              // current position inside the complete packet
         U1 *pData = NULL;        // pointer to data section of packet
         U1 totalFF = 8;          // how many 0xFF in success are allowed
         U curSearch = 0;         // how man 0xFF have been already found
         // get the content of the UPD-FLWRI message
         memcpy(&targetAddress, (U4 *)((U1 *)p+sizeof(UBX_HEAD_t)), sizeof(targetAddress));
         memcpy(&writeSize,     (U4 *)((U1 *)p+sizeof(UBX_HEAD_t)+sizeof(targetAddress)), sizeof(writeSize));
         // set the pointer to the data
         pData = (U1 *)p + sizeof(UBX_HEAD_t) + sizeof(targetAddress) + sizeof(writeSize);
         while(pos < writeSize)
         {
             // get the current character
             U1 current = pData[pos];
             // compare to 0xFF
             if(current == 0xFF)
             {
                 // increment the 0xFF counter
                 curSearch++;
             }
             // something else found
             else
             {
                 // check if already more 0xFF have passed than allowed
                 if(curSearch > totalFF)
                 {
                     // check if anything has to be written
                     if(pos-startOfData-curSearch)
                     {
                         // calculate the new write address and the new size of the payload
                         U4 writeAddress = targetAddress+startOfData;
                         U4 newWriteSize    = pos-startOfData-curSearch;
                         CH *pMessage=NULL;
                         CH *pSendData = (CH*)malloc(newWriteSize+8);
                         if(!pSendData)
                             return 0;
                         size_t Size;
                         // get the data
                         memcpy(pSendData+0, &writeAddress, 4);
                         memcpy(pSendData+4, &newWriteSize, 4);
                         memcpy(pSendData+8, pData+startOfData, newWriteSize);
                         // create UBX message
                         UbxCreateMessage(UBX_CLASS_UPD, UBX_UPD_FLWRI, pSendData, newWriteSize+8, &pMessage, &Size);
                         // send the data to the receiver
                         switch(h->type)
{
 #ifdef ENABLE_AARDVARK_SUPPORT
                         case SPI:
                             SPI_WRITE(h->handle,(SPI_READBUFFER_pt)h->pData,pMessage,Size);
                             break;
 #endif // ENABLE_AARDVARK_SUPPORT
 #ifdef ENABLE_DIOLAN_SUPPORT
                         case SPU:
                             SPU_WRITE(h->handle,(SPI_READBUFFER_pt)h->pData,pMessage,Size);
                             break;
 #endif // ENABLE_DIOLAN_SUPPORT
                         default:
                             break;
                         }
                         // cleanup
                         free(pMessage);
                         free(pSendData);
                     }
                     // set the start of the new data to the current position (where data was found)
                     startOfData = pos;
                 }
                 // reset the 0xFF counter
                 curSearch = 0;
             }
             // increment the position pointer
             pos++;
         }
         // check if anything has to be written
         if(pos-startOfData-curSearch)
         {
             // calculate the new write address and the new size of the payload
             U4 writeAddress = targetAddress+startOfData;
             U4 newWriteSize2    = pos-startOfData-curSearch;
             CH *pMessage=NULL;
             CH *pSendData = (CH*) malloc(newWriteSize2+8);
             if(!pSendData)
                 return 0;
             size_t Size;
             // get the data
             memcpy(pSendData+0, &writeAddress, 4);
             memcpy(pSendData+4, &newWriteSize2, 4);
             memcpy(pSendData+8, pData+startOfData, newWriteSize2);
             // create UBX message
             UbxCreateMessage(UBX_CLASS_UPD, UBX_UPD_FLWRI, pSendData, newWriteSize2+8, &pMessage, &Size);
             // send the data to the receiver
             switch(h->type)
             {
 #ifdef ENABLE_AARDVARK_SUPPORT
             case SPI:
                 SPI_WRITE(h->handle,(SPI_READBUFFER_pt)h->pData,pMessage,Size);
                 break;
 #endif // ENABLE_AARDVARK_SUPPORT
 #ifdef ENABLE_DIOLAN_SUPPORT
             case SPU:
                 SPU_WRITE(h->handle,(SPI_READBUFFER_pt)h->pData,pMessage,Size);
                 break;
 #endif // ENABLE_DIOLAN_SUPPORT
             default:
                 break;
             }
             // cleanup
             free(pMessage);
             free(pSendData);
         }
         // no data could be found to be written -> send one single byte
         else
         {
             U4 newSize = 1;       // size is one single byte
             CH *pMessage=NULL;
             CH *pSendData = (CH*) malloc(newSize+8);
             if(!pSendData)
                 return 0;
             U1 newData = 0xFF;    // data is 0xFF
             size_t Size;
             // get the data
             memcpy(pSendData+0, &targetAddress, 4);
             memcpy(pSendData+4, &newSize, 4);
             memcpy(pSendData+8, &newData, newSize);
             // create the message
             UbxCreateMessage(UBX_CLASS_UPD, UBX_UPD_FLWRI, pSendData, newSize+8, &pMessage, &Size);
             // send the data to the receiver
             switch(h->type)
             {
 #ifdef ENABLE_AARDVARK_SUPPORT
             case SPI:
                 SPI_WRITE(h->handle,(SPI_READBUFFER_pt)h->pData,pMessage,Size);
                 break;
 #endif // ENABLE_AARDVARK_SUPPORT
 #ifdef ENABLE_DIOLAN_SUPPORT
             case SPU:
                 SPU_WRITE(h->handle,(SPI_READBUFFER_pt)h->pData,pMessage,Size);
                 break;
 #endif // ENABLE_DIOLAN_SUPPORT
             default:
                 break;
             }
             // cleanup
             free(pMessage);
             free(pSendData);
         }
         // fake the number of written bytes
         // such that the higher levels wont freak out
         return size;
     }
     // no UPD-FLWRI message
     else
     {
         // write data using standard write
         switch(h->type)
         {
 #ifdef ENABLE_AARDVARK_SUPPORT
         case SPI:
             return SPI_WRITE(h->handle,(SPI_READBUFFER_pt)h->pData,p,size);
 #endif // ENABLE_AARDVARK_SUPPORT
 #ifdef ENABLE_DIOLAN_SUPPORT
         case SPU:
             return SPU_WRITE(h->handle,(SPI_READBUFFER_pt)h->pData,p,size);
 #endif // ENABLE_DIOLAN_SUPPORT
         default:
             return 0;
         }
     }
 }
BOOL SPI_BAUDRATE (HANDLE h, U4 br)
set baudrate of SPI device
Parameters
h handle to device
br baudrate to set
Returns
TRUE
Definition at line 1066 of file platform.c.
References MESSAGE(), MSG_DBG, and TRUE.
Referenced by SER_BAUDRATE(), and SER_REENUM().
 {
     br = aa_spi_bitrate((Aardvark)h,br/1000);
     MESSAGE(MSG_DBG, "Baudrate %dkHz",br);
     return TRUE;
 }
void SPI_CLOSE (HANDLE h)
close SPI port
Parameters
h handle to device
Definition at line 1055 of file platform.c.
Referenced by SER_CLOSE().
 {
     aa_close((Aardvark)h);
 }
HANDLE SPI_OPEN (const CH * name, void ** pData)
open SPI port
Parameters
name name of the SPI port ("SPI0", "SPI1", ...)
pData pointer to receive read buffer memory this function will allocate
Returns
handle to the device
Definition at line 1008 of file platform.c.
References SPI_READBUFFER_s::buffer, MESSAGE(), MSG_DBG, MSG_ERR, SPI_READBUFFER_s::pBuffer, and SPI_READBUFFER_s::size.
Referenced by SER_OPEN().
 {
     int devIndex;
     // find device index
     int parsedFields = sscanf(name+3,"%d",&devIndex);
     // assign defaults
     if (parsedFields < 1)
     {
         devIndex = 0;
     }
     // get access to aardvark
     Aardvark dev = aa_open(devIndex);
     MESSAGE(MSG_DBG,"aardvark port %d SPI ",devIndex);
     // bail on invalid dev handle
     if ((int)dev < 0)
     {
         MESSAGE(MSG_ERR, "%s", aa_status_string((int)dev));
         *pData = 0;
         return (HANDLE)0;
     }
     // get memory for read buffer
     *pData = malloc(sizeof(SPI_READBUFFER_t));
     if (!*pData)
     {
         MESSAGE(MSG_ERR,"Could not get memory for read buffer");
         return (HANDLE)0;
     }
     memset(*pData,0,sizeof(SPI_READBUFFER_t));
     SPI_READBUFFER_pt pBuf = (SPI_READBUFFER_pt)(*pData);
     pBuf->pBuffer = pBuf->buffer;
     pBuf->size = 0;
     // enable SPI mode
     aa_configure(dev,  AA_CONFIG_SPI_GPIO);
     // configure
     aa_spi_configure(dev, AA_SPI_POL_RISING_FALLING, AA_SPI_PHASE_SAMPLE_SETUP, AA_SPI_BITORDER_MSB);
     aa_spi_master_ss_polarity(dev, AA_SPI_SS_ACTIVE_LOW);
     return (HANDLE)dev;
 }
U4 SPI_READ (HANDLE h, SPI_READBUFFER_pt pReadBuf, void * p, U4 size)
read data from SPI port
Parameters
h handle to device
pReadBuf pointer to device buffer structure
p pointer to user-allocated buffer of at least size size to receive data
size number of bytes to read
Returns
number of bytes read
Definition at line 1110 of file platform.c.
References SPI_READBUFFER_s::buffer, COMPSZ, MESSAGE(), MIN, MSG_ERR, SPI_READBUFFER_s::pBuffer, and SPI_READBUFFER_s::size.
Referenced by SER_READ().
 {
     if (pReadBuf->size)
     { // we have data buffered from last write access
         size = MIN(pReadBuf->size, size);
         memcpy(p, pReadBuf->pBuffer, size);
         pReadBuf->pBuffer += size;
         pReadBuf->size -= size;
         memmove(pReadBuf->buffer, pReadBuf->pBuffer, pReadBuf->size);
         pReadBuf->pBuffer = pReadBuf->buffer;
     }
     else
     {
         // there's no buffered data -> perform a read with dummy write
         // setup a dummy FF buffer to perform dummy write
         u08 tmpBuf[COMPSZ];
         memset(tmpBuf, 0xFF, sizeof(tmpBuf));
         size = MIN(size, sizeof(tmpBuf));
         U2 size1 = (U2)MIN(size, COMPSZ);
         // first read some bytes and check if they are all FF
         int written = aa_spi_write((Aardvark)h, size1, tmpBuf, size1, (u08*)p);
         if (written == AA_SPI_WRITE_ERROR)
         {
             MESSAGE(MSG_ERR, "SPI_READ read data1:%s (%d)", aa_status_string((int)written), written);
             return 0;
         }
         if (memcmp(p, tmpBuf, size1) != 0)
         {
             if (size > size1)
             {
                 // some bytes are not FF, so we have data. the UPD messages are short,
                 // so perform only short read accesses. the longer messages are normally fetched
                 // as a side effect of the longer write access when writing packets
                 p = (void*)((U1*)p + size1);
                 int written2 = aa_spi_write((Aardvark)h, (u16)size - size1, tmpBuf, (u16)size - size1, (u08*)p);
                 if (written2 == AA_SPI_WRITE_ERROR)
                 {
                     MESSAGE(MSG_ERR, "SPI_READ read data2:%s (%d)", aa_status_string((int)written2), written2);
                     return size1;
                 }
             }
         }
         else
         {
             // we received only FFs -> discard
             return 0;
         }
     }
     return size;
 }
U4 SPI_WRITE (HANDLE h, SPI_READBUFFER_pt pReadBuf, const void * p, U4 size)
write data to SPI port
Parameters
h handle to device
pReadBuf pointer to device buffer structure
p pointer to data to write
size size of data to write
Returns
number of bytes written
Definition at line 1082 of file platform.c.
References SPI_READBUFFER_s::buffer, MESSAGE(), MIN, MSG_ERR, SPI_READBUFFER_s::pBuffer, and SPI_READBUFFER_s::size.
Referenced by SER_WRITE_SPI().
 {
     // manage read buffer. as SPI always performs a read access and a write access at the
     //  same time, we temporarily store the data read and return it on an SPI_READ call
     U4 room = sizeof(pReadBuf->buffer)-(pReadBuf->size);
     size = MIN(room, size);
     // perform write/read
     int status = aa_spi_write((Aardvark)h,(u16)size,(u08*)p,(u16)size,(u08*)(pReadBuf->pBuffer + pReadBuf->size));
     if (status < 0)
     {
         MESSAGE(MSG_ERR, "SPI_WRITE write data:%s (%d)", aa_status_string((int)status),status);
         return 0;
     }
     pReadBuf->size += size;
     return size;
 }
U4 TIME_GET (void)
Get Timer.
Number of milliseconds that have elapsed since a OS/platform specific event. Don't use absolute values, but differences between subsequent calls to TIME_GET() to get a predictable behavior.
Returns
number of milliseconds
Definition at line 129 of file platform.c.
References NULL.
Referenced by MESSAGE(), rcvAckMessage(), rcvReceiveMessage(), UpdateFirmware(), updateImageToRam(), updDumpAck(), updEraseSector(), and updWritePacket().
 {
 #ifdef WIN32
     return GetTickCount();
 #else
     struct timeval tv;
     return (gettimeofday(&tv,NULL)==0) ?
         (U4)(tv.tv_sec*1000 + tv.tv_usec/1000) : 0;
 #endif
 }
void TIME_SLEEP (U4 time)
Sleep.
Sleep for time milliseconds
Parameters
time IN: number of milliseconds to sleep
Definition at line 120 of file platform.c.
Referenced by I2C_PENDING(), I2C_READ(), rcvReceiveMessage(), rcvSendTrainingSequence(), rcvSetBaud(), SER_REENUM(), UpdateFirmware(), and updProcessMessages().
 {
 #ifdef WIN32
     Sleep(ms);
 #else
     usleep(1000*ms);
 #endif
 }
Variable Documentation
int sCONSOLE_SAVEPOS_x static
Definition at line 2075 of file platform.c.
int sCONSOLE_SAVEPOS_y static
Definition at line 2074 of file platform.c.
struct termios sCONSOLE_tioSave static
Definition at line 2078 of file platform.c.
Referenced by CONSOLE_DONE(), and CONSOLE_INIT().
int verbose = 0
verbosity
Definition at line 111 of file platform.c.
Referenced by CanSendParentCommands(), MESSAGE(), UpdateFirmware(), updDumpAck(), and updInit().