ubxfwupdate: receiver.h File Reference
receiver.h File Reference
Declares the receiver communication interface.
#include <string.h>
#include <stdio.h>
#include "platform.h"
#include "ubxmsg.h"
Data Structures
struct RECEIVEBUF_s
The receive buffer to write into.
struct RCV_DATA_t
Structure that defines a connection.
Macros
#define RECEIVEBUF_SIZE 65536
receive buffer size
#define AUTOBAUD_TIMEOUT 300
timeout for autobauding
#define POLL_TIMEOUT 1000
timeout for getting a polled message
#define RETRY_COUNT_AUTOBAUD 5
Number of retries when autobauding.
#define RETRY_COUNT 3
Number of retries for status messages (except for erase/write)
Typedefs
typedef struct RECEIVEBUF_s RECEIVEBUF_t
The receive buffer to write into.
Functions
BOOL rcvConnect (RCV_DATA_t *rcv, const CH *comPort, U4 baudrate)
void rcvDisconnect (RCV_DATA_t *rcv)
UBX_HEAD_t * rcvPollMessage (RCV_DATA_t *rcv, U1 classId, U1 msgId, CH *payload, U4 payloadSize, U4 timeout)
int rcvAckMessage (RCV_DATA_t *rcv, U1 classId, U1 msgId, CH *payload, U4 payloadSize, U4 timeout)
UBX_HEAD_t * rcvReceiveMessage (RCV_DATA_t *rcv, U4 timeout, I4 classId, I4 msgId)
BOOL rcvSendMessage (RCV_DATA_t *rcv, U1 classId, U1 msgId, CH *payload, U4 payloadSize)
UBX_HEAD_t * rcvDoAutobaud (RCV_DATA_t *rcv, BOOL sendTrainingSequence)
BOOL rcvReenumerate (RCV_DATA_t *rcv, BOOL isUsbPort)
BOOL rcvSendTrainingSequence (RCV_DATA_t *rcv)
void rcvFlushBuffer (RCV_DATA_t *rcv)
BOOL rcvSetBaud (RCV_DATA_t *rcv, int baud)
Variables
const U4 gAutoBaudRates []
List of baudrates to use when autobauding.
Detailed Description
Declares the receiver communication interface.
Definition in file receiver.h.
Macro Definition Documentation
#define AUTOBAUD_TIMEOUT 300
timeout for autobauding
Definition at line 41 of file receiver.h.
Referenced by rcvDoAutobaud().
#define POLL_TIMEOUT 1000
timeout for getting a polled message
Definition at line 44 of file receiver.h.
Referenced by getNoFisMergingData(), UpdateFirmware(), and updateImageToRam().
#define RECEIVEBUF_SIZE 65536
receive buffer size
Definition at line 38 of file receiver.h.
Referenced by rcvReceiveMessage().
#define RETRY_COUNT 3
Number of retries for status messages (except for erase/write)
Definition at line 50 of file receiver.h.
Referenced by rcvAckMessage(), rcvPollMessage(), and UpdateFirmware().
#define RETRY_COUNT_AUTOBAUD 5
Number of retries when autobauding.
Definition at line 47 of file receiver.h.
Referenced by rcvDoAutobaud().
Typedef Documentation
typedef struct RECEIVEBUF_s RECEIVEBUF_t
The receive buffer to write into.
Function Documentation
int rcvAckMessage (RCV_DATA_t * rcv, U1 classId, U1 msgId, CH * payload, U4 payloadSize, U4 timeout)
Send a message to the receiver and wait until it is ack'd (or nack'd). When the timeout expires it retries RETRY_COUNT times.
Parameters
rcv receiver control structure
classId class id of the message to send
msgId the message id of the message to send
payload pointer to the payload to include in the message to send
payloadSize size of the payload
timeout timeout that has to expire before retry
Returns
0 if successful and nack received 1 if successful and ack received, -1 if timed out or something went wrong
Definition at line 193 of file receiver.c.
References UBX_ACK_ACK_s::clsId, UBX_HEAD_s::msgId, UBX_ACK_ACK_s::msgId, NULL, rcvReceiveMessage(), rcvSendMessage(), RETRY_COUNT, TIME_GET(), UBX_ACK_ACK, UBX_CLASS_ACK, and UBX_HEAD_SIZE.
Referenced by UpdateFirmware().
 {
     assert(rcv);
     assert( ( payload &&  payloadSize)
          || (!payload && !payloadSize));
     U4 retryCount;
     for(retryCount = 0; retryCount < RETRY_COUNT; retryCount++)
     {
         if( rcvSendMessage(rcv, classId, msgId,  payload, payloadSize) )
         {
             const U4 toTime = TIME_GET() + timeout;
             do // loop so message is not retransmitted when ACK from different (previous) message is already in buffor or is received.
             {
                 UBX_HEAD_t *ack = rcvReceiveMessage(rcv, toTime - TIME_GET(), UBX_CLASS_ACK, -1);
                 if (ack != NULL)
                 {
                     UBX_ACK_ACK_t *pAck = (UBX_ACK_ACK_t*)((U1*)ack + UBX_HEAD_SIZE);
                     if (pAck->clsId == classId &&
                         pAck->msgId == msgId)
                     {
                         BOOL success = ack->msgId == UBX_ACK_ACK;
                         free(ack);
                         return success ? 1 : 0;
                     }
                     free(ack);
                 }
             }
             while (TIME_GET() < toTime);
         }
     }
     return -1;
 }
BOOL rcvConnect (RCV_DATA_t * rcv, const CH * comPort, U4 baudrate)
Connect to the receiver
Parameters
rcv receiver control structure
comPort com port to connect to
baudrate baudrate to setup
Returns
TRUE if successful
Definition at line 95 of file receiver.c.
References FALSE, MESSAGE(), MSG_DBG, MSG_ERR, NULL, rcvClearBuffer(), rcvSetBaud(), SER_CLEAR(), and SER_OPEN().
Referenced by UpdateFirmware().
 {
     assert(rcv);
     rcv->mPortHandle = NULL;
     MESSAGE(MSG_DBG, "Trying to open port %s", comPort);
     rcv->mPortHandle = SER_OPEN(comPort);
     if (rcv->mPortHandle == (SER_HANDLE_t *)0)
     {
         MESSAGE(MSG_ERR, "Could not open communications port.");
         return FALSE;
     }
     // initialize the receiver buffer
     rcvClearBuffer(rcv);
     // clear the serial port
     SER_CLEAR(rcv->mPortHandle);
     return rcvSetBaud(rcv, baudrate);
 }
void rcvDisconnect (RCV_DATA_t * rcv)
Disconnect from the receiver if connected. This is done in the destructor.
Parameters
rcv receiver control structure
Definition at line 118 of file receiver.c.
References NULL, rcvClearBuffer(), SER_CLEAR(), and SER_CLOSE().
Referenced by UpdateFirmware().
 {
     assert(rcv);
     if(rcv->mPortHandle)
     {
         SER_CLEAR(rcv->mPortHandle);
         rcvClearBuffer(rcv);
         SER_CLOSE(rcv->mPortHandle);
         rcv->mPortHandle = NULL;
     }
 }
UBX_HEAD_t* rcvDoAutobaud (RCV_DATA_t * rcv, BOOL sendTrainingSequence)
Poll the message MON-VER from the receiver trying different baudrates
Parameters
rcv receiver control structure
sendTrainingSequence should the training sequence be sent or not
Returns
pointer to the MON-VER message received or NULL if communication failed on all baudrates
Definition at line 304 of file receiver.c.
References AUTOBAUD_TIMEOUT, gAutoBaudRates, MESSAGE(), MSG_DBG, MSG_ERR, NULL, NUMOF, rcvPollMessage(), rcvSendTrainingSequence(), rcvSetBaud(), RETRY_COUNT_AUTOBAUD, UBX_CLASS_MON, and UBX_MON_VER.
Referenced by UpdateFirmware().
 {
     assert(rcv);
     U4 retryCount = 0;
     U4 autoBaudIndex = 0;
     for(;;)
     {
         UBX_HEAD_t* msg = rcvPollMessage(rcv, UBX_CLASS_MON, UBX_MON_VER, NULL, 0, AUTOBAUD_TIMEOUT);
         if(msg != NULL)
         {
             MESSAGE(MSG_DBG,"Detected Baudrate is %d", rcv->mPortHandle->baudrate);
             return msg;
         }
         if (retryCount++ <= RETRY_COUNT_AUTOBAUD)
         {
             MESSAGE(MSG_DBG,"...retrying autobaud");
         }
         else if(autoBaudIndex < NUMOF(gAutoBaudRates))
         {
             // advance to the next baudrate
             MESSAGE(MSG_DBG, "Retrying with baudrate %d", gAutoBaudRates[autoBaudIndex]);
             rcvSetBaud(rcv, gAutoBaudRates[autoBaudIndex]);
             // send the training sequence
             if(sendTraining)
                 rcvSendTrainingSequence(rcv);
             ++autoBaudIndex;
             retryCount = 0;
         }
         else
         {
             MESSAGE(MSG_ERR, "Unable to Communicate on any Baudrate");
             return NULL;
         }
     }
 }
void rcvFlushBuffer (RCV_DATA_t * rcv)
Flush the receive buffer of the receiver by sending 1kB of garbage.
Parameters
rcv receiver control structure
Definition at line 361 of file receiver.c.
References rcvClearBuffer(), SER_CLEAR(), and SER_WRITE().
Referenced by UpdateFirmware().
 {
     assert(rcv);
     SER_CLEAR(rcv->mPortHandle);
     rcvClearBuffer(rcv);
     CH pCrap[1024];
     memset(pCrap, 0xFF, sizeof(pCrap));
     SER_WRITE(rcv->mPortHandle, pCrap, sizeof(pCrap));
 }
UBX_HEAD_t* rcvPollMessage (RCV_DATA_t * rcv, U1 classId, U1 msgId, CH * payload, U4 payloadSize, U4 timeout)
Poll a message from the receiver. When the timeout expires it retries RETRY_COUNT times.
Parameters
rcv receiver control structure
classId class id of the message to poll
msgId the message id of the message to poll
payload pointer to the payload to include in the message to poll, may be NULL
payloadSize size of the payload, must be NULL if payload is
timeout timeout that has to expire before retry
Returns
pointer to the received message or NULL if the polling failed
Definition at line 170 of file receiver.c.
References MESSAGE(), MSG_DBG, NULL, rcvPollMessageOnce(), and RETRY_COUNT.
Referenced by getNoFisMergingData(), rcvDoAutobaud(), UpdateFirmware(), and verifyImage().
 {
     assert(rcv);
     assert( ( payload &&  payloadSize)
          || (!payload && !payloadSize));
     U4 retryCount;
     for(retryCount = 0; retryCount < RETRY_COUNT; retryCount++)
     {
         UBX_HEAD_t* msg = rcvPollMessageOnce(rcv, classId, msgId,  payload, payloadSize, timeout);
         if(msg != NULL)
             return msg;
         MESSAGE(MSG_DBG, "Retry poll");
     }
     return NULL;
 }
UBX_HEAD_t* rcvReceiveMessage (RCV_DATA_t * rcv, U4 timeout, I4 classId, I4 msgId)
Receive a message with given class and message id from the receiver. If other messages with different class or message ids are received within the timeout they are discarded.
Parameters
rcv receiver control structure
timeout wait for timeout
classId class id of the message to receive
msgId message id of the message to receive
Returns
pointer to the received message or null if the timeout expired
Definition at line 232 of file receiver.c.
References UBX_HEAD_s::classId, UBX_HEAD_s::msgId, NULL, RECEIVEBUF_SIZE, SER_READ(), UBX_HEAD_s::size, TIME_GET(), TIME_SLEEP(), UBX_FRAME_SIZE, and UbxSearchMsg().
Referenced by rcvAckMessage(), rcvPollMessageOnce(), UpdateFirmware(), updateImageToRam(), updProcessMessages(), and updUpdate().
 {
     assert(rcv);
     const U4 toTime = TIME_GET() + timeout;
     do
     {
         U4 availableSize = RECEIVEBUF_SIZE - (rcv->mRecBuf.pEnd - rcv->mRecBuf.pCurrent);
         U4 received = SER_READ(rcv->mPortHandle, rcv->mRecBuf.pEnd, availableSize);
         rcv->mRecBuf.pEnd += received;
         U1* pMessageBegin = NULL;
         //parse buffer if a valid UBX message can be found
         //start at position pCurrent
         if (UbxSearchMsg(rcv->mRecBuf.pCurrent, rcv->mRecBuf.pEnd - rcv->mRecBuf.pCurrent, &pMessageBegin))
         {
             UBX_HEAD_t ubxhead;
             memcpy(&ubxhead, pMessageBegin, sizeof(ubxhead));
             CH* message = (CH*)malloc((ubxhead.size + UBX_FRAME_SIZE)*sizeof(CH));
             if (!message)
             {
                 return NULL;
             }
             // copy the message to the buffer
             memcpy(message, pMessageBegin, ubxhead.size + UBX_FRAME_SIZE);
             rcv->mRecBuf.pCurrent = pMessageBegin + ubxhead.size + UBX_FRAME_SIZE;
             // move the rest of the data to the beginning of the buffer
             memmove(rcv->mRecBuf.Buf, rcv->mRecBuf.pCurrent, rcv->mRecBuf.pEnd - rcv->mRecBuf.pCurrent);
             rcv->mRecBuf.pEnd -= rcv->mRecBuf.pCurrent - rcv->mRecBuf.Buf;
             rcv->mRecBuf.pCurrent = rcv->mRecBuf.Buf;
             if ((classId == -1 || classId == ubxhead.classId)
                 && (msgId == -1 || msgId == ubxhead.msgId))
             {
                 return (UBX_HEAD_t*)message;
             }
             free(message);
         }
         else
         {
             TIME_SLEEP(1); // don't loop at 100% CPU
         }
     }
     while(TIME_GET() < toTime);
     return NULL;
 }
BOOL rcvReenumerate (RCV_DATA_t * rcv, BOOL isUsbPort)
Reinitialize the connection
Parameters
rcv receiver control structure
isUsbPort set to TRUE if connected to a USB port
Returns
TRUE if successful
Definition at line 284 of file receiver.c.
References COM, FALSE, MESSAGE(), MSG_ERR, SER_REENUM(), and TRUE.
Referenced by UpdateFirmware().
 {
     assert(rcv);
     BOOL result=FALSE;
     if( (rcv->mPortHandle->type == COM && !isUsbPort)
      ||  SER_REENUM(rcv->mPortHandle, isUsbPort) )
     {
         // we just booted in safeboot mode, try to
         // re-fetch communication channel
         result=TRUE;
     }
     else
     {
         MESSAGE(MSG_ERR, "Reconnect failed.");
     }
     return result;
 }
BOOL rcvSendMessage (RCV_DATA_t * rcv, U1 classId, U1 msgId, CH * payload, U4 payloadSize)
Send a message to the receiver
Parameters
rcv receiver control structure
classId class id of the message to send
msgId message id of the message to send
payload pointer to the payload to include in the message to send
payloadSize size of the payload
Returns
TRUE if successful
Definition at line 142 of file receiver.c.
References FALSE, rcvRawSend(), and UbxCreateMessage().
Referenced by doReset(), rcvAckMessage(), rcvPollMessageOnce(), UpdateFirmware(), updateImageToRam(), updEraseSector(), and updSendWrite().
 {
     assert(rcv);
     assert( ( payload &&  payloadSize)
          || (!payload && !payloadSize));
     CH* pMessage;
     size_t Size;
     if (!UbxCreateMessage( classId
                          , msgId
                          , payload
                          , payloadSize
                          , &pMessage
                          , &Size ))
     {
         return FALSE;
     }
     U4 written = rcvRawSend(rcv, pMessage, Size);
     free(pMessage);
     return written == Size;
 }
BOOL rcvSendTrainingSequence (RCV_DATA_t * rcv)
Send the training sequence to the receiver
Parameters
rcv receiver control structure
Returns
TRUE if successful
Definition at line 130 of file receiver.c.
References MESSAGE(), MSG_DBG, rcvRawSend(), and TIME_SLEEP().
Referenced by rcvDoAutobaud(), and UpdateFirmware().
 {
     assert(rcv);
     CH trainingSequence[] = {0x55, 0x55};
     MESSAGE(MSG_DBG, "Sending training sequence");
     size_t size = sizeof(trainingSequence);
     BOOL success = rcvRawSend(rcv, trainingSequence, size) == size;
     TIME_SLEEP(10);
     return success;
 }
BOOL rcvSetBaud (RCV_DATA_t * rcv, int baud)
Set the baudrate of the connection
Parameters
rcv receiver control structure
baud baudrate to set
Returns
TRUE if successful
Definition at line 344 of file receiver.c.
References FALSE, MESSAGE(), MSG_DBG, MSG_ERR, rcvClearBuffer(), SER_BAUDRATE(), TIME_SLEEP(), and TRUE.
Referenced by rcvConnect(), rcvDoAutobaud(), and UpdateFirmware().
 {
     assert(rcv);
     rcvClearBuffer(rcv);
     MESSAGE(MSG_DBG, "Setting baudrate to %d", baud);
     //we got a serial port, configure it
     if (!SER_BAUDRATE(rcv->mPortHandle, baud))
     {
         MESSAGE(MSG_ERR, "Could not configure communications port.");
         return FALSE;
     }
     TIME_SLEEP(200);
     return TRUE;
 }
Variable Documentation
const U4 gAutoBaudRates[]
List of baudrates to use when autobauding.
Definition at line 35 of file receiver.c.
Referenced by rcvDoAutobaud().