ubxfwupdate: ubxmsg.c File Reference
ubxmsg.c File Reference
ubx message protocol wrapper
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "checksum.h"
#include "ubxmsg.h"
#include "platform.h"
Functions
BOOL UbxCreateMessage (U1 ClassId, U1 MsgId, const void *pPayload, const size_t PayloadSize, CH **ppMessage, size_t *pMsgSize)
Create an UBX message of specified type.
static BOOL UbxCheckCrc (U1 const *pkMsg)
Check CRC of UBX packet.
BOOL UbxSearchMsg (U1 *pBuffer, size_t Size, U1 **ppMsg)
Search for UBX message header.
Detailed Description
ubx message protocol wrapper
Definition in file ubxmsg.c.
Function Documentation
static BOOL UbxCheckCrc (U1 const * pkMsg) static
Check CRC of UBX packet.
Parameters
pkMsg pointer to beginning of UBX packet
Returns
TRUE if CRC is correct, FALSE otherwise
Definition at line 76 of file ubxmsg.c.
References GetUbxChecksumU1(), UBX_HEAD_s::size, UBX_CHKSUM_SIZE, UBX_FRAME_SIZE, UBX_HEAD_SIZE, and UBX_PREFIX_SIZE.
Referenced by UbxSearchMsg().
 {
     UBX_HEAD_t ubxhdr;
     memcpy(&ubxhdr, pkMsg, sizeof(ubxhdr));
     U2 crc =
         GetUbxChecksumU1((U1*)pkMsg+UBX_PREFIX_SIZE,
         ubxhdr.size+UBX_FRAME_SIZE-UBX_PREFIX_SIZE-UBX_CHKSUM_SIZE);
     //crc_b is in high byte
     U1 crc_a_packet = *(pkMsg+UBX_HEAD_SIZE+ubxhdr.size);
     U1 crc_b_packet = *(pkMsg+UBX_HEAD_SIZE+ubxhdr.size+1);
     U1 crc_a_calc = crc & 0x00FF;
     U1 crc_b_calc = (crc & 0xFF00) >> 8;
     return ((crc_a_packet == crc_a_calc) && (crc_b_packet == crc_b_calc));
 }
BOOL UbxCreateMessage (U1 ClassId, U1 MsgId, const void * pPayload, const size_t PayloadSize, CH ** ppMessage, size_t * pMsgSize)
Create an UBX message of specified type.
Creates a UBX message from the payload provided. Allocates memory that has to be freed by the caller. Wraps the UBX Frame around the Payload and calculates CRC.
Parameters
ClassId message's class ID
MsgId message's message ID
pPayload pointer to Payload data
PayloadSize Size of Payload
ppMessage pointer to Message
pMsgSize Message size including Frame
Returns
TRUE if memory could be allocated, FALSE else
Definition at line 38 of file ubxmsg.c.
References UBX_HEAD_s::classId, FALSE, GetUbxChecksumU1(), UBX_HEAD_s::msgId, NULL, UBX_HEAD_s::prefix, UBX_HEAD_s::size, TRUE, UBX_FRAME_SIZE, UBX_HEAD_SIZE, UBX_PREFIX, and UBX_PREFIX_SIZE.
Referenced by rcvSendMessage(), and SER_WRITE_SPI().
 {
     CH* pMsg = NULL;
     CH* pMsgBuf = NULL;
     {
         pMsgBuf = (CH*)malloc(PayloadSize + UBX_FRAME_SIZE);
         if (pMsgBuf == NULL)
             return FALSE;
         pMsg = pMsgBuf;
     }
     UBX_HEAD_t ubxhdr;
     ubxhdr.prefix = UBX_PREFIX;
     ubxhdr.classId = ClassId;
     ubxhdr.msgId = MsgId;
     ubxhdr.size = PayloadSize;
     memcpy(pMsg, &ubxhdr, sizeof(ubxhdr));
     if (PayloadSize && pPayload)
         memcpy(pMsg + UBX_HEAD_SIZE, pPayload, PayloadSize);
     U2 crc = GetUbxChecksumU1((U1*)pMsg + UBX_PREFIX_SIZE, PayloadSize + UBX_HEAD_SIZE - UBX_PREFIX_SIZE);
     memcpy(pMsg + UBX_HEAD_SIZE + PayloadSize, &crc, sizeof(crc));
     {
         *pMsgSize = PayloadSize + UBX_FRAME_SIZE;
     }
     *ppMessage = pMsgBuf;
     return TRUE;
 }
BOOL UbxSearchMsg (U1 * pBuffer, size_t Size, U1 ** ppMsg)
Search for UBX message header.
Search buffer for valid UBX message
Parameters
pBuffer Buffer containing received stream
Size Number of characters in Buffer
ppMsg pointer to the first message found if return value is TRUE, else pointer to the first occurrence of a possible message start (where crap is discarded)
Returns
TRUE if a valid message was found, FALSE else
Definition at line 92 of file ubxmsg.c.
References UBX_HEAD_s::classId, FALSE, MESSAGE(), MSG_WARN, UBX_HEAD_s::msgId, UBX_HEAD_s::size, TRUE, UBX_FRAME_SIZE, UBX_SYNC_CHAR_1, UBX_SYNC_CHAR_2, and UbxCheckCrc().
Referenced by rcvReceiveMessage().
 {
     BOOL valid = FALSE;
     BOOL ubxSyncFound = FALSE;
     //discard all invalid bytes
     do
     {
         ubxSyncFound = FALSE;
         //search for UBX prefix
         while (Size > 2 &&
                ((*pBuffer     != UBX_SYNC_CHAR_1) ||
                 (*(pBuffer+1) != UBX_SYNC_CHAR_2)) )
         {
             pBuffer ++;
             Size --;
         }
         if (Size > 2 &&
             ((*pBuffer     == UBX_SYNC_CHAR_1) &&
              (*(pBuffer+1) == UBX_SYNC_CHAR_2)))
         {
             ubxSyncFound = TRUE;
         }
         else
         {
             //not a whole sync sequence found, return
             //discard bytes where no sync was found in
             *ppMsg = pBuffer;
             return FALSE;
         }
         //everything before prefix is crap
         *ppMsg = pBuffer;
         //check if message is complete and valid
         if (ubxSyncFound && Size >= UBX_FRAME_SIZE)
         {
             //found message begin, this could be a valid message
             UBX_HEAD_t ubxhdr;
             memcpy(&ubxhdr, pBuffer, sizeof(ubxhdr));
             if ((ubxhdr.size + UBX_FRAME_SIZE) > 2*8192)
             {
                 // the message length is corrupt, u-blox5 will not send a message
                 // bigger than 16384 bytes, discard this message
                 MESSAGE(MSG_WARN, "Corrupt Packet (0x%02X-0x%02X): msg-length %u > 2*8192",
                     ubxhdr.classId, ubxhdr.msgId, ubxhdr.size);
                 pBuffer ++;
                 *ppMsg = pBuffer;
                 Size --;
             }
             if (Size >= ubxhdr.size + UBX_FRAME_SIZE)
             {
                 //check CRC
                 if (UbxCheckCrc(pBuffer))
                 {
                     {
                         valid = TRUE;
                     }
                 }
                 else
                 {
                     MESSAGE(MSG_WARN, "Packet (CLSID %02X-%02X): CRC-error", ubxhdr.classId, ubxhdr.msgId);
                     // discard faulty message from buffer
                     pBuffer ++;
                     *ppMsg = pBuffer;
                     Size --;
                 }
             }
             else
             {
                 // the message header is received completely, but the
                 // payload is not complete. wait for it
                 // MESSAGE(MSG_DBG, "msg incomplete: %d bytes/%d", Size, pHead->size+UBX_FRAME_SIZE);
                 return FALSE;
             }
         }
         else
         {
             // either there are no more valid messages in buffer or the received
             // message is not complete yet.
             return FALSE;
         }
     } while (!valid);
     return valid;
 }