ubxfwupdate: updateCore.h File Reference
updateCore.h File Reference
Declaration of function that handle the update on the receiver.
#include <stdio.h>
#include "receiver.h"
#include "flash.h"
#include "image.h"
Data Structures
struct UPD_CORE_t
Preserves the state of the upgrade and the organization of the flash.
Macros
#define PACKETSIZE 512
size of a packet to send to the receiver
#define ERASE_TIMEOUT 12000
timeout for erasing a sector
#define CRC_TIMEOUT 3000
timeout for the CRC computation
#define ERASE_RETRIES 4
number of retries to erase block
#define WRITE_RETRIES 4
number of retries to write block
#define WRITE_TIMEOUT 3000
timeout for writing a block
#define CHIP_ERASE_TIMEOUT 45000
chip erase timeout
#define FLASH_BASE 0x00800000
Flash base address.
#define RAM_BASE 0x00800000
RAM base address.
#define DUMPINTERVAL 1000
timeout between two dumps when verbose > 1
#define CONSOLE_WIDTH 80
Width of the console.
#define MAX_PENDING_ERASES 2
The maximum number of erase commands to be present in the receiver queue.
Typedefs
typedef enum ACK_STATE_e ACK_STATE_t
Acknowledge states.
Enumerations
enum ACK_STATE_e {
ACK_INIT = '.', ACK_ERASE_SENT = 'e', ACK_ERASE_ACK = 'E', ACK_WRITE_SENT = 'w',
ACK_WRITE_ACK = 'W', ACK_UNKNOWN = '?'
}
Acknowledge states.
Functions
UPD_CORE_t * updInit (RCV_DATA_t *rx, I4 numberSectors, I4 numberPackets, BLOCK_ARR_t *flashOrg, U4 flashSize, U4 MaxPendingWritesNum, BOOL eraseInProgres)
void updDeinit (UPD_CORE_t *upd)
BOOL updUpdate (UPD_CORE_t *upd, FWHEADER_t *data, size_t size, U4 fwBase)
Detailed Description
Declaration of function that handle the update on the receiver.
Definition in file updateCore.h.
Macro Definition Documentation
#define CHIP_ERASE_TIMEOUT 45000
chip erase timeout
Definition at line 43 of file updateCore.h.
Referenced by updUpdate(), and updWritePacket().
#define CONSOLE_WIDTH 80
Width of the console.
Definition at line 47 of file updateCore.h.
Referenced by updDumpAck(), and updInit().
#define CRC_TIMEOUT 3000
timeout for the CRC computation
Definition at line 39 of file updateCore.h.
Referenced by verifyImage().
#define DUMPINTERVAL 1000
timeout between two dumps when verbose > 1
Definition at line 46 of file updateCore.h.
Referenced by updDumpAck().
#define ERASE_RETRIES 4
number of retries to erase block
Definition at line 40 of file updateCore.h.
Referenced by updEraseSector().
#define ERASE_TIMEOUT 12000
timeout for erasing a sector
Definition at line 38 of file updateCore.h.
Referenced by updEraseSector().
#define FLASH_BASE 0x00800000
Flash base address.
Definition at line 44 of file updateCore.h.
Referenced by UpdateFirmware().
#define MAX_PENDING_ERASES 2
The maximum number of erase commands to be present in the receiver queue.
Definition at line 49 of file updateCore.h.
Referenced by updEraseSector().
#define PACKETSIZE 512
size of a packet to send to the receiver
Definition at line 37 of file updateCore.h.
Referenced by UpdateFirmware(), updDumpAck(), updEraseSector(), updInit(), updProcessMessages(), and updSendWrite().
#define RAM_BASE 0x00800000
RAM base address.
Definition at line 45 of file updateCore.h.
Referenced by UpdateFirmware().
#define WRITE_RETRIES 4
number of retries to write block
Definition at line 41 of file updateCore.h.
Referenced by updWritePacket().
#define WRITE_TIMEOUT 3000
timeout for writing a block
Definition at line 42 of file updateCore.h.
Referenced by UpdateFirmware(), and updWritePacket().
Typedef Documentation
typedef enum ACK_STATE_e ACK_STATE_t
Acknowledge states.
Enumeration Type Documentation
enum ACK_STATE_e
Acknowledge states.
Enumerator
ACK_INIT
initial state
ACK_ERASE_SENT
erase pending for packet (sector-blocks)
ACK_ERASE_ACK
erase acknowledged for packet
ACK_WRITE_SENT
write pending for packet
ACK_WRITE_ACK
write acknowledged for packet
ACK_UNKNOWN
unknown state
Definition at line 52 of file updateCore.h.
 {
     ACK_INIT        = '.',  //!< initial state
     ACK_ERASE_SENT  = 'e',  //!< erase pending for packet (sector-blocks)
     ACK_ERASE_ACK   = 'E',  //!< erase acknowledged for packet
     ACK_WRITE_SENT  = 'w',  //!< write pending for packet
     ACK_WRITE_ACK   = 'W',  //!< write acknowledged for packet
     ACK_UNKNOWN     = '?'   //!< unknown state
 } ACK_STATE_t;
Function Documentation
void updDeinit (UPD_CORE_t * upd)
De-Initializer for UPD_CORE_t
Parameters
upd control structure
Definition at line 563 of file updateCore.c.
References UPD_CORE_t::pEraseRetryCnt, UPD_CORE_t::pEraseState, UPD_CORE_t::pEraseTimeout, UPD_CORE_t::pWriteRetryCnt, UPD_CORE_t::pWriteState, and UPD_CORE_t::pWriteTimeout.
Referenced by UpdateFirmware(), and updInit().
 {
     assert(upd);
     free(upd->pEraseTimeout);
     free(upd->pEraseRetryCnt);
     free(upd->pEraseState);
     free(upd->pWriteTimeout);
     free(upd->pWriteRetryCnt);
     free(upd->pWriteState);
     free(upd);
 }
UPD_CORE_t* updInit (RCV_DATA_t * rx, I4 numberSectors, I4 numberPackets, BLOCK_ARR_t * flashOrg, U4 flashSize, U4 MaxPendingWritesNum, BOOL eraseInProgres)
Initializer for UPD_CORE_t.
Parameters
rx receiver to do the update on
numberSectors number of sectors to erase
numberPackets number of packets to write
flashOrg information about the organization of the flash
flashSize size of the flash
MaxPendingWritesNum Maximum possible number of pending writes
eraseInProgres Means that flash erase was started but not finished before entering update.
Returns
The control structure on success, NULL on fail
Definition at line 480 of file updateCore.c.
References ACK_ERASE_ACK, ACK_INIT, CONSOLE_SAVE_POS(), CONSOLE_WIDTH, UPD_CORE_t::erasedUntil, UPD_CORE_t::eraseInProgres, UPD_CORE_t::FlashOrg, UPD_CORE_t::FlashSize, GetPacketNrForSector(), UPD_CORE_t::MaxPendingWritesNum, MESSAGE(), MSG_LEV1, NULL, UPD_CORE_t::NumberPackets, UPD_CORE_t::NumberSectors, PACKETSIZE, UPD_CORE_t::PendingErases, UPD_CORE_t::PendingWrites, UPD_CORE_t::pEraseRetryCnt, UPD_CORE_t::pEraseState, UPD_CORE_t::pEraseTimeout, UPD_CORE_t::pWriteRetryCnt, UPD_CORE_t::pWriteState, UPD_CORE_t::pWriteTimeout, UPD_CORE_t::Rx, UPD_CORE_t::sLastDumpTime, updDeinit(), verbose, and UPD_CORE_t::writtenUntil.
Referenced by UpdateFirmware().
 {
     assert(rx);
     UPD_CORE_t *upd= (UPD_CORE_t*) malloc(sizeof(*upd));
     if(!upd)
         return NULL;
     memset(upd, 0, sizeof(*upd));
     upd->Rx = rx;
     // we did not yet erase / write anything
     upd->erasedUntil = 0;
     upd->writtenUntil = 0;
     upd->NumberSectors = numberSectors;
     upd->NumberPackets = numberPackets;
     upd->FlashOrg = flashOrg;
     upd->FlashSize = flashSize;
     upd->MaxPendingWritesNum = MaxPendingWritesNum;
     upd->eraseInProgres = eraseInProgres;
     upd->PendingErases  = 0;
     upd->PendingWrites  = 0;
     upd->sLastDumpTime  = 0;
     upd->pEraseTimeout  = (U4*) malloc(sizeof(U4)*upd->NumberSectors);
     upd->pEraseRetryCnt = (U1*) malloc(sizeof(U1)*upd->NumberSectors);
     upd->pEraseState    = (CH*) malloc(sizeof(CH)*upd->NumberSectors);
     upd->pWriteTimeout  = (U4*) malloc(sizeof(U4)*upd->NumberPackets);
     upd->pWriteRetryCnt = (U1*) malloc(sizeof(U1)*upd->NumberPackets);
     upd->pWriteState    = (CH*) malloc(sizeof(CH)*upd->NumberPackets);
     if( !upd->pEraseTimeout
      || !upd->pEraseRetryCnt
      || !upd->pEraseState
      || !upd->pWriteTimeout
      || !upd->pWriteRetryCnt
      || !upd->pWriteState )
     {
         updDeinit(upd);
         return NULL;
     }
     memset(upd->pEraseTimeout,  0,        upd->NumberSectors*sizeof(U4));
     memset(upd->pEraseRetryCnt, 0,        upd->NumberSectors*sizeof(U1));
     memset(upd->pEraseState,    ACK_INIT, upd->NumberSectors*sizeof(CH));
     memset(upd->pWriteTimeout,  0,        upd->NumberPackets*sizeof(U4));
     memset(upd->pWriteRetryCnt, 0,        upd->NumberPackets*sizeof(U1));
     memset(upd->pWriteState,    (upd->NumberSectors == 0)?ACK_ERASE_ACK:ACK_INIT, upd->NumberPackets*sizeof(CH));
     MESSAGE(MSG_LEV1, "Receiver info collected, downloading to flash...");
     if(verbose > 1)
     {
         I4 numPacketsOverall = (upd->NumberSectors == 0)?upd->NumberPackets:GetPacketNrForSector(upd->NumberSectors, upd->FlashOrg, PACKETSIZE);
         // compute the number of lines needed to do a full dump
         // CONSOLE_WIDTH - 1 to make sure that the newline character is not
         // placed on a new line (seen in windows 7)
         U4 numberOfLines = numPacketsOverall / (CONSOLE_WIDTH - 1);
         if(numPacketsOverall % (CONSOLE_WIDTH - 1) != 0)
             ++numberOfLines;
         // for the max retries and the newline
         numberOfLines += 2;
         CONSOLE_SAVE_POS(numberOfLines);
     }
     return upd;
 }
BOOL updUpdate (UPD_CORE_t * upd, FWHEADER_t * data, size_t size, U4 fwBase)
Do the update.
Parameters
upd control structure
data pointer to the data to write
size size of the data
fwBase start address of the firmware on the flash
Returns
TRUE if successful
Definition at line 578 of file updateCore.c.
References ACK_ERASE_ACK, ACK_WRITE_ACK, CHIP_ERASE_TIMEOUT, UPD_CORE_t::eraseInProgres, FALSE, UPD_CORE_t::FwBase, UPD_CORE_t::ImageSize, MESSAGE(), MSG_DBG, MSG_ERR, NULL, UPD_CORE_t::NumberPackets, UPD_CORE_t::NumberSectors, UPD_CORE_t::pData, UPD_CORE_t::pEraseState, UPD_CORE_t::pWriteState, rcvReceiveMessage(), UPD_CORE_t::Rx, UBX_HEAD_s::size, TRUE, UBX_CLASS_UPD, UBX_HEAD_SIZE, UBX_UPD_CERASE, updDumpAck(), updEraseSector(), updProcessMessages(), and updWritePacket().
Referenced by UpdateFirmware().
 {
     assert(upd);
     upd->pData = data;
     upd->ImageSize = size;
     upd->FwBase = fwBase;
     BOOL writeComplete = (upd->NumberPackets == 0);
     BOOL eraseComplete = (upd->NumberSectors == 0);
     updDumpAck(upd, TRUE);
     // loop around until everything is written and erased
     while( !writeComplete || !eraseComplete )
     {
         if( !eraseComplete )
         {
             // try to send an erase command
             if( !updEraseSector(upd) )
                 return FALSE;
             updDumpAck(upd, FALSE);
             // receive messages
             if( !updProcessMessages(upd) )
                 return FALSE;
             // check if everything is erased completely
             eraseComplete = TRUE;
             I4 sector;
             for(sector = 0; sector < upd->NumberSectors; sector++)
             {
                 if (upd->pEraseState[sector] != ACK_ERASE_ACK)
                 {
                     eraseComplete = FALSE;
                     break;
                 }
             }
         }
         if( !writeComplete )
         {
             // try to send write command
             if (!updWritePacket(upd))
             {
                 return FALSE;
             }
             updDumpAck(upd, FALSE);
             // receive messages
             if( !updProcessMessages(upd) )
             {
                 return FALSE;
             }
             // check if everything was written completely
             writeComplete = TRUE;
             I4 pack;
             for(pack = 0; pack < upd->NumberPackets; pack++)
             {
                 if (upd->pWriteState[pack] != ACK_WRITE_ACK)
                 {
                     writeComplete = FALSE;
                     break;
                 }
             }
         }
     }
     updDumpAck(upd, TRUE);
     if (upd->eraseInProgres)
     {
         UBX_HEAD_t* cErase = rcvReceiveMessage(upd->Rx, CHIP_ERASE_TIMEOUT, UBX_CLASS_UPD, UBX_UPD_CERASE);
         if (cErase == NULL)
         {
             MESSAGE(MSG_ERR, "Chip erase timed out");
             return FALSE;
         }
         if (cErase->size != 1)
         {
             if (((U1*)cErase)[UBX_HEAD_SIZE] == 1)
             {
                 MESSAGE(MSG_DBG, "Chip erase finished later than update proces");
             }
             else
             {
                 MESSAGE(MSG_ERR, "Chip erase failed");
                 return FALSE;
             }
         }
     }
     return TRUE;
 }